//! Source-neutral theorem certificates and typed-channel transaction protocol.
//!
//! Grammar recognition proves that a reflected value belongs to a syntactic
//! category.  Stateful admission is a separate judgment: a channel is indexed
//! by an installed language and a theorem, and mutation is permitted only after
//! a certificate has been checked and both language and space authority have
//! been revalidated at the commit boundary.  This module owns that small,
//! runtime-neutral kernel; it deliberately owns no tuple-space persistence.

use crate::{
    CategoryId, InstalledLanguageHandle, InstalledLanguageTable, LanguageAccessError, LanguageRight,
};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::sync::{Arc, RwLock};

pub const STRUCTURAL_THEOREM_CHECKER_ABI_V1: &str = "mettail-structural-theorem-checker/1";
pub const STRUCTURAL_THEOREM_LIMIT_PROFILE_V1: &str = "mettail-structural-theorem-limits/1";
pub const STRUCTURAL_ADMISSION_WORK_UNITS: u64 = 1;

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TheoremId(pub [u8; 32]);

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TermHash(pub [u8; 32]);

/// Canonical quotient of conjunctions generated by category membership and
/// exact-term predicates.
///
/// `meet` is associative, commutative, and idempotent.  Contradictory
/// conjunctions normalize to `Bottom`, so neither equality nor refinement ever
/// traverses a user-sized theorem tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AdmissionTheorem {
    Bottom,
    Membership(CategoryId),
    ExactTerm {
        category: CategoryId,
        term_hash: TermHash,
    },
}

impl AdmissionTheorem {
    pub const fn membership(category: CategoryId) -> Self {
        Self::Membership(category)
    }

    pub const fn exact(category: CategoryId, term_hash: TermHash) -> Self {
        Self::ExactTerm { category, term_hash }
    }

    pub fn id(self) -> TheoremId {
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-admission-theorem/1\0");
        match self {
            Self::Bottom => {
                hasher.update(&[0]);
            },
            Self::Membership(category) => {
                hasher.update(&[1]);
                hasher.update(&category.0.to_be_bytes());
            },
            Self::ExactTerm { category, term_hash } => {
                hasher.update(&[2]);
                hasher.update(&category.0.to_be_bytes());
                hasher.update(&term_hash.0);
            },
        }
        TheoremId(*hasher.finalize().as_bytes())
    }

    pub const fn category(self) -> Option<CategoryId> {
        match self {
            Self::Bottom => None,
            Self::Membership(category) | Self::ExactTerm { category, .. } => Some(category),
        }
    }

    pub fn meet(self, other: Self) -> Self {
        match (self, other) {
            (Self::Bottom, _) | (_, Self::Bottom) => Self::Bottom,
            (Self::Membership(left), Self::Membership(right)) => {
                if left.0 == right.0 {
                    Self::Membership(left)
                } else {
                    Self::Bottom
                }
            },
            (
                Self::ExactTerm { category: exact_category, term_hash },
                Self::Membership(member_category),
            )
            | (
                Self::Membership(member_category),
                Self::ExactTerm { category: exact_category, term_hash },
            ) => {
                if exact_category.0 == member_category.0 {
                    Self::ExactTerm { category: exact_category, term_hash }
                } else {
                    Self::Bottom
                }
            },
            (
                Self::ExactTerm {
                    category: left_category,
                    term_hash: left_hash,
                },
                Self::ExactTerm {
                    category: right_category,
                    term_hash: right_hash,
                },
            ) => {
                if left_category.0 == right_category.0 && left_hash.0 == right_hash.0 {
                    Self::ExactTerm {
                        category: left_category,
                        term_hash: left_hash,
                    }
                } else {
                    Self::Bottom
                }
            },
        }
    }

    /// `self` refines `target` when every term satisfying `self` also satisfies
    /// `target`.  Bottom is the initial object of this implication preorder.
    pub fn refines(self, target: Self) -> bool {
        match (self, target) {
            (Self::Bottom, _) => true,
            (_, Self::Bottom) => false,
            (Self::Membership(left), Self::Membership(right)) => left.0 == right.0,
            (
                Self::ExactTerm {
                    category: left_category,
                    term_hash: left_hash,
                },
                Self::ExactTerm {
                    category: right_category,
                    term_hash: right_hash,
                },
            ) => left_category.0 == right_category.0 && left_hash.0 == right_hash.0,
            (
                Self::ExactTerm { category: exact_category, .. },
                Self::Membership(member_category),
            ) => exact_category.0 == member_category.0,
            (Self::Membership(_), Self::ExactTerm { .. }) => false,
        }
    }

    pub fn holds(self, term: CanonicalFltTerm) -> bool {
        match self {
            Self::Bottom => false,
            Self::Membership(category) => category.0 == term.category.0,
            Self::ExactTerm { category, term_hash } => {
                category.0 == term.category.0 && term_hash.0 == term.term_hash.0
            },
        }
    }
}

/// The source-neutral identity of an FLT after an authorized adapter has
/// checked its concrete representation against the installed grammar.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CanonicalFltTerm {
    language: [u8; 32],
    category: CategoryId,
    term_hash: TermHash,
}

impl CanonicalFltTerm {
    const fn structurally_admitted(
        language: [u8; 32],
        category: CategoryId,
        term_hash: TermHash,
    ) -> Self {
        Self { language, category, term_hash }
    }

    pub const fn language(self) -> [u8; 32] {
        self.language
    }

    pub const fn category(self) -> CategoryId {
        self.category
    }

    pub const fn term_hash(self) -> TermHash {
        self.term_hash
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmissionCertificate {
    term: CanonicalFltTerm,
    theorem: AdmissionTheorem,
    theorem_id: TheoremId,
    checker_abi: String,
    limit_profile: String,
    evidence: Vec<u8>,
    evidence_hash: [u8; 32],
}

impl AdmissionCertificate {
    pub const fn term(&self) -> CanonicalFltTerm {
        self.term
    }

    pub const fn theorem(&self) -> AdmissionTheorem {
        self.theorem
    }

    pub const fn theorem_id(&self) -> TheoremId {
        self.theorem_id
    }

    pub fn checker_abi(&self) -> &str {
        &self.checker_abi
    }

    pub fn limit_profile(&self) -> &str {
        &self.limit_profile
    }

    pub fn evidence(&self) -> &[u8] {
        &self.evidence
    }

    pub const fn evidence_hash(&self) -> [u8; 32] {
        self.evidence_hash
    }

    /// Package evidence produced by a trusted checker.  This constructor does
    /// not make the evidence authoritative: the selected `AdmissionChecker`
    /// must still return `Proven` for this exact envelope before admission.
    pub fn from_checked_evidence(
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
        checker_abi: impl Into<String>,
        limit_profile: impl Into<String>,
        evidence: Vec<u8>,
    ) -> Self {
        let theorem_id = theorem.id();
        let checker_abi = checker_abi.into();
        let limit_profile = limit_profile.into();
        let evidence_hash =
            certificate_evidence_hash(term, theorem_id, &checker_abi, &limit_profile, &evidence);
        Self {
            term,
            theorem,
            theorem_id,
            checker_abi,
            limit_profile,
            evidence,
            evidence_hash,
        }
    }

    fn has_valid_envelope_for(
        &self,
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
        checker_abi: &str,
        limit_profile: &str,
    ) -> bool {
        self.term == term
            && self.theorem == theorem
            && self.theorem_id == theorem.id()
            && self.checker_abi == checker_abi
            && self.limit_profile == limit_profile
            && self.evidence_hash
                == certificate_evidence_hash(
                    self.term,
                    self.theorem_id,
                    &self.checker_abi,
                    &self.limit_profile,
                    &self.evidence,
                )
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CertificateError {
    TheoremDoesNotHold,
    CertificateMismatch,
}

impl fmt::Display for CertificateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::TheoremDoesNotHold => "the admission theorem does not hold for the FLT",
            Self::CertificateMismatch => "the admission certificate is not canonical",
        })
    }
}

impl std::error::Error for CertificateError {}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AdmissionBudget {
    pub max_work_units: u64,
    pub max_evidence_bytes: u64,
}

impl AdmissionBudget {
    pub const fn new(max_work_units: u64, max_evidence_bytes: u64) -> Self {
        Self { max_work_units, max_evidence_bytes }
    }

    pub const fn structural() -> Self {
        Self::new(1, 0)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AdmissionUsage {
    pub logical_work_units: u64,
    pub evidence_bytes: u64,
}

impl AdmissionUsage {
    pub const fn new(logical_work_units: u64, evidence_bytes: u64) -> Self {
        Self { logical_work_units, evidence_bytes }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AdmissionRefutation {
    TheoremDoesNotHold,
    CertificateMismatch,
    CheckerDefined(u32),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AdmissionUndetermined {
    WorkBudgetExhausted { required: u64, available: u64 },
    EvidenceBudgetExhausted { required: u64, available: u64 },
    CheckerDefined(u32),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProvenAdmission {
    certificate: Arc<AdmissionCertificate>,
    usage: AdmissionUsage,
}

impl ProvenAdmission {
    /// Package a checker's positive result for kernel validation. Construction
    /// alone grants no authority: the theorem-channel kernel independently
    /// checks the complete certificate envelope, checker identity, limit
    /// profile, and reported usage before it can prepare a transaction.
    pub fn from_checked_certificate(
        certificate: AdmissionCertificate,
        usage: AdmissionUsage,
    ) -> Self {
        Self {
            certificate: Arc::new(certificate),
            usage,
        }
    }

    pub fn certificate(&self) -> &AdmissionCertificate {
        &self.certificate
    }

    pub fn term(&self) -> CanonicalFltTerm {
        self.certificate.term
    }

    pub const fn usage(&self) -> AdmissionUsage {
        self.usage
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AdmissionDecision {
    Proven(ProvenAdmission),
    Refuted {
        reason: AdmissionRefutation,
        usage: AdmissionUsage,
    },
    Undetermined {
        reason: AdmissionUndetermined,
        usage: AdmissionUsage,
    },
}

impl AdmissionDecision {
    pub const fn usage(&self) -> AdmissionUsage {
        match self {
            Self::Proven(proof) => proof.usage,
            Self::Refuted { usage, .. } | Self::Undetermined { usage, .. } => *usage,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct AdmissionRequest<'a> {
    pub term: CanonicalFltTerm,
    pub theorem: AdmissionTheorem,
    pub presented_certificate: Option<&'a AdmissionCertificate>,
    pub budget: AdmissionBudget,
}

/// Source-neutral, bounded theorem admission.  Implementations may embody a
/// structural checker or an installed `TheoryCore`; only `Proven` may cross
/// the transaction boundary, while exhaustion must return `Undetermined`.
///
/// Implementations are trusted host components, not grammar-provided
/// capabilities. They must be deterministic functions of the complete
/// request, account every unit of logical work and evidence against `budget`,
/// and return `Undetermined` before exceeding either bound. The kernel treats
/// their output as untrusted data until its envelope and reported usage have
/// been validated.
pub trait AdmissionChecker: fmt::Debug + Send + Sync {
    fn checker_abi(&self) -> &str;

    fn limit_profile(&self) -> &str;

    fn check(&self, request: AdmissionRequest<'_>) -> AdmissionDecision;
}

/// Total checker for the structural theorem fragment.  Stronger theorem
/// engines implement the same source-neutral certificate contract at a
/// separately authorized boundary; proof search is not part of this checker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StructuralTheoremChecker {
    checker_abi: String,
    limit_profile: String,
}

impl Default for StructuralTheoremChecker {
    fn default() -> Self {
        Self::new(STRUCTURAL_THEOREM_CHECKER_ABI_V1, STRUCTURAL_THEOREM_LIMIT_PROFILE_V1)
    }
}

impl StructuralTheoremChecker {
    pub fn new(checker_abi: impl Into<String>, limit_profile: impl Into<String>) -> Self {
        Self {
            checker_abi: checker_abi.into(),
            limit_profile: limit_profile.into(),
        }
    }

    pub fn checker_abi(&self) -> &str {
        &self.checker_abi
    }

    pub fn limit_profile(&self) -> &str {
        &self.limit_profile
    }

    pub fn check(
        &self,
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
    ) -> Result<AdmissionCertificate, CertificateError> {
        if !theorem.holds(term) {
            return Err(CertificateError::TheoremDoesNotHold);
        }
        Ok(AdmissionCertificate::from_checked_evidence(
            term,
            theorem,
            self.checker_abi.clone(),
            self.limit_profile.clone(),
            Vec::new(),
        ))
    }

    pub fn verify(&self, certificate: &AdmissionCertificate) -> Result<(), CertificateError> {
        if !certificate.has_valid_envelope_for(
            certificate.term,
            certificate.theorem,
            &self.checker_abi,
            &self.limit_profile,
        ) || !certificate.theorem.holds(certificate.term)
        {
            return Err(CertificateError::CertificateMismatch);
        }
        Ok(())
    }
}

impl AdmissionChecker for StructuralTheoremChecker {
    fn checker_abi(&self) -> &str {
        &self.checker_abi
    }

    fn limit_profile(&self) -> &str {
        &self.limit_profile
    }

    fn check(&self, request: AdmissionRequest<'_>) -> AdmissionDecision {
        let evidence_bytes = request
            .presented_certificate
            .map_or(0, |certificate| u64::try_from(certificate.evidence.len()).unwrap_or(u64::MAX));
        let usage = AdmissionUsage::new(STRUCTURAL_ADMISSION_WORK_UNITS, evidence_bytes);
        if request.budget.max_work_units < STRUCTURAL_ADMISSION_WORK_UNITS {
            return AdmissionDecision::Undetermined {
                reason: AdmissionUndetermined::WorkBudgetExhausted {
                    required: STRUCTURAL_ADMISSION_WORK_UNITS,
                    available: request.budget.max_work_units,
                },
                usage,
            };
        }
        if request.budget.max_evidence_bytes < evidence_bytes {
            return AdmissionDecision::Undetermined {
                reason: AdmissionUndetermined::EvidenceBudgetExhausted {
                    required: evidence_bytes,
                    available: request.budget.max_evidence_bytes,
                },
                usage,
            };
        }
        if let Some(certificate) = request.presented_certificate {
            if !certificate.has_valid_envelope_for(
                request.term,
                request.theorem,
                &self.checker_abi,
                &self.limit_profile,
            ) || !request.theorem.holds(request.term)
            {
                return AdmissionDecision::Refuted {
                    reason: AdmissionRefutation::CertificateMismatch,
                    usage,
                };
            }
            return AdmissionDecision::Proven(ProvenAdmission::from_checked_certificate(
                certificate.clone(),
                usage,
            ));
        }
        if !request.theorem.holds(request.term) {
            return AdmissionDecision::Refuted {
                reason: AdmissionRefutation::TheoremDoesNotHold,
                usage,
            };
        }
        AdmissionDecision::Proven(ProvenAdmission::from_checked_certificate(
            AdmissionCertificate::from_checked_evidence(
                request.term,
                request.theorem,
                self.checker_abi.clone(),
                self.limit_profile.clone(),
                Vec::new(),
            ),
            usage,
        ))
    }
}

fn certificate_evidence_hash(
    term: CanonicalFltTerm,
    theorem_id: TheoremId,
    checker_abi: &str,
    limit_profile: &str,
    evidence: &[u8],
) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"mettail-admission-certificate/1\0");
    hasher.update(&term.language);
    hasher.update(&term.category.0.to_be_bytes());
    hasher.update(&term.term_hash.0);
    hasher.update(&theorem_id.0);
    hash_field(&mut hasher, checker_abi.as_bytes());
    hash_field(&mut hasher, limit_profile.as_bytes());
    hash_field(&mut hasher, evidence);
    *hasher.finalize().as_bytes()
}

fn hash_field(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_be_bytes());
    hasher.update(bytes);
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ProofCacheKey {
    pub language: [u8; 32],
    pub theorem: TheoremId,
    pub term_hash: TermHash,
    pub checker_abi: String,
    pub limit_profile: String,
}

impl From<&AdmissionCertificate> for ProofCacheKey {
    fn from(certificate: &AdmissionCertificate) -> Self {
        Self {
            language: certificate.term.language,
            theorem: certificate.theorem_id,
            term_hash: certificate.term.term_hash,
            checker_abi: certificate.checker_abi.clone(),
            limit_profile: certificate.limit_profile.clone(),
        }
    }
}

impl ProofCacheKey {
    pub fn for_request(
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
        checker_abi: impl Into<String>,
        limit_profile: impl Into<String>,
    ) -> Self {
        Self {
            language: term.language,
            theorem: theorem.id(),
            term_hash: term.term_hash,
            checker_abi: checker_abi.into(),
            limit_profile: limit_profile.into(),
        }
    }
}

/// A bounded, semantics-inert cache.  Saturation merely declines new entries;
/// authorization and revocation are never cached.
#[derive(Debug)]
pub struct ProofCache {
    capacity: usize,
    entries: BTreeMap<ProofCacheKey, ProvenAdmission>,
}

impl ProofCache {
    pub fn new(capacity: usize) -> Self {
        Self { capacity, entries: BTreeMap::new() }
    }

    pub fn contains(&self, key: &ProofCacheKey) -> bool {
        self.entries.contains_key(key)
    }

    pub fn contains_certificate(&self, certificate: &AdmissionCertificate) -> bool {
        self.entries
            .get(&ProofCacheKey::from(certificate))
            .is_some_and(|stored| stored.certificate() == certificate)
    }

    pub fn get(&self, key: &ProofCacheKey) -> Option<&ProvenAdmission> {
        self.entries.get(key)
    }

    pub fn insert(&mut self, proof: ProvenAdmission) -> bool {
        let key = ProofCacheKey::from(proof.certificate());
        if let Some(stored) = self.entries.get(&key) {
            return stored == &proof;
        }
        if self.entries.len() >= self.capacity {
            return false;
        }
        self.entries.insert(key, proof);
        true
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SpaceRight {
    Produce,
    Consume,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SpaceRights(BTreeSet<SpaceRight>);

impl SpaceRights {
    pub fn none() -> Self {
        Self::default()
    }

    pub fn all() -> Self {
        Self::from_rights([SpaceRight::Produce, SpaceRight::Consume])
    }

    pub fn from_rights(rights: impl IntoIterator<Item = SpaceRight>) -> Self {
        Self(rights.into_iter().collect())
    }

    pub fn contains(&self, right: SpaceRight) -> bool {
        self.0.contains(&right)
    }

    pub fn attenuate(&self, requested: &Self) -> Self {
        Self(self.0.intersection(&requested.0).copied().collect())
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TheoremChannelDescriptor {
    language: [u8; 32],
    category: CategoryId,
    channel_theorem: AdmissionTheorem,
    space_theorem: AdmissionTheorem,
    id: [u8; 32],
}

impl TheoremChannelDescriptor {
    pub fn new(
        language: [u8; 32],
        category: CategoryId,
        channel_theorem: AdmissionTheorem,
        space_theorem: AdmissionTheorem,
    ) -> Result<Self, TheoremChannelError> {
        if channel_theorem
            .category()
            .is_some_and(|found| found != category)
            || space_theorem
                .category()
                .is_some_and(|found| found != category)
        {
            return Err(TheoremChannelError::CategoryMismatch);
        }
        if !channel_theorem.refines(space_theorem) {
            return Err(TheoremChannelError::InvalidRefinement);
        }
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-theorem-channel/1\0");
        hasher.update(&language);
        hasher.update(&category.0.to_be_bytes());
        hasher.update(&channel_theorem.id().0);
        hasher.update(&space_theorem.id().0);
        let id = *hasher.finalize().as_bytes();
        Ok(Self {
            language,
            category,
            channel_theorem,
            space_theorem,
            id,
        })
    }

    pub const fn language(&self) -> [u8; 32] {
        self.language
    }

    pub const fn category(&self) -> CategoryId {
        self.category
    }

    pub const fn channel_theorem(&self) -> AdmissionTheorem {
        self.channel_theorem
    }

    pub const fn space_theorem(&self) -> AdmissionTheorem {
        self.space_theorem
    }

    pub const fn id(&self) -> [u8; 32] {
        self.id
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TypedPatternDescriptor {
    language: [u8; 32],
    category: CategoryId,
    compiled_pattern: [u8; 32],
    exact_hash: Option<TermHash>,
    capture_categories: Vec<CategoryId>,
    id: [u8; 32],
}

impl TypedPatternDescriptor {
    pub fn new(
        language: [u8; 32],
        category: CategoryId,
        compiled_pattern: [u8; 32],
        exact_hash: Option<TermHash>,
        capture_categories: Vec<CategoryId>,
        max_captures: usize,
    ) -> Result<Self, TheoremChannelError> {
        if capture_categories.len() > max_captures {
            return Err(TheoremChannelError::CaptureLimitExceeded);
        }
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-typed-pattern/1\0");
        hasher.update(&language);
        hasher.update(&category.0.to_be_bytes());
        hasher.update(&compiled_pattern);
        match exact_hash {
            Some(hash) => {
                hasher.update(&[1]);
                hasher.update(&hash.0);
            },
            None => {
                hasher.update(&[0]);
            },
        }
        hasher.update(&(capture_categories.len() as u64).to_be_bytes());
        for capture in &capture_categories {
            hasher.update(&capture.0.to_be_bytes());
        }
        let id = *hasher.finalize().as_bytes();
        Ok(Self {
            language,
            category,
            compiled_pattern,
            exact_hash,
            capture_categories,
            id,
        })
    }

    pub const fn language(&self) -> [u8; 32] {
        self.language
    }

    pub const fn category(&self) -> CategoryId {
        self.category
    }

    pub const fn compiled_pattern(&self) -> [u8; 32] {
        self.compiled_pattern
    }

    pub const fn exact_hash(&self) -> Option<TermHash> {
        self.exact_hash
    }

    pub fn capture_categories(&self) -> &[CategoryId] {
        &self.capture_categories
    }

    pub const fn id(&self) -> [u8; 32] {
        self.id
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmittedMessage {
    term: CanonicalFltTerm,
    proof: ProvenAdmission,
}

impl AdmittedMessage {
    pub const fn term(&self) -> CanonicalFltTerm {
        self.term
    }

    pub fn certificate(&self) -> &AdmissionCertificate {
        self.proof.certificate()
    }

    pub fn proof(&self) -> &ProvenAdmission {
        &self.proof
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CheckedMatchEvidence {
    pattern_id: [u8; 32],
    message: AdmittedMessage,
    captures: Vec<ProvenAdmission>,
}

impl CheckedMatchEvidence {
    pub const fn pattern_id(&self) -> [u8; 32] {
        self.pattern_id
    }

    pub fn message(&self) -> &AdmittedMessage {
        &self.message
    }

    pub fn captures(&self) -> &[ProvenAdmission] {
        &self.captures
    }
}

pub struct PreparedProduce {
    channel_id: [u8; 32],
    epoch: u64,
    handle: InstalledLanguageHandle,
    message: AdmittedMessage,
}

pub struct PreparedConsume {
    channel_id: [u8; 32],
    epoch: u64,
    handle: InstalledLanguageHandle,
    evidence: CheckedMatchEvidence,
}

#[derive(Clone, Debug)]
struct ChannelAuthorityState {
    epoch: u64,
    rights: SpaceRights,
}

/// Capability-separated transaction kernel for one theorem-indexed channel.
/// Successful commit callbacks run while both the installed-language epoch and
/// the channel-authority epoch are read-locked.  A failed check never invokes
/// the callback, which is the adapter's atomic-mutation boundary.
pub struct TheoremChannelKernel {
    descriptor: TheoremChannelDescriptor,
    checker: Arc<dyn AdmissionChecker>,
    admission_budget: AdmissionBudget,
    authority: RwLock<ChannelAuthorityState>,
    proof_cache: RwLock<ProofCache>,
}

impl TheoremChannelKernel {
    pub fn new(
        descriptor: TheoremChannelDescriptor,
        rights: SpaceRights,
        checker: Arc<dyn AdmissionChecker>,
        admission_budget: AdmissionBudget,
        proof_cache_capacity: usize,
    ) -> Self {
        Self {
            descriptor,
            checker,
            admission_budget,
            authority: RwLock::new(ChannelAuthorityState { epoch: 0, rights }),
            proof_cache: RwLock::new(ProofCache::new(proof_cache_capacity)),
        }
    }

    pub fn descriptor(&self) -> &TheoremChannelDescriptor {
        &self.descriptor
    }

    pub fn prepare_produce(
        &self,
        table: &InstalledLanguageTable,
        handle: &InstalledLanguageHandle,
        term_hash: TermHash,
    ) -> Result<PreparedProduce, TheoremChannelError> {
        self.prepare_produce_with_certificate(table, handle, term_hash, None)
    }

    pub fn prepare_produce_with_certificate(
        &self,
        table: &InstalledLanguageTable,
        handle: &InstalledLanguageHandle,
        term_hash: TermHash,
        presented_certificate: Option<&AdmissionCertificate>,
    ) -> Result<PreparedProduce, TheoremChannelError> {
        table
            .authorize_all(handle, &[LanguageRight::Publish, LanguageRight::Check])
            .map_err(TheoremChannelError::LanguageAccess)?;
        if handle.fingerprint() != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        let term = CanonicalFltTerm::structurally_admitted(
            self.descriptor.language,
            self.descriptor.category,
            term_hash,
        );
        let authority = self
            .authority
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        if !authority.rights.contains(SpaceRight::Produce) {
            return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Produce));
        }
        let epoch = authority.epoch;
        drop(authority);
        let proof =
            self.check_admission(term, self.descriptor.channel_theorem, presented_certificate)?;
        Ok(PreparedProduce {
            channel_id: self.descriptor.id,
            epoch,
            handle: handle.clone(),
            message: AdmittedMessage { term, proof },
        })
    }

    pub fn commit_produce<R>(
        &self,
        table: &InstalledLanguageTable,
        prepared: PreparedProduce,
        commit: impl FnOnce(AdmittedMessage) -> R,
    ) -> Result<R, TheoremChannelError> {
        if prepared.channel_id != self.descriptor.id {
            return Err(TheoremChannelError::WrongChannel);
        }
        self.verify_cached(prepared.message.proof())?;
        table
            .with_authorized_all(
                &prepared.handle,
                &[LanguageRight::Publish, LanguageRight::Check],
                |_| {
                    let authority = self
                        .authority
                        .read()
                        .map_err(|_| TheoremChannelError::Poisoned)?;
                    if authority.epoch != prepared.epoch {
                        return Err(TheoremChannelError::StaleEpoch);
                    }
                    if !authority.rights.contains(SpaceRight::Produce) {
                        return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Produce));
                    }
                    Ok(commit(prepared.message))
                },
            )
            .map_err(TheoremChannelError::LanguageAccess)?
    }

    pub fn prepare_consume(
        &self,
        table: &InstalledLanguageTable,
        handle: &InstalledLanguageHandle,
        message: &AdmittedMessage,
        pattern: &TypedPatternDescriptor,
        capture_hashes: &[TermHash],
    ) -> Result<PreparedConsume, TheoremChannelError> {
        table
            .authorize_all(handle, &[LanguageRight::Match, LanguageRight::Check])
            .map_err(TheoremChannelError::LanguageAccess)?;
        if handle.fingerprint() != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        let authority = self
            .authority
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        if !authority.rights.contains(SpaceRight::Consume) {
            return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Consume));
        }
        let epoch = authority.epoch;
        drop(authority);
        let channel_message = self.reclassify_channel_message(message)?;
        if message.term.language != pattern.language
            || message.term.category != pattern.category
            || pattern.language != self.descriptor.language
            || pattern.category != self.descriptor.category
            || pattern
                .exact_hash
                .is_some_and(|hash| hash != message.term.term_hash)
        {
            return Err(TheoremChannelError::PatternMismatch);
        }
        if capture_hashes.len() != pattern.capture_categories.len() {
            return Err(TheoremChannelError::CaptureTelescopeMismatch);
        }
        let mut capture_proofs = Vec::with_capacity(capture_hashes.len());
        for (term_hash, category) in capture_hashes.iter().zip(&pattern.capture_categories) {
            let capture = CanonicalFltTerm::structurally_admitted(
                self.descriptor.language,
                *category,
                *term_hash,
            );
            capture_proofs.push(self.check_admission(
                capture,
                AdmissionTheorem::Membership(*category),
                None,
            )?);
        }
        Ok(PreparedConsume {
            channel_id: self.descriptor.id,
            epoch,
            handle: handle.clone(),
            evidence: CheckedMatchEvidence {
                pattern_id: pattern.id,
                message: channel_message,
                captures: capture_proofs,
            },
        })
    }

    pub fn commit_consume<R>(
        &self,
        table: &InstalledLanguageTable,
        prepared: PreparedConsume,
        commit: impl FnOnce(CheckedMatchEvidence) -> R,
    ) -> Result<R, TheoremChannelError> {
        if prepared.channel_id != self.descriptor.id {
            return Err(TheoremChannelError::WrongChannel);
        }
        self.verify_cached(prepared.evidence.message.proof())?;
        for proof in &prepared.evidence.captures {
            self.verify_cached(proof)?;
        }
        table
            .with_authorized_all(
                &prepared.handle,
                &[LanguageRight::Match, LanguageRight::Check],
                |_| {
                    let authority = self
                        .authority
                        .read()
                        .map_err(|_| TheoremChannelError::Poisoned)?;
                    if authority.epoch != prepared.epoch {
                        return Err(TheoremChannelError::StaleEpoch);
                    }
                    if !authority.rights.contains(SpaceRight::Consume) {
                        return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Consume));
                    }
                    Ok(commit(prepared.evidence))
                },
            )
            .map_err(TheoremChannelError::LanguageAccess)?
    }

    /// Rights can only decrease.  Epoch advancement invalidates every prepared
    /// transaction, including one whose proof certificate is cached.
    pub fn attenuate_space_rights(
        &self,
        requested: &SpaceRights,
    ) -> Result<u64, TheoremChannelError> {
        let mut authority = self
            .authority
            .write()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        authority.rights = authority.rights.attenuate(requested);
        authority.epoch = authority
            .epoch
            .checked_add(1)
            .ok_or(TheoremChannelError::EpochExhausted)?;
        Ok(authority.epoch)
    }

    pub fn revoke(&self) -> Result<u64, TheoremChannelError> {
        self.attenuate_space_rights(&SpaceRights::none())
    }

    fn check_term_identity(&self, term: CanonicalFltTerm) -> Result<(), TheoremChannelError> {
        if term.language != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        if term.category != self.descriptor.category {
            return Err(TheoremChannelError::CategoryMismatch);
        }
        Ok(())
    }

    /// Transport an already admitted term into this channel's theorem fibre.
    /// The original certificate establishes the canonical term identity; the
    /// local total checker then proves the channel predicate instead of
    /// trusting certificate provenance or requiring nominal theorem equality.
    fn reclassify_channel_message(
        &self,
        message: &AdmittedMessage,
    ) -> Result<AdmittedMessage, TheoremChannelError> {
        self.check_term_identity(message.term)?;
        self.verify_cached(message.proof())?;
        let proof = self.check_admission(message.term, self.descriptor.channel_theorem, None)?;
        Ok(AdmittedMessage { term: message.term, proof })
    }

    fn check_admission(
        &self,
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
        presented_certificate: Option<&AdmissionCertificate>,
    ) -> Result<ProvenAdmission, TheoremChannelError> {
        let key = ProofCacheKey::for_request(
            term,
            theorem,
            self.checker.checker_abi(),
            self.checker.limit_profile(),
        );
        let cached = self
            .proof_cache
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?
            .get(&key)
            .cloned();
        if let Some(proof) = cached {
            let exact_presented_certificate =
                presented_certificate.is_none_or(|certificate| certificate == proof.certificate());
            if exact_presented_certificate {
                self.validate_proven(term, theorem, &proof)?;
                return Ok(proof);
            }
        }
        let decision = self.checker.check(AdmissionRequest {
            term,
            theorem,
            presented_certificate,
            budget: self.admission_budget,
        });
        let proof = match decision {
            AdmissionDecision::Proven(proof) => proof,
            AdmissionDecision::Refuted { reason, usage } => {
                return Err(TheoremChannelError::AdmissionRefuted { reason, usage });
            },
            AdmissionDecision::Undetermined { reason, usage } => {
                return Err(TheoremChannelError::AdmissionUndetermined { reason, usage });
            },
        };
        self.validate_proven(term, theorem, &proof)?;
        self.proof_cache
            .write()
            .map_err(|_| TheoremChannelError::Poisoned)?
            .insert(proof.clone());
        Ok(proof)
    }

    fn validate_proven(
        &self,
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
        proof: &ProvenAdmission,
    ) -> Result<(), TheoremChannelError> {
        let certificate = proof.certificate();
        let evidence_bytes = u64::try_from(certificate.evidence.len()).unwrap_or(u64::MAX);
        if !certificate.has_valid_envelope_for(
            term,
            theorem,
            self.checker.checker_abi(),
            self.checker.limit_profile(),
        ) || proof.usage.evidence_bytes != evidence_bytes
            || proof.usage.logical_work_units > self.admission_budget.max_work_units
            || evidence_bytes > self.admission_budget.max_evidence_bytes
        {
            return Err(TheoremChannelError::Certificate(CertificateError::CertificateMismatch));
        }
        Ok(())
    }

    fn verify_cached(&self, proof: &ProvenAdmission) -> Result<(), TheoremChannelError> {
        let certificate = proof.certificate();
        self.validate_proven(certificate.term, certificate.theorem, proof)?;
        if self
            .proof_cache
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?
            .contains_certificate(certificate)
        {
            return Ok(());
        }
        let verified =
            self.check_admission(certificate.term, certificate.theorem, Some(certificate))?;
        if &verified != proof {
            return Err(TheoremChannelError::Certificate(CertificateError::CertificateMismatch));
        }
        Ok(())
    }
}

#[derive(Debug)]
pub enum TheoremChannelError {
    InvalidRefinement,
    LanguageMismatch,
    CategoryMismatch,
    WrongChannel,
    PatternMismatch,
    CaptureTelescopeMismatch,
    CaptureLimitExceeded,
    AdmissionRefuted {
        reason: AdmissionRefutation,
        usage: AdmissionUsage,
    },
    AdmissionUndetermined {
        reason: AdmissionUndetermined,
        usage: AdmissionUsage,
    },
    MissingSpaceRight(SpaceRight),
    StaleEpoch,
    EpochExhausted,
    Poisoned,
    Certificate(CertificateError),
    LanguageAccess(LanguageAccessError),
}

impl fmt::Display for TheoremChannelError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidRefinement => {
                formatter.write_str("the channel theorem does not refine the space theorem")
            },
            Self::LanguageMismatch => formatter.write_str("FLT language does not match channel"),
            Self::CategoryMismatch => formatter.write_str("FLT category does not match channel"),
            Self::WrongChannel => {
                formatter.write_str("prepared transaction belongs to another channel")
            },
            Self::PatternMismatch => {
                formatter.write_str("typed FLT pattern does not match message")
            },
            Self::CaptureTelescopeMismatch => {
                formatter.write_str("capture evidence does not match the typed telescope")
            },
            Self::CaptureLimitExceeded => {
                formatter.write_str("capture telescope exceeds its limit")
            },
            Self::AdmissionRefuted { reason, usage } => write!(
                formatter,
                "admission was refuted ({reason:?}) after {} logical work units",
                usage.logical_work_units,
            ),
            Self::AdmissionUndetermined { reason, usage } => write!(
                formatter,
                "admission is undetermined ({reason:?}) after {} logical work units",
                usage.logical_work_units,
            ),
            Self::MissingSpaceRight(right) => write!(formatter, "missing space right {right:?}"),
            Self::StaleEpoch => {
                formatter.write_str("prepared transaction has a stale authority epoch")
            },
            Self::EpochExhausted => formatter.write_str("channel authority epoch exhausted"),
            Self::Poisoned => formatter.write_str("theorem-channel state lock is poisoned"),
            Self::Certificate(error) => write!(formatter, "certificate error: {error}"),
            Self::LanguageAccess(error) => write!(formatter, "language access error: {error:?}"),
        }
    }
}

impl std::error::Error for TheoremChannelError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn hash(byte: u8) -> TermHash {
        TermHash([byte; 32])
    }

    #[test]
    fn normalized_meet_is_commutative_idempotent_and_refines_membership() {
        let category = CategoryId(7);
        let membership = AdmissionTheorem::membership(category);
        let exact = AdmissionTheorem::exact(category, hash(3));
        assert_eq!(membership.meet(exact), exact);
        assert_eq!(exact.meet(membership), exact);
        assert_eq!(exact.meet(exact), exact);
        assert!(exact.refines(membership));
        assert!(!membership.refines(exact));
        assert_eq!(
            membership.meet(AdmissionTheorem::membership(CategoryId(8))),
            AdmissionTheorem::Bottom
        );
    }

    #[test]
    fn structural_admission_is_bounded_and_three_valued() {
        let checker = StructuralTheoremChecker::default();
        let term = CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(4));
        let membership = AdmissionTheorem::membership(CategoryId(2));

        let exhausted = AdmissionChecker::check(
            &checker,
            AdmissionRequest {
                term,
                theorem: membership,
                presented_certificate: None,
                budget: AdmissionBudget::new(0, 0),
            },
        );
        assert!(matches!(
            exhausted,
            AdmissionDecision::Undetermined {
                reason: AdmissionUndetermined::WorkBudgetExhausted {
                    required: STRUCTURAL_ADMISSION_WORK_UNITS,
                    available: 0,
                },
                usage: AdmissionUsage {
                    logical_work_units: STRUCTURAL_ADMISSION_WORK_UNITS,
                    evidence_bytes: 0,
                },
            }
        ));

        let refuted = AdmissionChecker::check(
            &checker,
            AdmissionRequest {
                term,
                theorem: AdmissionTheorem::membership(CategoryId(3)),
                presented_certificate: None,
                budget: AdmissionBudget::structural(),
            },
        );
        assert!(matches!(
            refuted,
            AdmissionDecision::Refuted {
                reason: AdmissionRefutation::TheoremDoesNotHold,
                ..
            }
        ));

        let AdmissionDecision::Proven(proof) = AdmissionChecker::check(
            &checker,
            AdmissionRequest {
                term,
                theorem: membership,
                presented_certificate: None,
                budget: AdmissionBudget::structural(),
            },
        ) else {
            panic!("valid structural membership must be proven")
        };
        assert_eq!(proof.usage(), AdmissionUsage::new(STRUCTURAL_ADMISSION_WORK_UNITS, 0));
        checker
            .verify(proof.certificate())
            .expect("minted proof envelope");
    }

    #[test]
    fn presented_certificate_limits_and_complete_envelope_are_checked() {
        let checker = StructuralTheoremChecker::default();
        let term = CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(4));
        let theorem = AdmissionTheorem::membership(CategoryId(2));
        let evidence_bearing = AdmissionCertificate::from_checked_evidence(
            term,
            theorem,
            checker.checker_abi(),
            checker.limit_profile(),
            vec![7],
        );
        assert!(matches!(
            AdmissionChecker::check(
                &checker,
                AdmissionRequest {
                    term,
                    theorem,
                    presented_certificate: Some(&evidence_bearing),
                    budget: AdmissionBudget::structural(),
                },
            ),
            AdmissionDecision::Undetermined {
                reason: AdmissionUndetermined::EvidenceBudgetExhausted {
                    required: 1,
                    available: 0,
                },
                ..
            }
        ));

        let other = checker
            .check(
                CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(5)),
                theorem,
            )
            .expect("other canonical certificate");
        assert!(matches!(
            AdmissionChecker::check(
                &checker,
                AdmissionRequest {
                    term,
                    theorem,
                    presented_certificate: Some(&other),
                    budget: AdmissionBudget::structural(),
                },
            ),
            AdmissionDecision::Refuted {
                reason: AdmissionRefutation::CertificateMismatch,
                ..
            }
        ));
    }

    #[test]
    fn certificate_and_cache_bind_every_consensus_identity_field() {
        let checker = StructuralTheoremChecker::default();
        let term = CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(4));
        let certificate = checker
            .check(term, AdmissionTheorem::membership(CategoryId(2)))
            .expect("membership certificate");
        checker.verify(&certificate).expect("certificate verifies");
        let key = ProofCacheKey::from(&certificate);
        assert_eq!(key.language, [1; 32]);
        assert_eq!(key.term_hash, hash(4));
        assert_eq!(key.checker_abi, STRUCTURAL_THEOREM_CHECKER_ABI_V1);
        assert_eq!(key.limit_profile, STRUCTURAL_THEOREM_LIMIT_PROFILE_V1);

        let mut cache = ProofCache::new(1);
        let proof = ProvenAdmission::from_checked_certificate(
            certificate.clone(),
            AdmissionUsage::new(STRUCTURAL_ADMISSION_WORK_UNITS, 0),
        );
        assert!(cache.insert(proof));
        assert!(cache.contains(&key));
        let same_key_different_evidence = AdmissionCertificate::from_checked_evidence(
            term,
            AdmissionTheorem::membership(CategoryId(2)),
            checker.checker_abi(),
            checker.limit_profile(),
            vec![1],
        );
        assert!(!cache.contains_certificate(&same_key_different_evidence));
        let other = checker
            .check(
                CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(5)),
                AdmissionTheorem::membership(CategoryId(2)),
            )
            .expect("second certificate");
        assert!(!cache.insert(ProvenAdmission::from_checked_certificate(
            other,
            AdmissionUsage::new(STRUCTURAL_ADMISSION_WORK_UNITS, 0),
        )));
        assert_eq!(cache.len(), 1);
    }

    #[test]
    fn channel_refinement_rejects_cross_category_and_weaker_claims() {
        let member = AdmissionTheorem::membership(CategoryId(1));
        let exact = AdmissionTheorem::exact(CategoryId(1), hash(9));
        assert!(TheoremChannelDescriptor::new([3; 32], CategoryId(1), exact, member).is_ok());
        assert!(matches!(
            TheoremChannelDescriptor::new([3; 32], CategoryId(1), member, exact),
            Err(TheoremChannelError::InvalidRefinement)
        ));
        assert!(matches!(
            TheoremChannelDescriptor::new(
                [3; 32],
                CategoryId(1),
                AdmissionTheorem::membership(CategoryId(2)),
                member,
            ),
            Err(TheoremChannelError::CategoryMismatch)
        ));
    }
}
