//! Source-neutral theorem certificates and typed-channel transaction protocol.
//!
//! Grammar recognition proves that a reflected value belongs to a syntactic
//! category.  Stateful admission is a separate judgment: a channel is indexed
//! by an installed language and a theorem, and mutation is permitted only after
//! a certificate has been checked and both language and space authority have
//! been revalidated at the commit boundary.  This module owns that small,
//! runtime-neutral kernel; it deliberately owns no tuple-space persistence.

use crate::{
    CategoryId, InstalledLanguageHandle, InstalledLanguageTable, LanguageAccessError, LanguageRight,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fmt;
use std::sync::RwLock;

pub const STRUCTURAL_THEOREM_CHECKER_ABI_V1: &str = "mettail-structural-theorem-checker/1";
pub const STRUCTURAL_THEOREM_LIMIT_PROFILE_V1: &str = "mettail-structural-theorem-limits/1";

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TheoremId(pub [u8; 32]);

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct TermHash(pub [u8; 32]);

/// Canonical quotient of conjunctions generated by category membership and
/// exact-term predicates.
///
/// `meet` is associative, commutative, and idempotent.  Contradictory
/// conjunctions normalize to `Bottom`, so neither equality nor refinement ever
/// traverses a user-sized theorem tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum AdmissionTheorem {
    Bottom,
    Membership(CategoryId),
    ExactTerm {
        category: CategoryId,
        term_hash: TermHash,
    },
}

impl AdmissionTheorem {
    pub const fn membership(category: CategoryId) -> Self {
        Self::Membership(category)
    }

    pub const fn exact(category: CategoryId, term_hash: TermHash) -> Self {
        Self::ExactTerm { category, term_hash }
    }

    pub fn id(self) -> TheoremId {
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-admission-theorem/1\0");
        match self {
            Self::Bottom => {
                hasher.update(&[0]);
            },
            Self::Membership(category) => {
                hasher.update(&[1]);
                hasher.update(&category.0.to_be_bytes());
            },
            Self::ExactTerm { category, term_hash } => {
                hasher.update(&[2]);
                hasher.update(&category.0.to_be_bytes());
                hasher.update(&term_hash.0);
            },
        }
        TheoremId(*hasher.finalize().as_bytes())
    }

    pub const fn category(self) -> Option<CategoryId> {
        match self {
            Self::Bottom => None,
            Self::Membership(category) | Self::ExactTerm { category, .. } => Some(category),
        }
    }

    pub fn meet(self, other: Self) -> Self {
        match (self, other) {
            (Self::Bottom, _) | (_, Self::Bottom) => Self::Bottom,
            (Self::Membership(left), Self::Membership(right)) => {
                if left.0 == right.0 {
                    Self::Membership(left)
                } else {
                    Self::Bottom
                }
            },
            (
                Self::ExactTerm { category: exact_category, term_hash },
                Self::Membership(member_category),
            )
            | (
                Self::Membership(member_category),
                Self::ExactTerm { category: exact_category, term_hash },
            ) => {
                if exact_category.0 == member_category.0 {
                    Self::ExactTerm { category: exact_category, term_hash }
                } else {
                    Self::Bottom
                }
            },
            (
                Self::ExactTerm {
                    category: left_category,
                    term_hash: left_hash,
                },
                Self::ExactTerm {
                    category: right_category,
                    term_hash: right_hash,
                },
            ) => {
                if left_category.0 == right_category.0 && left_hash.0 == right_hash.0 {
                    Self::ExactTerm {
                        category: left_category,
                        term_hash: left_hash,
                    }
                } else {
                    Self::Bottom
                }
            },
        }
    }

    /// `self` refines `target` when every term satisfying `self` also satisfies
    /// `target`.  Bottom is the initial object of this implication preorder.
    pub fn refines(self, target: Self) -> bool {
        match (self, target) {
            (Self::Bottom, _) => true,
            (_, Self::Bottom) => false,
            (Self::Membership(left), Self::Membership(right)) => left.0 == right.0,
            (
                Self::ExactTerm {
                    category: left_category,
                    term_hash: left_hash,
                },
                Self::ExactTerm {
                    category: right_category,
                    term_hash: right_hash,
                },
            ) => left_category.0 == right_category.0 && left_hash.0 == right_hash.0,
            (
                Self::ExactTerm { category: exact_category, .. },
                Self::Membership(member_category),
            ) => exact_category.0 == member_category.0,
            (Self::Membership(_), Self::ExactTerm { .. }) => false,
        }
    }

    pub fn holds(self, term: CanonicalFltTerm) -> bool {
        match self {
            Self::Bottom => false,
            Self::Membership(category) => category.0 == term.category.0,
            Self::ExactTerm { category, term_hash } => {
                category.0 == term.category.0 && term_hash.0 == term.term_hash.0
            },
        }
    }
}

/// The source-neutral identity of an FLT after an authorized adapter has
/// checked its concrete representation against the installed grammar.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct CanonicalFltTerm {
    language: [u8; 32],
    category: CategoryId,
    term_hash: TermHash,
}

impl CanonicalFltTerm {
    const fn structurally_admitted(
        language: [u8; 32],
        category: CategoryId,
        term_hash: TermHash,
    ) -> Self {
        Self { language, category, term_hash }
    }

    pub const fn language(self) -> [u8; 32] {
        self.language
    }

    pub const fn category(self) -> CategoryId {
        self.category
    }

    pub const fn term_hash(self) -> TermHash {
        self.term_hash
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmissionCertificate {
    term: CanonicalFltTerm,
    theorem: AdmissionTheorem,
    theorem_id: TheoremId,
    checker_abi: String,
    limit_profile: String,
    evidence_hash: [u8; 32],
}

impl AdmissionCertificate {
    pub const fn term(&self) -> CanonicalFltTerm {
        self.term
    }

    pub const fn theorem(&self) -> AdmissionTheorem {
        self.theorem
    }

    pub const fn theorem_id(&self) -> TheoremId {
        self.theorem_id
    }

    pub fn checker_abi(&self) -> &str {
        &self.checker_abi
    }

    pub fn limit_profile(&self) -> &str {
        &self.limit_profile
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CertificateError {
    TheoremDoesNotHold,
    CertificateMismatch,
}

impl fmt::Display for CertificateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::TheoremDoesNotHold => "the admission theorem does not hold for the FLT",
            Self::CertificateMismatch => "the admission certificate is not canonical",
        })
    }
}

impl std::error::Error for CertificateError {}

/// Total checker for the structural theorem fragment.  Stronger theorem
/// engines implement the same source-neutral certificate contract at a
/// separately authorized boundary; proof search is not part of this checker.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StructuralTheoremChecker {
    checker_abi: String,
    limit_profile: String,
}

impl Default for StructuralTheoremChecker {
    fn default() -> Self {
        Self::new(STRUCTURAL_THEOREM_CHECKER_ABI_V1, STRUCTURAL_THEOREM_LIMIT_PROFILE_V1)
    }
}

impl StructuralTheoremChecker {
    pub fn new(checker_abi: impl Into<String>, limit_profile: impl Into<String>) -> Self {
        Self {
            checker_abi: checker_abi.into(),
            limit_profile: limit_profile.into(),
        }
    }

    pub fn checker_abi(&self) -> &str {
        &self.checker_abi
    }

    pub fn limit_profile(&self) -> &str {
        &self.limit_profile
    }

    pub fn check(
        &self,
        term: CanonicalFltTerm,
        theorem: AdmissionTheorem,
    ) -> Result<AdmissionCertificate, CertificateError> {
        if !theorem.holds(term) {
            return Err(CertificateError::TheoremDoesNotHold);
        }
        let theorem_id = theorem.id();
        let evidence_hash =
            certificate_evidence_hash(term, theorem_id, &self.checker_abi, &self.limit_profile);
        Ok(AdmissionCertificate {
            term,
            theorem,
            theorem_id,
            checker_abi: self.checker_abi.clone(),
            limit_profile: self.limit_profile.clone(),
            evidence_hash,
        })
    }

    pub fn verify(&self, certificate: &AdmissionCertificate) -> Result<(), CertificateError> {
        if certificate.theorem_id != certificate.theorem.id()
            || certificate.checker_abi != self.checker_abi
            || certificate.limit_profile != self.limit_profile
            || !certificate.theorem.holds(certificate.term)
            || certificate.evidence_hash
                != certificate_evidence_hash(
                    certificate.term,
                    certificate.theorem_id,
                    &certificate.checker_abi,
                    &certificate.limit_profile,
                )
        {
            return Err(CertificateError::CertificateMismatch);
        }
        Ok(())
    }
}

fn certificate_evidence_hash(
    term: CanonicalFltTerm,
    theorem_id: TheoremId,
    checker_abi: &str,
    limit_profile: &str,
) -> [u8; 32] {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"mettail-admission-certificate/1\0");
    hasher.update(&term.language);
    hasher.update(&term.category.0.to_be_bytes());
    hasher.update(&term.term_hash.0);
    hasher.update(&theorem_id.0);
    hash_field(&mut hasher, checker_abi.as_bytes());
    hash_field(&mut hasher, limit_profile.as_bytes());
    *hasher.finalize().as_bytes()
}

fn hash_field(hasher: &mut blake3::Hasher, bytes: &[u8]) {
    hasher.update(&(bytes.len() as u64).to_be_bytes());
    hasher.update(bytes);
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ProofCacheKey {
    pub language: [u8; 32],
    pub theorem: TheoremId,
    pub term_hash: TermHash,
    pub checker_abi: String,
    pub limit_profile: String,
}

impl From<&AdmissionCertificate> for ProofCacheKey {
    fn from(certificate: &AdmissionCertificate) -> Self {
        Self {
            language: certificate.term.language,
            theorem: certificate.theorem_id,
            term_hash: certificate.term.term_hash,
            checker_abi: certificate.checker_abi.clone(),
            limit_profile: certificate.limit_profile.clone(),
        }
    }
}

/// A bounded, semantics-inert cache.  Saturation merely declines new entries;
/// authorization and revocation are never cached.
#[derive(Debug)]
pub struct ProofCache {
    capacity: usize,
    entries: BTreeSet<ProofCacheKey>,
}

impl ProofCache {
    pub fn new(capacity: usize) -> Self {
        Self { capacity, entries: BTreeSet::new() }
    }

    pub fn contains(&self, key: &ProofCacheKey) -> bool {
        self.entries.contains(key)
    }

    pub fn insert(&mut self, key: ProofCacheKey) -> bool {
        if self.entries.contains(&key) {
            return true;
        }
        if self.entries.len() >= self.capacity {
            return false;
        }
        self.entries.insert(key)
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SpaceRight {
    Produce,
    Consume,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SpaceRights(BTreeSet<SpaceRight>);

impl SpaceRights {
    pub fn none() -> Self {
        Self::default()
    }

    pub fn all() -> Self {
        Self::from_rights([SpaceRight::Produce, SpaceRight::Consume])
    }

    pub fn from_rights(rights: impl IntoIterator<Item = SpaceRight>) -> Self {
        Self(rights.into_iter().collect())
    }

    pub fn contains(&self, right: SpaceRight) -> bool {
        self.0.contains(&right)
    }

    pub fn attenuate(&self, requested: &Self) -> Self {
        Self(self.0.intersection(&requested.0).copied().collect())
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TheoremChannelDescriptor {
    language: [u8; 32],
    category: CategoryId,
    channel_theorem: AdmissionTheorem,
    space_theorem: AdmissionTheorem,
    id: [u8; 32],
}

impl TheoremChannelDescriptor {
    pub fn new(
        language: [u8; 32],
        category: CategoryId,
        channel_theorem: AdmissionTheorem,
        space_theorem: AdmissionTheorem,
    ) -> Result<Self, TheoremChannelError> {
        if channel_theorem
            .category()
            .is_some_and(|found| found != category)
            || space_theorem
                .category()
                .is_some_and(|found| found != category)
        {
            return Err(TheoremChannelError::CategoryMismatch);
        }
        if !channel_theorem.refines(space_theorem) {
            return Err(TheoremChannelError::InvalidRefinement);
        }
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-theorem-channel/1\0");
        hasher.update(&language);
        hasher.update(&category.0.to_be_bytes());
        hasher.update(&channel_theorem.id().0);
        hasher.update(&space_theorem.id().0);
        let id = *hasher.finalize().as_bytes();
        Ok(Self {
            language,
            category,
            channel_theorem,
            space_theorem,
            id,
        })
    }

    pub const fn language(&self) -> [u8; 32] {
        self.language
    }

    pub const fn category(&self) -> CategoryId {
        self.category
    }

    pub const fn channel_theorem(&self) -> AdmissionTheorem {
        self.channel_theorem
    }

    pub const fn space_theorem(&self) -> AdmissionTheorem {
        self.space_theorem
    }

    pub const fn id(&self) -> [u8; 32] {
        self.id
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TypedPatternDescriptor {
    language: [u8; 32],
    category: CategoryId,
    compiled_pattern: [u8; 32],
    exact_hash: Option<TermHash>,
    capture_categories: Vec<CategoryId>,
    id: [u8; 32],
}

impl TypedPatternDescriptor {
    pub fn new(
        language: [u8; 32],
        category: CategoryId,
        compiled_pattern: [u8; 32],
        exact_hash: Option<TermHash>,
        capture_categories: Vec<CategoryId>,
        max_captures: usize,
    ) -> Result<Self, TheoremChannelError> {
        if capture_categories.len() > max_captures {
            return Err(TheoremChannelError::CaptureLimitExceeded);
        }
        let mut hasher = blake3::Hasher::new();
        hasher.update(b"mettail-typed-pattern/1\0");
        hasher.update(&language);
        hasher.update(&category.0.to_be_bytes());
        hasher.update(&compiled_pattern);
        match exact_hash {
            Some(hash) => {
                hasher.update(&[1]);
                hasher.update(&hash.0);
            },
            None => {
                hasher.update(&[0]);
            },
        }
        hasher.update(&(capture_categories.len() as u64).to_be_bytes());
        for capture in &capture_categories {
            hasher.update(&capture.0.to_be_bytes());
        }
        let id = *hasher.finalize().as_bytes();
        Ok(Self {
            language,
            category,
            compiled_pattern,
            exact_hash,
            capture_categories,
            id,
        })
    }

    pub const fn language(&self) -> [u8; 32] {
        self.language
    }

    pub const fn category(&self) -> CategoryId {
        self.category
    }

    pub const fn compiled_pattern(&self) -> [u8; 32] {
        self.compiled_pattern
    }

    pub const fn exact_hash(&self) -> Option<TermHash> {
        self.exact_hash
    }

    pub fn capture_categories(&self) -> &[CategoryId] {
        &self.capture_categories
    }

    pub const fn id(&self) -> [u8; 32] {
        self.id
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdmittedMessage {
    term: CanonicalFltTerm,
    certificate: AdmissionCertificate,
}

impl AdmittedMessage {
    pub const fn term(&self) -> CanonicalFltTerm {
        self.term
    }

    pub fn certificate(&self) -> &AdmissionCertificate {
        &self.certificate
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CheckedMatchEvidence {
    pattern_id: [u8; 32],
    message: AdmittedMessage,
    captures: Vec<AdmissionCertificate>,
}

impl CheckedMatchEvidence {
    pub const fn pattern_id(&self) -> [u8; 32] {
        self.pattern_id
    }

    pub fn message(&self) -> &AdmittedMessage {
        &self.message
    }

    pub fn captures(&self) -> &[AdmissionCertificate] {
        &self.captures
    }
}

#[derive(Clone)]
pub struct PreparedProduce {
    channel_id: [u8; 32],
    epoch: u64,
    handle: InstalledLanguageHandle,
    message: AdmittedMessage,
}

#[derive(Clone)]
pub struct PreparedConsume {
    channel_id: [u8; 32],
    epoch: u64,
    handle: InstalledLanguageHandle,
    evidence: CheckedMatchEvidence,
}

#[derive(Clone, Debug)]
struct ChannelAuthorityState {
    epoch: u64,
    rights: SpaceRights,
}

/// Capability-separated transaction kernel for one theorem-indexed channel.
/// Successful commit callbacks run while both the installed-language epoch and
/// the channel-authority epoch are read-locked.  A failed check never invokes
/// the callback, which is the adapter's atomic-mutation boundary.
pub struct TheoremChannelKernel {
    descriptor: TheoremChannelDescriptor,
    checker: StructuralTheoremChecker,
    authority: RwLock<ChannelAuthorityState>,
    proof_cache: RwLock<ProofCache>,
}

impl TheoremChannelKernel {
    pub fn new(
        descriptor: TheoremChannelDescriptor,
        rights: SpaceRights,
        checker: StructuralTheoremChecker,
        proof_cache_capacity: usize,
    ) -> Self {
        Self {
            descriptor,
            checker,
            authority: RwLock::new(ChannelAuthorityState { epoch: 0, rights }),
            proof_cache: RwLock::new(ProofCache::new(proof_cache_capacity)),
        }
    }

    pub fn descriptor(&self) -> &TheoremChannelDescriptor {
        &self.descriptor
    }

    pub fn prepare_produce(
        &self,
        table: &InstalledLanguageTable,
        handle: &InstalledLanguageHandle,
        term_hash: TermHash,
    ) -> Result<PreparedProduce, TheoremChannelError> {
        table
            .authorize(handle, LanguageRight::Publish)
            .map_err(TheoremChannelError::LanguageAccess)?;
        if handle.fingerprint() != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        let term = CanonicalFltTerm::structurally_admitted(
            self.descriptor.language,
            self.descriptor.category,
            term_hash,
        );
        let authority = self
            .authority
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        if !authority.rights.contains(SpaceRight::Produce) {
            return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Produce));
        }
        let certificate = self
            .checker
            .check(term, self.descriptor.channel_theorem)
            .map_err(TheoremChannelError::Certificate)?;
        self.cache_verified(&certificate)?;
        Ok(PreparedProduce {
            channel_id: self.descriptor.id,
            epoch: authority.epoch,
            handle: handle.clone(),
            message: AdmittedMessage { term, certificate },
        })
    }

    pub fn commit_produce<R>(
        &self,
        table: &InstalledLanguageTable,
        prepared: PreparedProduce,
        commit: impl FnOnce(AdmittedMessage) -> R,
    ) -> Result<R, TheoremChannelError> {
        if prepared.channel_id != self.descriptor.id {
            return Err(TheoremChannelError::WrongChannel);
        }
        table
            .with_authorized(&prepared.handle, LanguageRight::Publish, |_| {
                let authority = self
                    .authority
                    .read()
                    .map_err(|_| TheoremChannelError::Poisoned)?;
                if authority.epoch != prepared.epoch {
                    return Err(TheoremChannelError::StaleEpoch);
                }
                if !authority.rights.contains(SpaceRight::Produce) {
                    return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Produce));
                }
                self.verify_cached(prepared.message.certificate())?;
                Ok(commit(prepared.message))
            })
            .map_err(TheoremChannelError::LanguageAccess)?
    }

    pub fn prepare_consume(
        &self,
        table: &InstalledLanguageTable,
        handle: &InstalledLanguageHandle,
        message: &AdmittedMessage,
        pattern: &TypedPatternDescriptor,
        capture_hashes: &[TermHash],
    ) -> Result<PreparedConsume, TheoremChannelError> {
        table
            .authorize(handle, LanguageRight::Match)
            .map_err(TheoremChannelError::LanguageAccess)?;
        if handle.fingerprint() != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        let channel_message = self.reclassify_channel_message(message)?;
        if message.term.language != pattern.language
            || message.term.category != pattern.category
            || pattern.language != self.descriptor.language
            || pattern.category != self.descriptor.category
            || pattern
                .exact_hash
                .is_some_and(|hash| hash != message.term.term_hash)
        {
            return Err(TheoremChannelError::PatternMismatch);
        }
        if capture_hashes.len() != pattern.capture_categories.len() {
            return Err(TheoremChannelError::CaptureTelescopeMismatch);
        }
        let mut capture_certificates = Vec::with_capacity(capture_hashes.len());
        for (term_hash, category) in capture_hashes.iter().zip(&pattern.capture_categories) {
            let capture = CanonicalFltTerm::structurally_admitted(
                self.descriptor.language,
                *category,
                *term_hash,
            );
            let certificate = self
                .checker
                .check(capture, AdmissionTheorem::Membership(*category))
                .map_err(TheoremChannelError::Certificate)?;
            self.cache_verified(&certificate)?;
            capture_certificates.push(certificate);
        }
        let authority = self
            .authority
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        if !authority.rights.contains(SpaceRight::Consume) {
            return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Consume));
        }
        Ok(PreparedConsume {
            channel_id: self.descriptor.id,
            epoch: authority.epoch,
            handle: handle.clone(),
            evidence: CheckedMatchEvidence {
                pattern_id: pattern.id,
                message: channel_message,
                captures: capture_certificates,
            },
        })
    }

    pub fn commit_consume<R>(
        &self,
        table: &InstalledLanguageTable,
        prepared: PreparedConsume,
        commit: impl FnOnce(CheckedMatchEvidence) -> R,
    ) -> Result<R, TheoremChannelError> {
        if prepared.channel_id != self.descriptor.id {
            return Err(TheoremChannelError::WrongChannel);
        }
        table
            .with_authorized(&prepared.handle, LanguageRight::Match, |_| {
                let authority = self
                    .authority
                    .read()
                    .map_err(|_| TheoremChannelError::Poisoned)?;
                if authority.epoch != prepared.epoch {
                    return Err(TheoremChannelError::StaleEpoch);
                }
                if !authority.rights.contains(SpaceRight::Consume) {
                    return Err(TheoremChannelError::MissingSpaceRight(SpaceRight::Consume));
                }
                self.verify_cached(prepared.evidence.message.certificate())?;
                for certificate in &prepared.evidence.captures {
                    self.verify_cached(certificate)?;
                }
                Ok(commit(prepared.evidence))
            })
            .map_err(TheoremChannelError::LanguageAccess)?
    }

    /// Rights can only decrease.  Epoch advancement invalidates every prepared
    /// transaction, including one whose proof certificate is cached.
    pub fn attenuate_space_rights(
        &self,
        requested: &SpaceRights,
    ) -> Result<u64, TheoremChannelError> {
        let mut authority = self
            .authority
            .write()
            .map_err(|_| TheoremChannelError::Poisoned)?;
        authority.rights = authority.rights.attenuate(requested);
        authority.epoch = authority
            .epoch
            .checked_add(1)
            .ok_or(TheoremChannelError::EpochExhausted)?;
        Ok(authority.epoch)
    }

    pub fn revoke(&self) -> Result<u64, TheoremChannelError> {
        self.attenuate_space_rights(&SpaceRights::none())
    }

    fn check_term_identity(&self, term: CanonicalFltTerm) -> Result<(), TheoremChannelError> {
        if term.language != self.descriptor.language {
            return Err(TheoremChannelError::LanguageMismatch);
        }
        if term.category != self.descriptor.category {
            return Err(TheoremChannelError::CategoryMismatch);
        }
        Ok(())
    }

    /// Transport an already admitted term into this channel's theorem fibre.
    /// The original certificate establishes the canonical term identity; the
    /// local total checker then proves the channel predicate instead of
    /// trusting certificate provenance or requiring nominal theorem equality.
    fn reclassify_channel_message(
        &self,
        message: &AdmittedMessage,
    ) -> Result<AdmittedMessage, TheoremChannelError> {
        self.check_term_identity(message.term)?;
        self.verify_cached(message.certificate())?;
        let certificate = self
            .checker
            .check(message.term, self.descriptor.channel_theorem)
            .map_err(TheoremChannelError::Certificate)?;
        self.cache_verified(&certificate)?;
        Ok(AdmittedMessage { term: message.term, certificate })
    }

    fn cache_verified(
        &self,
        certificate: &AdmissionCertificate,
    ) -> Result<(), TheoremChannelError> {
        self.checker
            .verify(certificate)
            .map_err(TheoremChannelError::Certificate)?;
        self.proof_cache
            .write()
            .map_err(|_| TheoremChannelError::Poisoned)?
            .insert(ProofCacheKey::from(certificate));
        Ok(())
    }

    fn verify_cached(&self, certificate: &AdmissionCertificate) -> Result<(), TheoremChannelError> {
        let key = ProofCacheKey::from(certificate);
        if self
            .proof_cache
            .read()
            .map_err(|_| TheoremChannelError::Poisoned)?
            .contains(&key)
        {
            return Ok(());
        }
        self.cache_verified(certificate)
    }
}

#[derive(Debug)]
pub enum TheoremChannelError {
    InvalidRefinement,
    LanguageMismatch,
    CategoryMismatch,
    WrongChannel,
    PatternMismatch,
    CaptureTelescopeMismatch,
    CaptureLimitExceeded,
    MissingSpaceRight(SpaceRight),
    StaleEpoch,
    EpochExhausted,
    Poisoned,
    Certificate(CertificateError),
    LanguageAccess(LanguageAccessError),
}

impl fmt::Display for TheoremChannelError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidRefinement => {
                formatter.write_str("the channel theorem does not refine the space theorem")
            },
            Self::LanguageMismatch => formatter.write_str("FLT language does not match channel"),
            Self::CategoryMismatch => formatter.write_str("FLT category does not match channel"),
            Self::WrongChannel => {
                formatter.write_str("prepared transaction belongs to another channel")
            },
            Self::PatternMismatch => {
                formatter.write_str("typed FLT pattern does not match message")
            },
            Self::CaptureTelescopeMismatch => {
                formatter.write_str("capture evidence does not match the typed telescope")
            },
            Self::CaptureLimitExceeded => {
                formatter.write_str("capture telescope exceeds its limit")
            },
            Self::MissingSpaceRight(right) => write!(formatter, "missing space right {right:?}"),
            Self::StaleEpoch => {
                formatter.write_str("prepared transaction has a stale authority epoch")
            },
            Self::EpochExhausted => formatter.write_str("channel authority epoch exhausted"),
            Self::Poisoned => formatter.write_str("theorem-channel state lock is poisoned"),
            Self::Certificate(error) => write!(formatter, "certificate error: {error}"),
            Self::LanguageAccess(error) => write!(formatter, "language access error: {error:?}"),
        }
    }
}

impl std::error::Error for TheoremChannelError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn hash(byte: u8) -> TermHash {
        TermHash([byte; 32])
    }

    #[test]
    fn normalized_meet_is_commutative_idempotent_and_refines_membership() {
        let category = CategoryId(7);
        let membership = AdmissionTheorem::membership(category);
        let exact = AdmissionTheorem::exact(category, hash(3));
        assert_eq!(membership.meet(exact), exact);
        assert_eq!(exact.meet(membership), exact);
        assert_eq!(exact.meet(exact), exact);
        assert!(exact.refines(membership));
        assert!(!membership.refines(exact));
        assert_eq!(
            membership.meet(AdmissionTheorem::membership(CategoryId(8))),
            AdmissionTheorem::Bottom
        );
    }

    #[test]
    fn certificate_and_cache_bind_every_consensus_identity_field() {
        let checker = StructuralTheoremChecker::default();
        let term = CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(4));
        let certificate = checker
            .check(term, AdmissionTheorem::membership(CategoryId(2)))
            .expect("membership certificate");
        checker.verify(&certificate).expect("certificate verifies");
        let key = ProofCacheKey::from(&certificate);
        assert_eq!(key.language, [1; 32]);
        assert_eq!(key.term_hash, hash(4));
        assert_eq!(key.checker_abi, STRUCTURAL_THEOREM_CHECKER_ABI_V1);
        assert_eq!(key.limit_profile, STRUCTURAL_THEOREM_LIMIT_PROFILE_V1);

        let mut cache = ProofCache::new(1);
        assert!(cache.insert(key.clone()));
        assert!(cache.contains(&key));
        let other = checker
            .check(
                CanonicalFltTerm::structurally_admitted([1; 32], CategoryId(2), hash(5)),
                AdmissionTheorem::membership(CategoryId(2)),
            )
            .expect("second certificate");
        assert!(!cache.insert(ProofCacheKey::from(&other)));
        assert_eq!(cache.len(), 1);
    }

    #[test]
    fn channel_refinement_rejects_cross_category_and_weaker_claims() {
        let member = AdmissionTheorem::membership(CategoryId(1));
        let exact = AdmissionTheorem::exact(CategoryId(1), hash(9));
        assert!(TheoremChannelDescriptor::new([3; 32], CategoryId(1), exact, member).is_ok());
        assert!(matches!(
            TheoremChannelDescriptor::new([3; 32], CategoryId(1), member, exact),
            Err(TheoremChannelError::InvalidRefinement)
        ));
        assert!(matches!(
            TheoremChannelDescriptor::new(
                [3; 32],
                CategoryId(1),
                AdmissionTheorem::membership(CategoryId(2)),
                member,
            ),
            Err(TheoremChannelError::CategoryMismatch)
        ));
    }
}
