//! Layered proof output: verdicts, human-readable explanations, Rocq certificates.
//!
//! Every analysis produces a structured result with multiple layers:
//! 1. **Verdict** (always included): verified/violated/unknown + witness traces
//! 2. **Human-readable explanation** (with `proofs` feature): detailed reasoning
//! 3. **Machine-checkable certificate** (with `proofs` feature): Rocq/Coq output
//!
//! The proof output layer consumes provenance information from the provenance
//! semiring to construct explanations that show not just WHAT was proven, but
//! HOW and WHY (which base facts, which derivation paths).

use crate::provenance::{ProvenanceVar, ProvenanceWeight};
use crate::verify::Verdict;
use std::fmt;

/// A proof step in a human-readable proof trace.
#[derive(Debug, Clone)]
pub struct ProofStep {
    /// Step number (1-based).
    pub step: usize,
    /// The statement being justified.
    pub statement: String,
    /// Justification (axiom, inference rule, etc.).
    pub justification: String,
    /// Provenance variables used in this step.
    pub base_facts: Vec<ProvenanceVar>,
}

impl fmt::Display for ProofStep {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "  {}. {} [{}]", self.step, self.statement, self.justification)?;
        if !self.base_facts.is_empty() {
            write!(f, "  (uses: ")?;
            let mut first = true;
            for var in &self.base_facts {
                if !first {
                    write!(f, ", ")?;
                }
                first = false;
                write!(f, "{}", var)?;
            }
            write!(f, ")")?;
        }
        Ok(())
    }
}

/// A complete proof output with layered detail levels.
#[derive(Debug, Clone)]
pub struct ProofOutput {
    /// The property being verified.
    pub property: String,
    /// The verdict.
    pub verdict: Verdict,
    /// Provenance polynomial summarizing how the result was derived.
    pub provenance: ProvenanceWeight,
    /// Human-readable proof steps.
    pub proof_steps: Vec<ProofStep>,
    /// Rocq/Coq certificate source (if generated).
    pub rocq_certificate: Option<String>,
}

impl ProofOutput {
    /// Create a new proof output with a verdict and provenance.
    pub fn new(
        property: impl Into<String>,
        verdict: Verdict,
        provenance: ProvenanceWeight,
    ) -> Self {
        ProofOutput {
            property: property.into(),
            verdict,
            provenance,
            proof_steps: Vec::new(),
            rocq_certificate: None,
        }
    }

    /// Add a proof step.
    pub fn add_step(
        &mut self,
        statement: impl Into<String>,
        justification: impl Into<String>,
        base_facts: Vec<ProvenanceVar>,
    ) {
        let step = self.proof_steps.len() + 1;
        self.proof_steps.push(ProofStep {
            step,
            statement: statement.into(),
            justification: justification.into(),
            base_facts,
        });
    }

    /// Generate a Rocq/Coq certificate skeleton for the proof.
    ///
    /// The generated certificate includes:
    /// - Theorem statement
    /// - Proof outline referencing the proof steps
    /// - Admitted subgoals (to be filled in by Rocq)
    pub fn generate_rocq_certificate(&mut self) {
        let mut cert = String::new();
        cert.push_str(&format!(
            "(* Auto-generated by MeTTaIL proof output layer *)\n"
        ));
        cert.push_str(&format!(
            "(* Property: {} *)\n",
            self.property
        ));
        cert.push_str(&format!(
            "(* Verdict: {} *)\n\n",
            self.verdict
        ));

        // Theorem statement.
        let theorem_name = self.property
            .replace(' ', "_")
            .replace(|c: char| !c.is_alphanumeric() && c != '_', "");
        cert.push_str(&format!(
            "Theorem {} :\n  (* {} *)\n  True. (* placeholder — replace with actual statement *)\n",
            theorem_name, self.property
        ));

        // Proof.
        cert.push_str("Proof.\n");
        for step in &self.proof_steps {
            cert.push_str(&format!(
                "  (* Step {}: {} [{}] *)\n",
                step.step, step.statement, step.justification
            ));
        }
        match self.verdict {
            Verdict::Verified => {
                cert.push_str("  trivial.\n");
            }
            Verdict::Violated => {
                cert.push_str("  (* Counterexample exists — property is false. *)\n");
                cert.push_str("  Admitted. (* The property does not hold. *)\n");
            }
            Verdict::Unknown => {
                cert.push_str("  Admitted. (* Analysis could not determine. *)\n");
            }
        }
        cert.push_str("Qed.\n");

        self.rocq_certificate = Some(cert);
    }

    /// Format as a human-readable proof trace.
    pub fn to_human_readable(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("Property: {}\n", self.property));
        out.push_str(&format!("Verdict:  {}\n", self.verdict));
        out.push_str(&format!("Provenance: {}\n", self.provenance));

        if !self.proof_steps.is_empty() {
            out.push_str("\nProof:\n");
            for step in &self.proof_steps {
                out.push_str(&format!("{}\n", step));
            }
        }

        if let Some(ref cert) = self.rocq_certificate {
            out.push_str(&format!("\nRocq Certificate:\n{}\n", cert));
        }

        out
    }
}

impl fmt::Display for ProofOutput {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_human_readable())
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// Pipeline bridge
// ══════════════════════════════════════════════════════════════════════════════

/// Pipeline bridge: generate proof certificates from all analysis results.
///
/// Consumes analysis results from all phases and produces proof certificates
/// for each verified property. Each certificate includes a verdict, provenance
/// polynomial, and human-readable proof steps.
///
/// Confluence and termination parameters require the `trs-analysis` feature;
/// safety checking is always available.
pub fn generate_certificates(
    #[cfg(feature = "trs-analysis")]
    confluence_result: Option<&crate::confluence::ConfluenceAnalysis>,
    #[cfg(feature = "trs-analysis")]
    termination_result: Option<&crate::termination::TerminationResult>,
    safety_result: Option<&crate::verify::SafetyResult<crate::automata::semiring::BooleanWeight>>,
) -> Vec<ProofOutput> {
    let mut outputs = Vec::new();

    // Confluence certificate
    #[cfg(feature = "trs-analysis")]
    if let Some(analysis) = confluence_result {
        if analysis.is_confluent {
            let mut proof = ProofOutput::new(
                "confluence",
                crate::verify::Verdict::Verified,
                ProvenanceWeight::var(ProvenanceVar::new("confluence_analysis")),
            );
            proof.add_step(
                format!("Checked {} critical pairs", analysis.critical_pairs.len()),
                "Knuth-Bendix criterion",
                vec![ProvenanceVar::new("critical_pair_enumeration")],
            );
            proof.add_step(
                format!(
                    "All {} critical pairs are joinable ({} non-joinable, {} unknown)",
                    analysis.critical_pairs.len(),
                    analysis.non_joinable_count,
                    analysis.unknown_count,
                ),
                "Joinability check",
                vec![ProvenanceVar::new("joinability_results")],
            );
            outputs.push(proof);
        } else {
            let mut proof = ProofOutput::new(
                "confluence",
                crate::verify::Verdict::Violated,
                ProvenanceWeight::var(ProvenanceVar::new("confluence_analysis")),
            );
            proof.add_step(
                format!(
                    "{} non-joinable critical pairs found",
                    analysis.non_joinable_count,
                ),
                "Knuth-Bendix criterion (failed)",
                vec![ProvenanceVar::new("non_joinable_pairs")],
            );
            outputs.push(proof);
        }
    }

    // Termination certificate
    #[cfg(feature = "trs-analysis")]
    if let Some(result) = termination_result {
        match result {
            crate::termination::TerminationResult::Terminating => {
                let mut proof = ProofOutput::new(
                    "termination",
                    crate::verify::Verdict::Verified,
                    ProvenanceWeight::var(ProvenanceVar::new("termination_analysis")),
                );
                proof.add_step(
                    "All SCCs have decreasing measures",
                    "Dependency pair method",
                    vec![ProvenanceVar::new("scc_ordering_witnesses")],
                );
                outputs.push(proof);
            }
            crate::termination::TerminationResult::PotentiallyNonTerminating {
                reason,
                problematic_sccs,
            } => {
                let mut proof = ProofOutput::new(
                    "termination",
                    crate::verify::Verdict::Unknown,
                    ProvenanceWeight::var(ProvenanceVar::new("termination_analysis")),
                );
                proof.add_step(
                    format!(
                        "Could not prove termination: {} (SCCs: {:?})",
                        reason, problematic_sccs,
                    ),
                    "Dependency pair method (inconclusive)",
                    vec![ProvenanceVar::new("problematic_sccs")],
                );
                outputs.push(proof);
            }
            crate::termination::TerminationResult::Unknown { reason } => {
                let mut proof = ProofOutput::new(
                    "termination",
                    crate::verify::Verdict::Unknown,
                    ProvenanceWeight::var(ProvenanceVar::new("termination_analysis")),
                );
                proof.add_step(
                    format!("Analysis inconclusive: {}", reason),
                    "Dependency pair method (inconclusive)",
                    vec![],
                );
                outputs.push(proof);
            }
        }
    }

    // Safety certificate
    if let Some(result) = safety_result {
        if result.safe {
            let mut proof = ProofOutput::new(
                "safety",
                crate::verify::Verdict::Verified,
                ProvenanceWeight::var(ProvenanceVar::new("safety_analysis")),
            );
            proof.add_step(
                "No bad state is reachable from the initial configuration",
                "Prestar analysis",
                vec![ProvenanceVar::new("prestar_fixpoint")],
            );
            outputs.push(proof);
        } else {
            let mut proof = ProofOutput::new(
                "safety",
                crate::verify::Verdict::Violated,
                ProvenanceWeight::var(ProvenanceVar::new("safety_analysis")),
            );
            proof.add_step(
                format!(
                    "Bad state reachable via witness trace of length {}",
                    result.witness_trace.len(),
                ),
                "Prestar analysis (counterexample found)",
                vec![ProvenanceVar::new("witness_trace")],
            );
            outputs.push(proof);
        }
    }

    outputs
}

// ══════════════════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provenance::ProvenanceVar;

    #[test]
    fn test_proof_output_verified() {
        let prov = ProvenanceWeight::var(ProvenanceVar::new("axiom1"));
        let mut proof = ProofOutput::new("safety property P", Verdict::Verified, prov);
        proof.add_step(
            "P is unreachable",
            "prestar analysis",
            vec![ProvenanceVar::new("axiom1")],
        );
        let output = proof.to_human_readable();
        assert!(output.contains("VERIFIED"));
        assert!(output.contains("safety property P"));
        assert!(output.contains("prestar analysis"));
    }

    #[test]
    fn test_proof_output_violated() {
        let prov = ProvenanceWeight::zero();
        let proof = ProofOutput::new("liveness property L", Verdict::Violated, prov);
        let output = proof.to_human_readable();
        assert!(output.contains("VIOLATED"));
    }

    #[test]
    fn test_rocq_certificate_generation() {
        let prov = ProvenanceWeight::one();
        let mut proof = ProofOutput::new("test property", Verdict::Verified, prov);
        proof.add_step("initial state is safe", "assumption", vec![]);
        proof.generate_rocq_certificate();
        let cert = proof.rocq_certificate.as_ref().expect("certificate should be generated");
        assert!(cert.contains("Theorem test_property"));
        assert!(cert.contains("trivial"));
        assert!(cert.contains("Step 1"));
    }

    #[test]
    fn test_proof_step_display() {
        let step = ProofStep {
            step: 1,
            statement: "x = 5".to_string(),
            justification: "assignment".to_string(),
            base_facts: vec![ProvenanceVar::new("fact_a")],
        };
        let s = step.to_string();
        assert!(s.contains("x = 5"));
        assert!(s.contains("assignment"));
        assert!(s.contains("fact_a"));
    }

    #[test]
    fn test_proof_output_display() {
        let prov = ProvenanceWeight::var(ProvenanceVar::new("ax1"))
            .plus(&ProvenanceWeight::var(ProvenanceVar::new("ax2")));
        let proof = ProofOutput::new("multi-axiom property", Verdict::Verified, prov);
        let display = format!("{}", proof);
        assert!(display.contains("multi-axiom property"));
        assert!(display.contains("VERIFIED"));
    }

    #[test]
    fn test_generate_certificates_with_safety() {
        use crate::automata::semiring::BooleanWeight;
        let safety_result = crate::verify::SafetyResult {
            safe: true,
            initial_weight: BooleanWeight(false),
            witness_trace: Vec::new(),
        };
        let certs = generate_certificates(
            #[cfg(feature = "trs-analysis")]
            None,
            #[cfg(feature = "trs-analysis")]
            None,
            Some(&safety_result),
        );
        assert!(!certs.is_empty(), "should produce at least one certificate from safety result");
    }

    #[test]
    fn test_generate_certificates_all_none() {
        let certs = generate_certificates(
            #[cfg(feature = "trs-analysis")]
            None,
            #[cfg(feature = "trs-analysis")]
            None,
            None,
        );
        assert!(certs.is_empty(), "should produce empty vec when all inputs are None");
    }
}
