//! Runtime support for MeTTaIL-generated code
//!
//! This crate provides:
//! - Variable binding support (via moniker wrappers)
//! - Collection types (HashBag for associative-commutative operations)
//! - Language metadata types for REPL introspection
//! - Core language traits and runtime-neutral backend reports
//! - Utility functions for parsing and variable management

// Variable binding support
mod binding;
pub use binding::*;

/// Runtime diagnostics queue (D11 ambiguous-display warnings, etc.).
/// Stage 7 of W7 plan v5.1.
pub mod diagnostics;

// Canonical float types for Float category (Eq/Hash/Ord)
mod canonical_float;
pub use canonical_float::{CanonicalFloat32, CanonicalFloat64};
mod canonical_bigint;
pub use canonical_bigint::CanonicalBigInt;
mod canonical_bigrat;
pub use canonical_bigrat::CanonicalBigRat;
mod canonical_fixed_point;
pub use canonical_fixed_point::CanonicalFixedPoint;

// L9-4: the native capture of a delimited FLT (foreign-language template) guest
// body — an opaque host-side leaf assembled by the `GuestBody` WPDA codegen.
mod flt_node;
pub use flt_node::{FltHole, FltHoleId, FltNode, FltTemplateError, FltTemplatePiece};

// Numeric literal parsers for fixed-point and float types. These live here
// (not in `mettail-prattail`) because they construct runtime types above and
// because the dep direction is runtime → prattail, not the reverse. Callers
// in generated code use `mettail_runtime::parse_fixed_lit` / `parse_float_lit`.
pub mod fixed_lit;
pub mod float_lit;
pub use fixed_lit::parse_fixed_lit;
pub use float_lit::parse_float_lit;

// Display-side fence-capture grouping; generated `Display` impls call
// `mettail_runtime::group_if_bare_delims` for any child slot whose rendered
// text could otherwise be split at one of the enclosing rule's own delimiters
// (a `.*sep(S)` separator, or the literal that terminates the slot).
pub mod display_grouping;
pub use display_grouping::{group_if_bare_delims, group_if_bare_sep, has_bare_any, has_bare_sep};

mod numeric_cast;
mod numeric_cast_dispatch;
pub use numeric_cast::{
    cast_bigint_from_bigrat, cast_bigint_from_f64, cast_bigint_from_fixed, cast_bigrat_from_bigint,
    cast_bigrat_from_f64, cast_bigrat_from_fixed, cast_bigrat_from_i64, cast_bigrat_from_u32,
    cast_fixed_from_bigint, cast_fixed_from_bigrat, cast_fixed_from_f64, cast_fixed_from_fixed,
    cast_float_from_bigint, cast_float_from_bigrat, cast_float_from_f64,
    cast_float_from_f64_allow_nonfinite, cast_float_from_fixed, cast_int_from_bigint,
    cast_int_from_bigrat, cast_int_from_f64, cast_int_from_fixed, cast_int_from_i64,
    cast_int_from_u32, cast_uint_from_bigint, cast_uint_from_bigrat, cast_uint_from_f64,
    cast_uint_from_fixed, cast_uint_from_i64, cast_uint_from_u32, f64_to_exact_rational,
    signed_modular, unsigned_modular, validate_fixed_places, validate_float_width,
    validate_int_uint_width, CastError, FloatCastWidth, MAX_FIXED_PLACES, MAX_INT_UINT_WIDTH,
};
pub use numeric_cast_dispatch::{
    bigint_unary_pipeline, bigint_unary_pipeline_decimal_str, bigrat_unary_pipeline,
    bigrat_unary_pipeline_numeric_str, fixed_bin_pipeline, fixed_bin_pipeline_numeric_str,
    float_bin_pipeline, float_bin_pipeline_parse_f64, int_bin_pipeline_decimal_str_i32,
    int_bin_pipeline_decimal_str_i64, int_bin_pipeline_i32, int_bin_pipeline_i64,
    int_uint_bits_from_width, numeric_try_bigint, numeric_try_bigrat, numeric_try_fixed,
    numeric_try_float, numeric_try_int, numeric_try_uint, uint_bin_pipeline_decimal_str_u32,
    uint_bin_pipeline_u32, NumericInput,
};
mod numeric_cast_adapter;

/// String-heuristic predicate for whether a rendered `@`-prefix operand is safe to
/// emit BARE (no disambiguating parens).
///
/// **SUPERSEDED / currently unused by the display codegen (2026-07-01).** The
/// `@`-quote round-trip fix now uses a GRAMMAR-DERIVED, per-rule structural AST
/// predicate — `<Cat>::__at_sigil_operand_needs_wrap`, generated by
/// `macros/src/gen/syntax/display.rs::generate_at_sigil_wrap_predicate` — instead
/// of this string scan. Two reasons the string heuristic was replaced:
///   1. It only checked a leading bare `@`, so it MISSED operand-leading Proc
///      operands (a top-level `|` infix, a `.method` postfix, a plain-channel
///      send) that also need `@(…)` — the `NQuoteShort(a | b)` under-wrap bug.
///   2. For a send CHANNEL (`n ! (q)`) it OVER-wrapped a bare `@`-sugar channel
///      into `(@Nil)`, which does NOT re-parse inside nested contexts
///      (`int((@Nil)!(Nil), 5)`, `a | (@Nil)!(Nil)`) — parser-truth shows EVERY
///      channel form is bare-OK, so the channel is now emitted bare.
/// Retained (not deleted) as a `pub` helper because it is a stable API surface and
/// documents the failed string-heuristic approach; new code should prefer the
/// structural predicate.
///
/// A bare `@<operand>` re-parses to the same term only when `<operand>` is a
/// single "primary" surface that the `@`-prefix precedence cap captures whole:
///   - it must NOT begin with `@` (else `@@…` abuts into one sigil), and
///   - it is an atom (ident / keyword / number) OR a keyword-call `kw(…)` / a
///     single bracket-delimited group (`(…)`, `[…]`, `{…}`, `{|…|}`, `#{…}#`)
///     that closes at the very end.
pub fn at_quote_bare_ok(s: &str) -> bool {
    // A leading BARE `@`-sugar (`@Nil` / `@p` / `@@…` — a `@` NOT immediately
    // followed by `(`) abuts or mis-dispatches under an outer `@`-prefix or `!!`
    // send. The already-delimited NQuote `@(…)` and every non-`@` surface (plain
    // names, literals, bracket groups) are round-trippable bare.
    let b = s.trim_start().as_bytes();
    !(b.first() == Some(&b'@') && b.get(1) != Some(&b'('))
}
pub use numeric_cast_adapter::{
    numeric_bigint_unary, numeric_bigrat_unary, numeric_fixed_bin, numeric_float_bin,
    numeric_int_bin_i32, numeric_int_bin_i64, numeric_uint_bin_u32, proc_bigint_unary,
    proc_bigrat_unary, proc_fixed_bin, proc_float_bin, proc_int_bin, proc_uint_bin, CastResult,
    CastWidth, ProcToNumericInput,
};

// ★ The REPORTED disposition of a partial operation — why it declined, carried as a value.
// `safe_arith` (below) is its producer; the generated Dovetail dispatcher is its consumer.
pub mod partiality;
pub use partiality::{
    Declarable, DeclineSink, DeclinedFold, FoldDisposition, Partiality, UndefinedReason,
};

// Overflow-safe / NaN-safe arithmetic used by generated eval and Ascent rules to convert
// panicking Rust arithmetic into `Result`-returning steps that NAME the partiality
// (`Partiality::{Undefined, NotRepresentable}`) rather than merely absenting a value.
mod safe_arith;
pub use safe_arith::{nan_is_a_value, QuietNaN, SafeArith, SafeFloat};

// Collection types
mod hashbag;
pub use hashbag::HashBag;

mod hashmap_lit;
pub use hashmap_lit::HashMapLit;

mod pathmap_lit;
pub use pathmap_lit::{
    PathMapEntry, PathMapEntryRef, PathMapIntoIter, PathMapIter, PathMapKeys, PathMapLit,
    PathMapMode, PathMapModeError,
};
mod zipper_lit;
pub use zipper_lit::{ReadZipperLit, WriteZipperLit};
mod pathmap_bridge;
pub use pathmap::PathMap as RawPathMap;
pub use pathmap_bridge::{
    homogeneous_lit_from_trie_and_keys, homogeneous_trie_and_key_index,
    pathmap_lit_from_trie_and_keys, trie_and_key_index_from_lit, trie_from_lit, trie_meet_lit,
    trie_merge_lit, trie_put_encoded, trie_restrict_lit, trie_subtract_lit, HomogeneousPathTrie,
    PathTrie,
};

mod hashset_lit;
pub use hashset_lit::HashSetLit;

mod collection_cmp_pda;
pub use collection_cmp_pda::{
    CollectionCmpItem, CollectionCmpPda, CollectionCmpRole, CollectionCmpStep,
};

mod collection_semantic_hash_pda;
pub use collection_semantic_hash_pda::{
    CollectionSemanticHashItem, CollectionSemanticHashPda, CollectionSemanticHashRole,
    CollectionSemanticHashStep, CollectionSemanticHasher, COLLECTION_SEMANTIC_KEY_ABI_V2,
};

// Language metadata for REPL introspection
mod metadata;
pub use metadata::*;

// Core language traits and types
mod language;
pub use language::*;

mod semantic_key;
pub use mettail_semantic_key as exact_semantic_key;
pub use semantic_key::FramedSemanticKeyHasher;

// Matchings enumeration for zip+map correlated search (used by generated rewrite clauses)
mod matchings;
pub use matchings::*;

// Hash-consing infrastructure for recursive term types (A-RT01)
mod hash_consing;
pub use hash_consing::*;

// Shared iterative-traversal infrastructure — extracted from the seven
// per-op engines previously hand-rolled by the macro per-language.
// See `runtime/src/visitor.rs` docs for scope + non-goals.
pub mod visitor;

/// Shared, representation-independent spatial-formula pushdown machine.
pub mod formula_pda;

// Runtime behavioral predicate AST for source-level predicated types.
// Phase 2A of the predicated-types implementation plan.
//
// This is a passive carrier type. At run time its relation lookups are
// evaluated by `evaluate_pred_with_bindings` against the thread-local fact
// snapshot (WPDA refinement guards), or enforced host-side at COMM for
// Rho-backed guarded languages (RSpace matching, a Rholang `where` guard, or a
// `RhoNativeJoin`). See `docs/design/predicated-types.md` §8. (The legacy
// Ascent Datalog JOIN-clause lowering was retired in P6.)
pub mod behavioral_pred;
pub use behavioral_pred::{
    clear_pred_fact_snapshot, evaluate_pred_with_bindings, set_pred_fact_snapshot, BehavioralPred,
    PredArg, QuantifiedDomain, Quantifier,
};

// Phase 7: refinement-type predicate registry + evaluator. Generated
// rule action codegen calls `evaluate_refinement_predicate` after
// constructing a candidate term against a refined category to enforce
// the refinement.
pub mod refinement;
pub use refinement::{
    clear_refinement_registry, evaluate_refinement_predicate, register_refinement_predicate,
    RefinementPredicate,
};

// T4 user assertion registry — see `t4_assertions` for full lifecycle.
// Phase 7C of the predicated-types implementation plan.
pub mod t4_assertions;
pub use t4_assertions::{
    clear_t4_assertions, register_t4_assertion, t4_assertion_lookup, T4Assertion, T4AssertionHandle,
};

// Language-generic parsers for sub-sublanguages embedded inside
// `language!`-defined languages. Currently hosts the predicate
// sublanguage parser (Phase 1B of the predicated-types implementation
// plan).
pub mod parser;
pub use parser::{
    parse_predicate_from_str, ParseError, PredicateParser, PredicateParserConfig, TerminatorToken,
};

/// `Lift<T>` — autoref-specialization helper used by the macro-generated
/// safeify wrapper around user `![…]` eval blocks.
///
/// **Problem solved:** the safeify pass rewrites `![a + b]` into
/// `(|| -> Result<_, Partiality> { Ok(safe_add(a,b)?) })()` (one level of
/// `Result`). But user evals like `![{ calc_try_int_bin(&a, w) }]` *already*
/// return `Option<i32>`, and a body that already reports its own partiality
/// returns `Result<i32, Partiality>`. Wrapping either with `Ok(...)` would
/// produce a nested `Result<Option<…>, …>` / `Result<Result<…>, …>` where the
/// expected type is one level deep.
///
/// **Solution:** the generated closure body becomes `Lift(rewritten).lift()`
/// where method resolution picks:
///   - the inherent method on `Lift<Result<T, Partiality>>` (passthrough) when
///     the expression already reports its own partiality;
///   - the inherent method on `Lift<Option<T>>`, which converts the bare
///     absence into [`Partiality::Unreported`] — a decline that names the site
///     while recording, truthfully, that no reason was stated;
///   - the trait method on `&Lift<T>` (returns `Ok(t)`) for plain `T`.
///
/// This is the dtolnay autoref-specialization trick: inherent methods bind
/// without autoref, trait methods bind with autoref, so an inherent
/// passthrough always wins for the two specialised shapes.
///
/// ★ **Why `Option<T>` maps to `Unreported` rather than to a silent deferral.**
/// A `try_*` helper answering `None` is a body declining without saying why;
/// the whole subject of `Partiality` is that such silence used to be
/// indistinguishable from "no rule applies". Mapping it to a *named* decline
/// makes every such site visible in the run report, which is how the remaining
/// unvocalised partialities get found. A genuinely structural "not yet" is
/// spelled explicitly — `safeify` emits
/// [`partiality::not_reduced`](crate::partiality::not_reduced) for `x.eval()`
/// ⟶ `x.try_eval()`, which produces [`Partiality::NotReduced`] and defers.
pub mod lift {
    use crate::partiality::Partiality;

    /// Newtype wrapper used to drive method-resolution dispatch.
    /// Always constructed by-value at the call site and consumed by `.lift()`.
    pub struct Lift<T>(pub T);

    impl<T> Lift<Result<T, Partiality>> {
        /// Inherent passthrough for a body that ALREADY reports its own partiality.
        ///
        /// Wins over the trait impl on `&Lift<…>` because no autoref is
        /// needed, and inherent-method resolution outranks trait-method
        /// resolution at equal autoref depth.
        #[inline]
        pub fn lift(self) -> Result<T, Partiality> {
            self.0
        }
    }

    impl<T> Lift<Option<T>> {
        /// Inherent conversion for a body whose tail is a bare `Option<T>`: the absence carries
        /// no reason, so it becomes [`Partiality::Unreported`] — recorded as a decline whose
        /// finding is precisely that no reason was declared.
        #[inline]
        pub fn lift(self) -> Result<T, Partiality> {
            self.0.ok_or(Partiality::Unreported)
        }
    }

    /// Trait providing `lift()` on `&Lift<T>` for plain (non-`Option`, non-`Result`) `T`.
    ///
    /// The autoref step happens via `Lift(x).lift()`; for the two specialised
    /// shapes the inherent method binds first (no autoref) and this trait is
    /// bypassed. For plain `T`, autoref takes `&Lift<T>` and dispatches here.
    ///
    /// `T: Clone` is required because the receiver is a borrow — we cannot
    /// move `T` out of `&Lift<T>` safely. All numeric/string/canonical types
    /// generated code uses already implement `Clone`, so this is not a
    /// real-world restriction.
    pub trait LiftPlain {
        type Output;
        fn lift(self) -> Self::Output;
    }

    impl<T: Clone> LiftPlain for &Lift<T> {
        type Output = Result<T, Partiality>;
        #[inline]
        fn lift(self) -> Result<T, Partiality> {
            Ok(self.0.clone())
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// Inherent specialization wins for `Option<T>`: the value passes through into `Ok`.
        ///
        /// Method resolution: `Lift(x).lift()` finds the inherent
        /// `impl Lift<Option<T>>::lift` without needing autoref, so it
        /// outranks the trait impl on `&Lift<T>`.
        #[test]
        fn lift_option_passes_through_some() {
            let x: Option<i32> = Some(42);
            let out: Result<i32, Partiality> = Lift(x).lift();
            assert_eq!(out, Ok(42));
        }

        /// ★ A bare `None` becomes a NAMED decline, not an anonymous absence.
        #[test]
        fn lift_option_none_becomes_an_unreported_decline() {
            let x: Option<i32> = None;
            let out: Result<i32, Partiality> = Lift(x).lift();
            assert_eq!(out, Err(Partiality::Unreported));
            assert!(
                out.unwrap_err().is_decline(),
                "a helper that declines without a reason is still a decline — the silence is \
                 the finding",
            );
        }

        /// ★ A body that ALREADY reports its partiality passes through unchanged — no
        /// double-wrap, and its reason is not overwritten by `Unreported`.
        #[test]
        fn lift_result_passes_its_own_partiality_through() {
            let carried = Partiality::Undefined {
                operation: "div",
                carrier: "i64",
                reason: crate::partiality::UndefinedReason::DivisionByZero,
            };
            let x: Result<i32, Partiality> = Err(carried);
            let out: Result<i32, Partiality> = Lift(x).lift();
            assert_eq!(out, Err(carried), "the inner reason must survive the lift");
            let ok: Result<i32, Partiality> = Lift(Ok::<i32, Partiality>(5)).lift();
            assert_eq!(ok, Ok(5));
        }

        /// Trait fallback wraps a plain `T` in `Ok`.
        ///
        /// `Lift(x).lift()` for `x: i32` finds no inherent on
        /// `Lift<i32>` (only `Lift<Option<T>>` and `Lift<Result<T, Partiality>>`
        /// have one), so resolution autorefs to `&Lift<i32>` and the trait impl
        /// `LiftPlain for &Lift<T>` binds, returning `Ok(x)`.
        #[test]
        fn lift_plain_t_wraps_ok() {
            let x: i32 = 7;
            let out: Result<i32, Partiality> = Lift(x).lift();
            assert_eq!(out, Ok(7));
        }

        /// Plain `T` with non-`Copy` payload is moved (not cloned).
        #[test]
        fn lift_plain_moves_owned() {
            let s = String::from("hello");
            let out: Result<String, Partiality> = Lift(s).lift();
            assert_eq!(out.as_deref(), Ok("hello"));
        }
    }
}

/// Wrapper that provides `Display` for slices/Vecs of `Display` items.
///
/// Renders as a comma-separated list, e.g. `a, b, c`.
/// Used by generated extraction code so `Vec<T>` columns get pretty-printed
/// via `T`'s `Display` impl rather than falling back to `Debug`.
pub struct DisplaySlice<'a, T>(pub &'a [T]);

impl<T: std::fmt::Display> std::fmt::Display for DisplaySlice<'_, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for (i, item) in self.0.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", item)?;
        }
        Ok(())
    }
}
