//! ★★ #112/D4 — THE PUBLISHED DEAD-RULE LIST, MEASURED ON THE REAL RHOLANG ARTIFACT.
//!
//! # What this suite is, and why it lives here rather than in `prattail`
//!
//! `prattail::pipeline::tests::the_dead_rule_list_does_not_name_a_rule_the_action_table_dispatches`
//! isolates the MECHANISM on a synthetic fixture: an operand-led rule is flagged by Tier 3
//! and must not be promoted into `PipelineAnalysis::dead_rule_labels`. It cannot use a
//! bundled grammar, because `languages` depends on `prattail` and not the reverse.
//!
//! This suite supplies the other half — the CORPUS WITNESS — from the side of the
//! dependency graph that can see Rholang. It reads the artefacts the `language!` macro
//! actually wrote for it:
//!
//! ```text
//!   target/generated/rholang/tests_unit.rs   the PUBLISHED list (a header comment)
//!   target/generated/rholang/wpda.rs         the ACTION table (what really dispatches)
//! ```
//!
//! and shows that the same rule cannot be in both. Neither file is hand-written; both are
//! regenerated on every compile of `languages`, which is a prerequisite of running this
//! test at all.
//!
//! # ⚠ The measurement before the repair
//!
//! At `0808b258`, `target/generated/rholang/tests_unit.rs` opened with
//!
//! ```text
//!   // Dead rules detected by WFST analysis: ["Bag::BagLit", …, "Proc::POutput", …]
//! ```
//!
//! — **149 entries**, among them `Proc::POutput` (`n!(p)`, the Rholang send), `Proc::PNew`
//! (`new x in { … }`) and `Name::NQuote` (`@P`). Three of the most-used constructs in the
//! language, published as dead, in a file every generated test suite includes.
//!
//! The cause is one line (`prattail/src/pipeline/dead_rules.rs`) admitting
//! `DeadRuleWarning::WfstUnreachable` — Tier 3 — into a set two doc comments said excluded
//! it, behind a "trie confirmation" pass that cross-validates the prediction WFST against
//! `CategoryDecisionTree::reachable_rules()`. Both are indexed by DISPATCH TOKEN, so both
//! are blind to a rule reached through the Pratt loop's operand path, and agreeing was
//! never evidence.
//!
//! # The three assertions, and why each is separate
//!
//! Asserted one token at a time so the failure message names WHICH rule survived. A
//! shrinkage assertion (`len < 160`) would pass on any change at all and is exactly the
//! vacuity this campaign has been bitten by.

#![cfg(feature = "rholang")]

use std::path::{Path, PathBuf};

/// The generated-artefact directory. `CARGO_TARGET_DIR` wins when set, so a caller who
/// redirects the build tree still measures the tree that was just built.
fn generated_dir() -> PathBuf {
    let target = match std::env::var_os("CARGO_TARGET_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("`languages` is a workspace member, so its manifest dir has a parent")
            .join("target"),
    };
    target.join("generated").join("rholang")
}

fn read_artifact(name: &str) -> String {
    let path = generated_dir().join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the generated artefact {}: {e}\n\nIt is written by the `language!` \
             macro during the compilation of `mettail_languages`, which is a dependency of \
             this test — so a missing file means the walk is looking in the wrong place, \
             never that the artefact is optional.",
            path.display()
        )
    })
}

/// The labels the generated unit-test section publishes as having no reachable parse.
///
/// Returns an empty vector when the caption is absent, which is what the emitter does when
/// the set itself is empty (`macros/src/gen/test_gen/mod.rs::emit_test_file_header`).
fn published_labels(source: &str) -> Vec<String> {
    let Some(line) = source
        .lines()
        .find(|l| l.starts_with("// Rules with no reachable parse"))
    else {
        return Vec::new();
    };
    let Some(open) = line.find('[') else {
        return Vec::new();
    };
    line[open..]
        .split('"')
        .skip(1)
        .step_by(2)
        .map(str::to_string)
        .collect()
}

/// ★★ THE CELL. Three live Rholang constructors are not published as unreachable.
#[test]
fn the_published_dead_rule_list_does_not_name_a_rule_the_action_table_dispatches() {
    let unit = read_artifact("tests_unit.rs");

    // ── ANCHOR: the walk reached the Rholang unit section and not some other file. ────
    assert!(
        unit.starts_with("// AUTO-GENERATED by language! macro for Rholang (unit)"),
        "★ the artefact read is not the Rholang unit section, so every assertion below \
         would be about the wrong file. First line: {:?}",
        unit.lines().next(),
    );

    let published = published_labels(&unit);

    // ── THE MUTATION'S SIGNATURE — one token per assertion. ──────────────────────────
    for (label, surface) in [
        ("Proc::POutput", "n!(p) — the send"),
        ("Proc::PNew", "new x in { … } — name restriction"),
        ("Name::NQuote", "@P — quotation"),
    ] {
        assert!(
            !published.contains(&label.to_string()),
            "★ `{label}` ({surface}) is published as having no reachable parse, in a file \
             every generated Rholang test suite includes. It is operand-led or \
             keyword-led-with-an-operand, so the prediction WFST's prefix dispatch cannot \
             see it — and `CategoryDecisionTree::reachable_rules()`, the model that was \
             supposed to confirm the verdict, is a trie over the SAME dispatch tokens. \
             Published list ({} entries): {published:?}",
            published.len(),
        );
    }

    // ── THE CAPTION SAYS WHAT IT MEASURES. ───────────────────────────────────────────
    assert!(
        !unit.contains("Dead rules detected by WFST analysis"),
        "★ the caption still claims a WFST reachability verdict. The set is Tier 1 \
         (literal in a category with no native_type) + Tier 2 (infix/var in an unreachable \
         category) + SYM01 (guard proven UNSAT) — no WFST result is in it. A caption that \
         reads as a deadness verdict over a set that is not one is a defect even when the \
         entries are all correct: it is what a reader acts on.",
    );
}

/// ★ THE CROSS-CHECK: `POutput` has a LIVE ACTION, shown on the same run.
///
/// Without this, "not in the dead list" and "not in the grammar" are the same observation.
/// `wpda.rs` carries both halves of the evidence — the per-category rule table
/// (`WPDA_RULES`, whose entry is what an emitted WPDS weight's `rule_idx` refers to) and
/// the semantic action that constructs the node. A rule with both is dispatchable, and the
/// two facts are therefore shown simultaneously true.
#[test]
fn the_rule_the_list_used_to_name_has_an_emitted_action() {
    let wpda = read_artifact("wpda.rs");

    assert!(
        wpda.contains("(\"POutput\","),
        "★ `POutput` must appear in `WPDA_RULES` — the per-category `(label, rule_idx)` \
         table every emitted WPDS weight indexes into. Without this entry the cross-check \
         above proves nothing, because there would be no dispatchable rule to contradict.",
    );
    assert!(
        wpda.contains("Proc::POutput("),
        "★ `POutput` must have an emitted semantic action constructing `Proc::POutput(..)`. \
         `WPDA_RULES` alone is a name; the action is the machine that runs.",
    );
}

/// ★ THE CONTROL THAT MUST NOT DISCRIMINATE: the list is still a list.
///
/// Deleting the Tier-3 arm must remove Tier-3 entries and nothing else. Tier 1 (a literal
/// rule in a category with no `native_type`) is still a proof and its entries must survive
/// — a repair that emptied the set entirely would satisfy the cell above and would have
/// removed a real analysis.
///
/// ⚠ Asserted as "the published set is non-empty AND every surviving entry is qualified",
/// not as a fixed membership list: which particular Tier-1 rules Rholang has is a property
/// of the grammar, and pinning them here would make an ordinary grammar edit fail a test
/// about the dead-rule analysis. The Tier-1 and Tier-2 *mechanisms* are pinned by name in
/// `prattail::pipeline::tests`, where a synthetic fixture can hold them still.
#[test]
fn tier_one_survivors_are_still_published() {
    let unit = read_artifact("tests_unit.rs");
    let published = published_labels(&unit);

    assert!(
        !published.is_empty(),
        "★ THE CONTROL: the published set is EMPTY. Rholang declares literal rules in \
         categories with no `native_type`, so Tier 1 has survivors and the repair was \
         over-broad — it deleted the admission rather than the Tier-3 arm.",
    );
    assert!(
        published.len() < 149,
        "★ 149 entries is the PRE-REPAIR count, measured at `0808b258`. A list that has not \
         shrunk means the Tier-3 admission is back. Published: {published:?}",
    );
}
