// AUTO-GENERATED by language! macro for OptSmoke (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::optsmoke::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn optsmoke_language_instantiates() {
    let lang = OptSmokeLanguage;
    assert_eq!(lang.name(), "OptSmoke");
}

#[test]
fn optsmoke_metadata_populated() {
    let lang = OptSmokeLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_optsmoke_int_ifelse() {
    mettail_runtime::clear_var_cache();
    let term = Int::IfElse(
        std::sync::Arc::new(Bool::BoolLit(false)),
        std::sync::Arc::new(Int::NumLit(0i32)),
        None,
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for IfElse");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for IfElse: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_optsmoke_int_booltoint() {
    mettail_runtime::clear_var_cache();
    let term = Int::BoolToInt(std::sync::Arc::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolToInt");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for BoolToInt: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_optsmoke_auto_int_numlit() {
    let term = Int::NumLit(0i32);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_optsmoke_auto_bool_boollit() {
    let term = Bool::BoolLit(false);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolLit");
    if let Ok(parsed) = Bool::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for BoolLit: {} != {}",
            displayed, re_displayed
        );
    }
}
