// AUTO-GENERATED by language! macro for AppSubst (rewrite) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::appsubst::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Rewrite tests (one per rewrite rule)
// ═══════════════════════════════════════════════════════════

#[test]
fn rewrite_appsubst_reduce() {
    let _lang = AppSubstLanguage;
    let meta = _lang.metadata();
    let rewrites = meta.rewrites();
    // Verify rewrite Reduce (index 0) exists in metadata
    assert!(
        rewrites.len() > 0,
        "Expected at least 1 rewrites in metadata, found {}",
        rewrites.len()
    );
    let rw = &rewrites[0];
    // Verify rewrite rule name
    assert_eq!(rw.name, Some("Reduce"), "Rewrite rule name mismatch");
    assert!(!rw.lhs.is_empty(), "Rewrite Reduce LHS should be non-empty");
    assert!(!rw.rhs.is_empty(), "Rewrite Reduce RHS should be non-empty");
}

// Concrete execution test: run "ap ( 0 , 0 )" through SimulationRunner,
// assert it reaches NormalForm (exercises rewrite rule Reduce).
#[test]
fn rewrite_appsubst_reduce_exec() {
    use mettail_simulation::runner::{SimulationConfig, SimulationRunner};
    use mettail_simulation::trace::TraceOutcome;
    let lang = AppSubstLanguage;
    let lang_ref: &dyn mettail_runtime::Language = &lang;
    let config = SimulationConfig {
        max_steps: 100,
        track_morphology: false,
        ..SimulationConfig::default()
    };
    let runner = SimulationRunner::new(lang_ref, config);
    mettail_runtime::clear_var_cache();
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        runner.run_to_normal_form("ap ( 0 , 0 )")
    }));
    if let Ok(Ok(trace)) = result {
        assert!(
            matches!(trace.outcome, TraceOutcome::NormalForm { .. }),
            "Rewrite rule Reduce: input 'ap ( 0 , 0 )' did not reach NF: {:?}",
            trace.outcome,
        );
    }
    // Panics (e.g., division by zero in native eval) are tolerated.
}

// Rewrite test for ApCongL skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_appsubst_apcongl() {
    let _lang = AppSubstLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for ApCongR skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_appsubst_apcongr() {
    let _lang = AppSubstLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for AbsCong skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_appsubst_abscong() {
    let _lang = AppSubstLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}
