// AUTO-GENERATED by language! macro for InOutDemo (rewrite) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::inoutdemo::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Rewrite tests (one per rewrite rule)
// ═══════════════════════════════════════════════════════════

#[test]
fn rewrite_inoutdemo_inrule() {
    let _lang = InOutDemoLanguage;
    let meta = _lang.metadata();
    let rewrites = meta.rewrites();
    // Verify rewrite InRule (index 0) exists in metadata
    assert!(
        rewrites.len() > 0,
        "Expected at least 1 rewrites in metadata, found {}",
        rewrites.len()
    );
    let rw = &rewrites[0];
    // Verify rewrite rule name
    assert_eq!(rw.name, Some("InRule"), "Rewrite rule name mismatch");
    assert!(!rw.lhs.is_empty(), "Rewrite InRule LHS should be non-empty");
    assert!(!rw.rhs.is_empty(), "Rewrite InRule RHS should be non-empty");
}

#[test]
fn rewrite_inoutdemo_outrule() {
    let _lang = InOutDemoLanguage;
    let meta = _lang.metadata();
    let rewrites = meta.rewrites();
    // Verify rewrite OutRule (index 1) exists in metadata
    assert!(
        rewrites.len() > 1,
        "Expected at least 2 rewrites in metadata, found {}",
        rewrites.len()
    );
    let rw = &rewrites[1];
    // Verify rewrite rule name
    assert_eq!(rw.name, Some("OutRule"), "Rewrite rule name mismatch");
    assert!(!rw.lhs.is_empty(), "Rewrite OutRule LHS should be non-empty");
    assert!(!rw.rhs.is_empty(), "Rewrite OutRule RHS should be non-empty");
}

// Concrete execution test: run "0 [ 0 ]" through SimulationRunner,
// assert it reaches NormalForm (exercises rewrite rule OutRule).
#[test]
fn rewrite_inoutdemo_outrule_exec() {
    use mettail_simulation::runner::{SimulationConfig, SimulationRunner};
    use mettail_simulation::trace::TraceOutcome;
    let lang = InOutDemoLanguage;
    let lang_ref: &dyn mettail_runtime::Language = &lang;
    let config = SimulationConfig {
        max_steps: 100,
        track_morphology: false,
        ..SimulationConfig::default()
    };
    let runner = SimulationRunner::new(lang_ref, config);
    mettail_runtime::clear_var_cache();
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        runner.run_to_normal_form("0 [ 0 ]")
    }));
    if let Ok(Ok(trace)) = result {
        assert!(
            matches!(trace.outcome, TraceOutcome::NormalForm { .. }),
            "Rewrite rule OutRule: input '0 [ 0 ]' did not reach NF: {:?}",
            trace.outcome,
        );
    }
    // Panics (e.g., division by zero in native eval) are tolerated.
}
