// AUTO-GENERATED by language! macro for Class2OptSmoke (prop) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::class2optsmoke::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Proptest strategies + property tests (tape-based)
// ═══════════════════════════════════════════════════════════

use proptest::prelude::*;
use proptest::strategy::BoxedStrategy;

/// Heterogeneous term wrapper for the tape-based builder.
#[allow(dead_code)]
#[derive(Clone)]
enum AnyTerm {
    WrapProc(Proc),
}

impl AnyTerm {
    #[allow(dead_code)]
    fn unwrap_proc(self) -> Proc {
        match self {
            AnyTerm::WrapProc(v) => v,
        }
    }
}

/// Work item for the tape-based iterative term builder.
#[allow(dead_code)]
enum BuildTask {
    /// Build a Proc term at the given depth, storing result in the given slot.
    BuildProc { depth: u32, slot: usize },
}

/// Helper to consume bytes from the tape.
#[allow(dead_code)]
struct TapeReader<'a> {
    tape: &'a [u8],
    pos: usize,
}

#[allow(dead_code)]
impl<'a> TapeReader<'a> {
    fn new(tape: &'a [u8]) -> Self {
        TapeReader { tape, pos: 0 }
    }

    /// Read the next byte. On exhaustion return 0 — do NOT wrap. Byte 0 maps
    /// to constructor choice `0 % N == 0`, which is ALWAYS a leaf: every
    /// `build_*_from_tape` match emits its leaf arms before its recursive arms
    /// (see `classify_variants`), so choice 0 selects `leaves[0]` and the
    /// recursion bottoms out to the simplest term — the documented intent
    /// "shorter tapes = simpler terms". The old `pos % len` wrap RE-READ the
    /// same recursive-constructor byte at every level, so a 1-byte tape
    /// `[0x38]` built a COMPLETE binary tree down to max_depth (0x38 ->
    /// `MulBigRat` at all internal nodes -> `error*error*...`), which drove
    /// BigRat::parse into the exponential cross-category axis (~9s).
    fn next_byte(&mut self) -> u8 {
        if self.pos >= self.tape.len() {
            return 0;
        }
        let b = self.tape[self.pos];
        self.pos += 1;
        b
    }

    /// Read a u32 from 4 bytes (little-endian); reads 0 past end of tape.
    fn next_u32(&mut self) -> u32 {
        let b0 = self.next_byte() as u32;
        let b1 = self.next_byte() as u32;
        let b2 = self.next_byte() as u32;
        let b3 = self.next_byte() as u32;
        b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)
    }

    /// Read an i32 from tape bytes.
    ///
    /// Returns the full i32 range. Overflow in `![a + b]` native eval paths is
    /// handled by the `SafeArith` trait and the `rust_code_rewrite` pass in the
    /// `language!` macro: arithmetic operators are rewritten to `safe_add`,
    /// `safe_mul`, etc., which return `Option<T>` on overflow rather than
    /// panicking. This removes the need for a restricted range here.
    fn next_i32(&mut self) -> i32 {
        self.next_u32() as i32
    }

    /// Read an i64 from tape bytes.
    fn next_i64(&mut self) -> i64 {
        let lo = self.next_u32() as i64;
        let hi = self.next_u32() as i64;
        lo | (hi << 32)
    }

    /// Read an f64 from tape bytes.
    fn next_f64(&mut self) -> f64 {
        let bits = self.next_i64() as u64;
        let val = f64::from_bits(bits);
        // Avoid NaN/Inf which cause issues with Eq/Ord
        if val.is_nan() || val.is_infinite() {
            0.0
        } else {
            val
        }
    }

    /// Read an f32 from tape bytes.
    fn next_f32(&mut self) -> f32 {
        let bits = self.next_u32();
        let val = f32::from_bits(bits);
        if val.is_nan() || val.is_infinite() {
            0.0f32
        } else {
            val
        }
    }

    /// Read a bool from tape.
    fn next_bool(&mut self) -> bool {
        self.next_byte() & 1 == 1
    }

    /// Read a short string from tape.
    fn next_string(&mut self) -> String {
        let len = (self.next_byte() % 8) as usize;
        (0..len)
            .map(|_| {
                let b = self.next_byte();
                // Map to printable ASCII range 'a'-'z'
                (b'a' + (b % 26)) as char
            })
            .collect()
    }
}

/// Build a `Proc` term from an instruction tape.
///
/// Consumes bytes from the tape to choose constructors.
/// At depth 0, only leaf constructors (nullary, literal, var) are chosen.
/// At depth > 0, recursive constructors are also available.
#[allow(dead_code, unused_variables, clippy::let_and_return)]
fn build_proc_from_tape(reader: &mut TapeReader<'_>, depth: u32) -> Proc {
    if depth == 0 {
        let choice = (reader.next_byte() as usize) % 2;
        let result = match choice {
            0 => AnyTerm::WrapProc(Proc::PZero),
            _ => {
                let _ = reader.next_byte(); // consume tape byte for replay determinism
                AnyTerm::WrapProc(Proc::PVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(
                    mettail_runtime::get_or_create_var("a"),
                ))))
            },
        };
        return result.unwrap_proc();
    }

    let choice = (reader.next_byte() as usize) % 3;
    let child_depth = depth - 1;
    match choice {
        0 => AnyTerm::WrapProc(Proc::PZero).unwrap_proc(),
        1 => {
            let _ = reader.next_byte(); // consume tape byte for replay determinism
            AnyTerm::WrapProc(Proc::PVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a"),
            ))))
        }
        .unwrap_proc(),
        _ => {
            let f0 = std::sync::Arc::new(build_proc_from_tape(reader, child_depth));
            let f1 = if reader.next_byte() & 1 == 0 {
                None
            } else {
                let num_elems = (reader.next_byte() % 4) as usize;
                let v: Vec<_> = (0..num_elems)
                    .map(|_| build_proc_from_tape(reader, child_depth))
                    .collect();
                Some(v)
            };
            Proc::ChooseMaybe(f0, f1)
        },
    }
}

/// Generate an arbitrary `Proc` term with bounded depth.
///
/// Uses a flat `Vec<u8>` tape interpreted by `build_proc_from_tape`.
/// Proptest shrinking produces shorter tapes = simpler terms.
#[allow(dead_code)]
fn arb_proc(max_depth: u32) -> BoxedStrategy<Proc> {
    // Tape size scales with depth: deeper terms need more bytes
    let max_tape = (10 * (max_depth as usize + 1)).max(20);
    proptest::collection::vec(any::<u8>(), 1..max_tape)
        .prop_map(move |tape| {
            let mut reader = TapeReader::new(&tape);
            build_proc_from_tape(&mut reader, max_depth)
        })
        .boxed()
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(100))]

    #[test]
    fn proc_debug_does_not_panic(term in arb_proc(4)) {
        let _ = format!("{:?}", term);
    }

    #[test]
    fn proc_display_does_not_panic(term in arb_proc(4)) {
        let _ = format!("{}", term);
    }

    #[test]
    fn proc_clone_eq(term in arb_proc(4)) {
        let cloned = term.clone();
        prop_assert_eq!(term, cloned);
    }

    #[test]
    fn proc_display_parse_roundtrip(term in arb_proc(3)) {
        let displayed = format!("{}", term);
        // Skip terms whose display is too long (parser may overflow).
        // NOTE: length is only a coarse backstop against degenerate
        // displays; cross-category-shared operator chains are parsed
        // via the walker's k-best extraction, so depth-3 terms are cheap.
        if displayed.len() > 500 {
            return Ok(());
        }
        // GRAMMAR-AWARE ROUNDTRIP CONTRACT (strengthened from
        // silent-skip): the literal-build codegen now projects
        // tape values onto the language's admitted literal
        // domain (see rust_code_rewrite + automaton_walk::classify).
        // Any parse failure here is a real regression — the
        // generator emitted something the grammar does not admit.
        // Canonical-form idempotence:
        //   Parse(Display(Parse(s))) ≡ Parse(s) for any s that
        //   the generator emits.
        let parsed = Proc::parse(&displayed)
            .unwrap_or_else(|e| panic!(
                "arb_proc produced unparseable surface term {:?}: {:?}",
                displayed, e));
        let canonical = format!("{}", parsed);
        if canonical.len() > 500 { return Ok(()); }
        let reparsed = Proc::parse(&canonical).unwrap_or_else(|e| panic!(
            "Parse(Display(Parse(s))) should succeed for canonical form {:?}: {:?}",
            canonical, e));
        let recanonical = format!("{}", reparsed);
        prop_assert_eq!(canonical, recanonical,
            "Display should be idempotent after canonicalization: \
             display(parse(display(parse(display(t))))) == display(parse(display(t)))");
    }

    #[test]
    fn proc_strong_roundtrip(term in arb_proc(1)) {
        mettail_runtime::clear_var_cache();
        let displayed = format!("{}", term);
        // Skip terms whose display is too long (parser may overflow)
        if displayed.len() > 500 {
            return Ok(());
        }
        mettail_runtime::clear_var_cache();
        if let Ok(parsed) = Proc::parse(&displayed) {
            let canonical = format!("{}", parsed);
            if canonical.len() > 500 { return Ok(()); }
            mettail_runtime::clear_var_cache();
            let reparsed = Proc::parse(&canonical).unwrap_or_else(|e| panic!(
                "Strong roundtrip: canonical form {:?} did not parse: {:?}",
                canonical, e));
            let recanonical = format!("{}", reparsed);
            prop_assert_eq!(&canonical, &recanonical,
                "Strong roundtrip: canonical display not stable after double parse");
        }
    }

    #[test]
    fn proc_parse_determinism(term in arb_proc(2)) {
        mettail_runtime::clear_var_cache();
        let displayed = format!("{}", term);
        // Skip terms whose display is too long (parser may overflow)
        if displayed.len() > 500 {
            return Ok(());
        }
        mettail_runtime::clear_var_cache();
        let p1 = Proc::parse(&displayed);
        mettail_runtime::clear_var_cache();
        let p2 = Proc::parse(&displayed);
        match (p1, p2) {
            (Ok(t1), Ok(t2)) => {
                let d1 = format!("{}", t1);
                let d2 = format!("{}", t2);
                prop_assert_eq!(d1, d2,
                    "Parse determinism failed: two parses of the same string differ");
            }
            (Err(_), Err(_)) => { /* Both failed — consistent */ }
            (Ok(_), Err(e)) | (Err(e), Ok(_)) => {
                prop_assert!(false,
                    "Parse determinism failed: one parse succeeded, other failed: {}", e);
            }
        }
    }

}
