// AUTO-GENERATED by language! macro for Lambda (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::lambda::*;
use mettail_runtime::Language;
use mettail_runtime::BehavioralPred;

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn lambda_language_instantiates() {
    let lang = LambdaLanguage;
    assert_eq!(lang.name(), "Lambda");
}

#[test]
fn lambda_metadata_populated() {
    let lang = LambdaLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_lambda_term_lam() {
    mettail_runtime::clear_var_cache();
    let term = Term::Lam(mettail_runtime::Scope::new(mettail_runtime::Binder(mettail_runtime::get_or_create_var("a")), Box::new(Term::TVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a")))))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Lam");
}

#[test]
fn unit_lambda_term_app() {
    mettail_runtime::clear_var_cache();
    let term = Term::App(Box::new(Term::TVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))), Box::new(Term::TVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for App");
    if let Ok(parsed) = Term::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for App: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_lambda_auto_term_tvar() {
    mettail_runtime::clear_var_cache();
    let term = Term::TVar(
        mettail_runtime::OrdVar(
            mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a")
            )
        )
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for TVar");
}

