// AUTO-GENERATED by language! macro for CommDemo (rewrite) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::commdemo::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Rewrite tests (one per rewrite rule)
// ═══════════════════════════════════════════════════════════

#[test]
fn rewrite_commdemo_comm() {
    let _lang = CommDemoLanguage;
    let meta = _lang.metadata();
    let rewrites = meta.rewrites();
    // Verify rewrite Comm (index 0) exists in metadata
    assert!(
        rewrites.len() > 0,
        "Expected at least 1 rewrites in metadata, found {}",
        rewrites.len()
    );
    let rw = &rewrites[0];
    // Verify rewrite rule name
    assert_eq!(rw.name, Some("Comm"), "Rewrite rule name mismatch");
    assert!(!rw.lhs.is_empty(), "Rewrite Comm LHS should be non-empty");
    assert!(!rw.rhs.is_empty(), "Rewrite Comm RHS should be non-empty");
}
