//! Designated host for the generated `Rholang` `unit` suite — HAND-WRITTEN.
//!
//! The suite itself is generated by the `language!` macro into
//! `target/generated/rholang/tests_unit.rs` and pulled in by the wrapper invoked
//! below. This file exists so cargo has a test target to discover, and it is where the
//! AUTHOR — not the macro — decides which sections get their own binary.
//!
//! One section per binary, deliberately. The no-selector form of the wrapper materializes
//! every section into a single binary, which is the shape that peaked at **96 GB RSS on a
//! 125 GB machine** for a language this size; see
//! `macros/src/gen/test_gen/mod.rs::write_test_file`. Small test-hosted definitions use
//! the no-selector form; `Rholang` must not.
//!
//! Adding a section to `Rholang` means adding a sibling of this file. Nothing regenerates
//! it, and nothing overwrites it.

mettail_languages::rholang_generated_tests!(section unit, mettail_languages::rholang);
