// AUTO-GENERATED by language! macro for BiCongDemo (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::bicongdemo::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn bicongdemo_language_instantiates() {
    let lang = BiCongDemoLanguage;
    assert_eq!(lang.name(), "BiCongDemo");
}

#[test]
fn bicongdemo_metadata_populated() {
    let lang = BiCongDemoLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_bicongdemo_proc_a() {
    let term = Proc::A;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for A");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for A: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_b() {
    let term = Proc::B;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for B");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for B: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_c() {
    let term = Proc::C;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for C");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for C: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_d() {
    let term = Proc::D;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for D");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for D: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_pair() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Pair(std::sync::Arc::new(Proc::A), std::sync::Arc::new(Proc::A));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Pair");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for Pair: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_swap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Swap(std::sync::Arc::new(Proc::A), std::sync::Arc::new(Proc::A));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Swap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for Swap: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_proc_node() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Node(std::sync::Arc::new(Proc::A), std::sync::Arc::new(Proc::A));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Node");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for Node: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_bicongdemo_auto_proc_pvar() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(
        mettail_runtime::get_or_create_var("a"),
    )));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PVar");
}
