// AUTO-GENERATED by language! macro for RhoCalc (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::rhocalc::*;
use mettail_runtime::Language;
use mettail_runtime::BehavioralPred;

// Dead rules detected by WFST analysis: {"Proc::FixedBinProc", "Proc::BigintCastProc", "CastInt", "BoolToInt", "Proc::BigratCastProc", "CastMap", "Proc::PNew", "Proc::GetMap", "Proc::MergeMap", "Proc::ConcatList", "Proc::PutMap", "CastBool", "Proc::UIntBinProc", "CastList", "Proc::ElemList", "Proc::DiffBag", "CastStr", "UInt32ToInt", "CastBag", "CastUInt32", "Proc::FractionProc", "Proc::Len", "Proc::UnionBag", "Proc::PDrop", "CastBigInt", "Proc::RemoveBag", "Proc::IntBinProc", "CastBigRat", "Proc::KeysMap", "Proc::DeleteMap", "Proc::ToBool", "Proc::PInputs", "Proc::POutput", "Int::CountBag", "Proc::FloatBinProc", "Proc::ValuesMap", "Proc::HasMap", "Proc::DeleteList", "Proc::ToStr"}

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn rhocalc_language_instantiates() {
    let lang = RhoCalcLanguage;
    assert_eq!(lang.name(), "RhoCalc");
}

#[test]
fn rhocalc_metadata_populated() {
    let lang = RhoCalcLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_rhocalc_proc_pzero() {
    let term = Proc::PZero;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PZero");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for PZero: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_pdrop() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PDrop(Box::new(Name::NVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PDrop");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for PDrop: {} != {}", displayed, re_displayed);
    }
}

// Skipped unit test for PPar (Proc) — constructor too complex to construct statically

#[test]
fn unit_rhocalc_proc_poutput() {
    mettail_runtime::clear_var_cache();
    let term = Proc::POutput(Box::new(Name::NVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for POutput");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for POutput: {} != {}", displayed, re_displayed);
    }
}

// Skipped unit test for PInputs (Proc) — constructor too complex to construct statically

#[test]
fn unit_rhocalc_name_nquote() {
    mettail_runtime::clear_var_cache();
    let term = Name::NQuote(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NQuote");
    if let Ok(parsed) = Name::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NQuote: {} != {}", displayed, re_displayed);
    }
}

// Skipped unit test for PNew (Proc) — constructor too complex to construct statically

#[test]
fn unit_rhocalc_proc_err() {
    let term = Proc::Err;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Err");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Err: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castbigrat() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastBigRat(Box::new(BigRat::RatLit(mettail_runtime::CanonicalBigRat::default())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastBigRat");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castfixed() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastFixed(Box::new(Fixed::FixedLit(mettail_runtime::CanonicalFixedPoint::default())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastFixed");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastFixed: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castfloat() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastFloat(Box::new(Float::FloatLit(mettail_runtime::CanonicalFloat64::from(0.0f64))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastFloat");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastFloat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castbigint() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastBigInt(Box::new(BigInt::NumLit(mettail_runtime::CanonicalBigInt::default())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastBigInt");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastBigInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castuint32() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastUInt32(Box::new(UInt32::NumLit(0u32)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastUInt32");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastUInt32: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castint() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastInt(Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastInt");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castbool() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastBool(Box::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastBool");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastBool: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_caststr() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastStr(Box::new(Str::StringLit(String::new())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastStr");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastStr: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castlist() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastList(Box::new(List::ListLit(Vec::new())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastList");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastList: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castbag() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastBag(Box::new(Bag::BagLit(mettail_runtime::HashBag::new())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastBag");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastBag: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_castmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastMap(Box::new(Map::MapLit(mettail_runtime::HashMapLit::new())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_intbinproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::IntBinProc(Box::new(Proc::PZero), Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for IntBinProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for IntBinProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_uintbinproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::UIntBinProc(Box::new(Proc::PZero), Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for UIntBinProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for UIntBinProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_floatbinproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::FloatBinProc(Box::new(Proc::PZero), Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FloatBinProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FloatBinProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_fixedbinproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::FixedBinProc(Box::new(Proc::PZero), Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FixedBinProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FixedBinProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_bigintcastproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::BigintCastProc(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BigintCastProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BigintCastProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_bigratcastproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::BigratCastProc(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BigratCastProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BigratCastProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_int_negint() {
    mettail_runtime::clear_var_cache();
    let term = Int::NegInt(Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NegInt");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NegInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_fractionproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::FractionProc(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FractionProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FractionProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_or() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Or(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Or");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Or: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_and() {
    mettail_runtime::clear_var_cache();
    let term = Proc::And(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for And");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for And: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_bitor() {
    mettail_runtime::clear_var_cache();
    let term = Proc::BitOr(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BitOr");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BitOr: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_bitand() {
    mettail_runtime::clear_var_cache();
    let term = Proc::BitAnd(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BitAnd");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BitAnd: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_bitnot() {
    mettail_runtime::clear_var_cache();
    let term = Proc::BitNot(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BitNot");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BitNot: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_eq() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Eq(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Eq");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Eq: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_ne() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Ne(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Ne");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Ne: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_gt() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Gt(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Gt");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Gt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_lt() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Lt(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Lt");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Lt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_gteq() {
    mettail_runtime::clear_var_cache();
    let term = Proc::GtEq(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for GtEq");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for GtEq: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_lteq() {
    mettail_runtime::clear_var_cache();
    let term = Proc::LtEq(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for LtEq");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for LtEq: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_add() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Add(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Add");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Add: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_sub() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Sub(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Sub");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Sub: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_mul() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Mul(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Mul");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Mul: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_div() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Div(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Div");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Div: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_mod() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Mod(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Mod");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Mod: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_negproc() {
    mettail_runtime::clear_var_cache();
    let term = Proc::NegProc(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NegProc");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NegProc: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_concatlist() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ConcatList(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ConcatList");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ConcatList: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_elemlist() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ElemList(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ElemList");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ElemList: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_deletelist() {
    mettail_runtime::clear_var_cache();
    let term = Proc::DeleteList(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for DeleteList");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for DeleteList: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_unionbag() {
    mettail_runtime::clear_var_cache();
    let term = Proc::UnionBag(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for UnionBag");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for UnionBag: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_removebag() {
    mettail_runtime::clear_var_cache();
    let term = Proc::RemoveBag(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for RemoveBag");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for RemoveBag: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_diffbag() {
    mettail_runtime::clear_var_cache();
    let term = Proc::DiffBag(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for DiffBag");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for DiffBag: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_int_countbag() {
    mettail_runtime::clear_var_cache();
    let term = Int::CountBag(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CountBag");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CountBag: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_getmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::GetMap(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for GetMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for GetMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_putmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PutMap(Box::new(Proc::PZero), Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PutMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for PutMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_deletemap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::DeleteMap(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for DeleteMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for DeleteMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_mergemap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::MergeMap(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for MergeMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for MergeMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_hasmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::HasMap(Box::new(Proc::PZero), Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for HasMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for HasMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_keysmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::KeysMap(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for KeysMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for KeysMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_valuesmap() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ValuesMap(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ValuesMap");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ValuesMap: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_not() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Not(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Not");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Not: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_len() {
    mettail_runtime::clear_var_cache();
    let term = Proc::Len(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for Len");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for Len: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_tobool() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ToBool(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ToBool");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ToBool: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_proc_tostr() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ToStr(Box::new(Proc::PZero));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ToStr");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ToStr: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_int_booltoint() {
    mettail_runtime::clear_var_cache();
    let term = Int::BoolToInt(Box::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolToInt");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BoolToInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_uint32_booltouint32() {
    mettail_runtime::clear_var_cache();
    let term = UInt32::BoolToUInt32(Box::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolToUInt32");
    if let Ok(parsed) = UInt32::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BoolToUInt32: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigint_booltobigint() {
    mettail_runtime::clear_var_cache();
    let term = BigInt::BoolToBigInt(Box::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolToBigInt");
    if let Ok(parsed) = BigInt::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BoolToBigInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_booltobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::BoolToBigRat(Box::new(Bool::BoolLit(false)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BoolToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigint_inttobigint() {
    mettail_runtime::clear_var_cache();
    let term = BigInt::IntToBigInt(Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for IntToBigInt");
    if let Ok(parsed) = BigInt::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for IntToBigInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_inttobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::IntToBigRat(Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for IntToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for IntToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_int_uint32toint() {
    mettail_runtime::clear_var_cache();
    let term = Int::UInt32ToInt(Box::new(UInt32::NumLit(0u32)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for UInt32ToInt");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for UInt32ToInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigint_uint32tobigint() {
    mettail_runtime::clear_var_cache();
    let term = BigInt::UInt32ToBigInt(Box::new(UInt32::NumLit(0u32)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for UInt32ToBigInt");
    if let Ok(parsed) = BigInt::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for UInt32ToBigInt: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_uint32tobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::UInt32ToBigRat(Box::new(UInt32::NumLit(0u32)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for UInt32ToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for UInt32ToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_floattobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::FloatToBigRat(Box::new(Float::FloatLit(mettail_runtime::CanonicalFloat64::from(0.0f64))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FloatToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FloatToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_biginttobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::BigIntToBigRat(Box::new(BigInt::NumLit(mettail_runtime::CanonicalBigInt::default())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BigIntToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BigIntToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_bigrat_fixedtobigrat() {
    mettail_runtime::clear_var_cache();
    let term = BigRat::FixedToBigRat(Box::new(Fixed::FixedLit(mettail_runtime::CanonicalFixedPoint::default())));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FixedToBigRat");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FixedToBigRat: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_proc_pvar() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PVar(
        mettail_runtime::OrdVar(
            mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a")
            )
        )
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PVar");
}

#[test]
fn unit_rhocalc_auto_name_nvar() {
    mettail_runtime::clear_var_cache();
    let term = Name::NVar(
        mettail_runtime::OrdVar(
            mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a")
            )
        )
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NVar");
}

#[test]
fn unit_rhocalc_auto_int_numlit() {
    let term = Int::NumLit(0i64);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_uint32_numlit() {
    let term = UInt32::NumLit(0u32);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = UInt32::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_bigint_numlit() {
    let term = BigInt::NumLit(mettail_runtime::CanonicalBigInt::default());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = BigInt::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_bigrat_ratlit() {
    let term = BigRat::RatLit(mettail_runtime::CanonicalBigRat::default());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for RatLit");
    if let Ok(parsed) = BigRat::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for RatLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_fixed_fixedlit() {
    let term = Fixed::FixedLit(mettail_runtime::CanonicalFixedPoint::default());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FixedLit");
    if let Ok(parsed) = Fixed::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FixedLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_float_floatlit() {
    let term = Float::FloatLit(mettail_runtime::CanonicalFloat64::from(0.0f64));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for FloatLit");
    if let Ok(parsed) = Float::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for FloatLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_bool_boollit() {
    let term = Bool::BoolLit(false);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BoolLit");
    if let Ok(parsed) = Bool::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BoolLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_str_stringlit() {
    let term = Str::StringLit(String::new());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for StringLit");
    if let Ok(parsed) = Str::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for StringLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_list_listlit() {
    let term = List::ListLit(Vec::new());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ListLit");
    if let Ok(parsed) = List::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for ListLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_bag_baglit() {
    let term = Bag::BagLit(mettail_runtime::HashBag::new());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for BagLit");
    if let Ok(parsed) = Bag::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for BagLit: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_rhocalc_auto_map_maplit() {
    let term = Map::MapLit(mettail_runtime::HashMapLit::new());
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for MapLit");
    if let Ok(parsed) = Map::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for MapLit: {} != {}", displayed, re_displayed);
    }
}

