// AUTO-GENERATED by language! macro for ImportedMath (rewrite) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::importedmath::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Rewrite tests (one per rewrite rule)
// ═══════════════════════════════════════════════════════════

// Rewrite test for AddCongL skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_addcongl() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for AddCongR skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_addcongr() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for SubCongL skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_subcongl() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for SubCongR skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_subcongr() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for DivCongL skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_divcongl() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}

// Rewrite test for DivCongR skipped: congruence rule (needs triggering context)
#[test]
fn rewrite_importedmath_divcongr() {
    let _lang = ImportedMathLanguage;
    // Congruence rules require a rewrite-triggering context to test.
    // They fire when their premise (S ~> T) is satisfied by another rewrite.
}
