// AUTO-GENERATED by language! macro for AcBagDemo (rewrite) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::acbagdemo::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Equation tests (one per equation)
// ═══════════════════════════════════════════════════════════

#[test]
fn equation_acbagdemo_markidem() {
    let _lang = AcBagDemoLanguage;
    let meta = _lang.metadata();
    let equations = meta.equations();
    // Verify equation MarkIdem (index 0) exists in metadata
    assert!(
        equations.len() > 0,
        "Expected at least 1 equations in metadata, found {}",
        equations.len()
    );
    let eq = &equations[0];
    assert!(!eq.lhs.is_empty(), "Equation MarkIdem LHS should be non-empty");
    assert!(!eq.rhs.is_empty(), "Equation MarkIdem RHS should be non-empty");
}

// ═══════════════════════════════════════════════════════════
// Rewrite tests (one per rewrite rule)
// ═══════════════════════════════════════════════════════════

#[test]
fn rewrite_acbagdemo_acbagstep() {
    let _lang = AcBagDemoLanguage;
    let meta = _lang.metadata();
    let rewrites = meta.rewrites();
    // Verify rewrite AcBagStep (index 0) exists in metadata
    assert!(
        rewrites.len() > 0,
        "Expected at least 1 rewrites in metadata, found {}",
        rewrites.len()
    );
    let rw = &rewrites[0];
    // Verify rewrite rule name
    assert_eq!(rw.name, Some("AcBagStep"), "Rewrite rule name mismatch");
    assert!(!rw.lhs.is_empty(), "Rewrite AcBagStep LHS should be non-empty");
    assert!(!rw.rhs.is_empty(), "Rewrite AcBagStep RHS should be non-empty");
}
