// AUTO-GENERATED by language! macro for Class3Opt (analytical) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::class3opt::*;
use mettail_runtime::Language;
use mettail_runtime::BehavioralPred;

// ═══════════════════════════════════════════════════════════
// Analytical tests (confluence, termination)
// ═══════════════════════════════════════════════════════════

// No rewrites defined — TRS analytical tests skipped.

// ═══════════════════════════════════════════════════════════
// User tests (from `tests { }` block)
// ═══════════════════════════════════════════════════════════

// No user tests defined for Class3Opt — `tests {}` block not yet supported in spec.

// ═══════════════════════════════════════════════════════════
// Program tests (from `program { }` blocks)
// ═══════════════════════════════════════════════════════════

// No program tests defined for Class3Opt — `program {}` blocks not yet supported in spec.

