// AUTO-GENERATED by language! macro for Class2OptSmoke (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::class2optsmoke::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn class2optsmoke_language_instantiates() {
    let lang = Class2OptSmokeLanguage;
    assert_eq!(lang.name(), "Class2OptSmoke");
}

#[test]
fn class2optsmoke_metadata_populated() {
    let lang = Class2OptSmokeLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_class2optsmoke_proc_pzero() {
    let term = Proc::PZero;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PZero");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for PZero: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_class2optsmoke_proc_choosemaybe() {
    mettail_runtime::clear_var_cache();
    let term = Proc::ChooseMaybe(std::sync::Arc::new(Proc::PZero), None);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for ChooseMaybe");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for ChooseMaybe: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_class2optsmoke_auto_proc_pvar() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(
        mettail_runtime::get_or_create_var("a"),
    )));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PVar");
}
