// AUTO-GENERATED by language! macro for GuardedRho (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::guardedrho::*;
use mettail_runtime::Language;
use mettail_runtime::BehavioralPred;

// Dead rules detected by WFST analysis: ["CastInt", "POutput"]

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn guardedrho_language_instantiates() {
    let lang = GuardedRhoLanguage;
    assert_eq!(lang.name(), "GuardedRho");
}

#[test]
fn guardedrho_metadata_populated() {
    let lang = GuardedRhoLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_guardedrho_proc_pnil() {
    let term = Proc::PNil;
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PNil");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for PNil: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_guardedrho_proc_castint() {
    mettail_runtime::clear_var_cache();
    let term = Proc::CastInt(Box::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for CastInt");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for CastInt: {} != {}", displayed, re_displayed);
    }
}

// Skipped unit test for PPar (Proc) — constructor too complex to construct statically

#[test]
fn unit_guardedrho_proc_poutput() {
    mettail_runtime::clear_var_cache();
    let term = Proc::POutput(Box::new(Name::NVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))), Box::new(Proc::PNil));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for POutput");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for POutput: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_guardedrho_proc_pguardedinput() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PGuardedInput(Box::new(Name::NVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))), mettail_runtime::BehavioralPred::Top, mettail_runtime::Scope::new(mettail_runtime::Binder(mettail_runtime::get_or_create_var("a")), Box::new(Proc::PNil)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PGuardedInput");
}

#[test]
fn unit_guardedrho_name_nquote() {
    mettail_runtime::clear_var_cache();
    let term = Name::NQuote(Box::new(Proc::PNil));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NQuote");
    if let Ok(parsed) = Name::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NQuote: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_guardedrho_proc_pdrop() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PDrop(Box::new(Name::NVar(mettail_runtime::OrdVar(mettail_runtime::Var::Free(mettail_runtime::get_or_create_var("a"))))));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PDrop");
    if let Ok(parsed) = Proc::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for PDrop: {} != {}", displayed, re_displayed);
    }
}

#[test]
fn unit_guardedrho_auto_proc_pvar() {
    mettail_runtime::clear_var_cache();
    let term = Proc::PVar(
        mettail_runtime::OrdVar(
            mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a")
            )
        )
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for PVar");
}

#[test]
fn unit_guardedrho_auto_name_nvar() {
    mettail_runtime::clear_var_cache();
    let term = Name::NVar(
        mettail_runtime::OrdVar(
            mettail_runtime::Var::Free(
                mettail_runtime::get_or_create_var("a")
            )
        )
    );
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NVar");
}

#[test]
fn unit_guardedrho_auto_int_numlit() {
    let term = Int::NumLit(0i64);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}", displayed, re_displayed);
    }
}

