// AUTO-GENERATED by language! macro for NativeFoldDemo (unit) — do not edit
// Regenerated on each compilation of the language definition.
// Run with: cargo test -p mettail-languages

#![allow(unused_imports, dead_code)]

use mettail_languages::nativefolddemo::*;
use mettail_runtime::BehavioralPred;
use mettail_runtime::Language;

// ═══════════════════════════════════════════════════════════
// Unit tests (one per constructor)
// ═══════════════════════════════════════════════════════════

#[test]
fn nativefolddemo_language_instantiates() {
    let lang = NativeFoldDemoLanguage;
    assert_eq!(lang.name(), "NativeFoldDemo");
}

#[test]
fn nativefolddemo_metadata_populated() {
    let lang = NativeFoldDemoLanguage;
    let meta = lang.metadata();
    assert!(!meta.types().is_empty(), "language should have at least one type");
    assert!(!meta.terms().is_empty(), "language should have at least one term");
}

#[test]
fn unit_nativefolddemo_int_addint() {
    mettail_runtime::clear_var_cache();
    let term =
        Int::AddInt(std::sync::Arc::new(Int::NumLit(0i64)), std::sync::Arc::new(Int::NumLit(0i64)));
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for AddInt");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for AddInt: {} != {}",
            displayed, re_displayed
        );
    }
}

#[test]
fn unit_nativefolddemo_auto_int_numlit() {
    let term = Int::NumLit(0i64);
    let displayed = format!("{}", term);
    assert!(!displayed.is_empty(), "Display should produce non-empty output for NumLit");
    if let Ok(parsed) = Int::parse(&displayed) {
        let re_displayed = format!("{}", parsed);
        assert_eq!(
            displayed, re_displayed,
            "Roundtrip failed for NumLit: {} != {}",
            displayed, re_displayed
        );
    }
}
