//! Host binary for the test-hosted `LambdaDemo` demonstration language.
//!
//! Stage 3c: the untyped λ-calculus binder/β-substitution demonstration.
//!
//! Task #11 (extended 2026-07-26): `LambdaDemo` is a DEMONSTRATION grammar, not a production
//! language, so its definition lives in `languages/tests/definitions/lambdademo.rs`, not in the
//! `languages` library — `languages/src/` is production-only.
//!
//! This file is its DESIGNATED HOST: it declares the definition module and is the one and only
//! invoker of the opt-in `lambdademo_generated_tests!` wrapper, which materializes the
//! macro-generated unit / prop / rewrite / analytical sections that used to be written to
//! `languages/tests/gen_lambdademo_*.rs`. Every other consumer (`rholang-runtime/tests/rho_net_beta_firing.rs`, `rho_net_naive_equivalence.rs`, `languages/tests/set_automaton_size_optimal.rs`, `rholang-runtime/benches/support/workloads.rs`)
//! `#[path]`-includes the same definition WITHOUT invoking the wrapper, so the generated tests
//! exist exactly once across the whole suite.

#[path = "definitions/lambdademo.rs"]
mod lambdademo;

lambdademo::lambdademo_generated_tests!(crate::lambdademo);

use lambdademo::Term;

/// Test-only mirror of the binder layout that the pre-PDA derived formatter
/// produced. Naming the mirror `Scope` and its fields `pattern`/`body` makes
/// `#[derive(Debug)]` an independent specification of the exact punctuation and
/// alternate indentation generated by the iterative formatter.
#[derive(Clone, Debug)]
struct Scope {
    pattern: mettail_runtime::Binder<String>,
    body: Box<TermDebugOracle>,
}

#[derive(Clone, Debug)]
enum TermDebugOracle {
    Lam(Scope),
    App(Box<TermDebugOracle>, Box<TermDebugOracle>),
    F(Box<TermDebugOracle>),
    A,
}

fn term_debug_oracle(term: &Term) -> TermDebugOracle {
    match term {
        Term::Lam(scope) => {
            let inner = scope.inner();
            TermDebugOracle::Lam(Scope {
                pattern: inner.unsafe_pattern.clone(),
                body: Box::new(term_debug_oracle(&inner.unsafe_body)),
            })
        },
        Term::App(function, argument) => TermDebugOracle::App(
            Box::new(term_debug_oracle(function)),
            Box::new(term_debug_oracle(argument)),
        ),
        Term::F(argument) => TermDebugOracle::F(Box::new(term_debug_oracle(argument))),
        Term::A => TermDebugOracle::A,
        other => panic!("LambdaDemo Debug oracle received an unsupported fixture shape: {other:?}"),
    }
}

#[test]
fn iterative_debug_matches_derive_for_binders_in_both_layouts() {
    for source in ["A", "f(A)", "(f(A), A)", "lam x.A", "lam x.f(A)", "lam x.lam y.(f(A), A)"] {
        let term = Term::parse_via_wpda(source).unwrap_or_else(|error| {
            panic!("Debug oracle fixture `{source}` failed to parse: {error}")
        });
        let oracle = term_debug_oracle(&term);

        assert_eq!(
            format!("{term:?}"),
            format!("{oracle:?}"),
            "compact generated Debug diverged from derive for `{source}`"
        );
        assert_eq!(
            format!("{term:#?}"),
            format!("{oracle:#?}"),
            "alternate generated Debug diverged from derive for `{source}`"
        );
    }
}
