//! Allocation/size ladder for the constant-size native shift call.
//!
//! This is a separate integration-test binary so its counting allocator does not weaken
//! `rholang-codegen`'s production `#![forbid(unsafe_code)]` boundary.

use std::alloc::{GlobalAlloc, Layout, System};
use std::cell::Cell;
use std::time::Instant;

use mettail_rholang_codegen::native_shift_call_par;
use models::rust::utils::new_boundvar_par;
use prost::Message;

mod counting_alloc {
    use super::*;

    thread_local! {
        static ALLOCATIONS: Cell<usize> = const { Cell::new(0) };
        static BYTES: Cell<usize> = const { Cell::new(0) };
    }

    fn bump(bytes: usize) {
        let _ = ALLOCATIONS.try_with(|count| count.set(count.get() + 1));
        let _ = BYTES.try_with(|count| count.set(count.get() + bytes));
    }

    fn read() -> (usize, usize) {
        (
            ALLOCATIONS.try_with(Cell::get).unwrap_or(0),
            BYTES.try_with(Cell::get).unwrap_or(0),
        )
    }

    pub struct Counting;

    unsafe impl GlobalAlloc for Counting {
        unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
            bump(layout.size());
            unsafe { System.alloc(layout) }
        }

        unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
            unsafe { System.dealloc(ptr, layout) }
        }

        unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, size: usize) -> *mut u8 {
            bump(size);
            unsafe { System.realloc(ptr, layout, size) }
        }
    }

    pub fn measure<R>(f: impl FnOnce() -> R) -> (R, usize, usize) {
        let (allocations_before, bytes_before) = read();
        let result = f();
        let (allocations_after, bytes_after) = read();
        (result, allocations_after - allocations_before, bytes_after - bytes_before)
    }
}

#[global_allocator]
static ALLOCATOR: counting_alloc::Counting = counting_alloc::Counting;

fn addressed_call(depth: usize) -> models::rhoapi::Par {
    native_shift_call_par(
        "shift-profile",
        depth,
        new_boundvar_par(0, models::create_bit_vector(&[0]), false),
        new_boundvar_par(1, models::create_bit_vector(&[1]), false),
    )
}

#[test]
fn depth_ladder_has_constant_size_and_allocation_cost() {
    drop(addressed_call(1));

    let mut baseline = None;
    println!("depth,protobuf_bytes,allocations,allocated_bytes,elapsed_ns");
    for depth in [1usize, 10, 100, 1_000, 10_000, 20_000] {
        let started = Instant::now();
        let (call, allocations, allocated_bytes) =
            counting_alloc::measure(|| addressed_call(depth));
        let elapsed = started.elapsed();
        let protobuf_bytes = call.encode_to_vec().len();
        println!(
            "{depth},{protobuf_bytes},{allocations},{allocated_bytes},{}",
            elapsed.as_nanos()
        );
        let row = (protobuf_bytes, allocations, allocated_bytes);
        match baseline {
            None => baseline = Some(row),
            Some(expected) => assert_eq!(
                row, expected,
                "binder depth must not affect generated bytes or construction allocation"
            ),
        }
    }
}
