//! Rho-default backend planning.
//!
//! `RhoBackendFlipGate.v` proves the Boolean gate. This module is the Rust-side
//! artifact that a runtime selector can consume: it lowers a `LanguageDef`,
//! checks proof/oracle/coverage/artifact-validation/scheduler-fairness/deadlock
//! evidence, and either returns a concrete Rho-default backend plan or all
//! blockers.

use std::collections::BTreeSet;

use mettail_ast::language::LanguageDef;
use models::rhoapi::Par;

use crate::flip::{decide_rho_flip, RhoFlipDecision, RhoFlipGates};
use crate::lower::{lower_language_def, RhoLowering};
use crate::validate::{RhoValidationError, ValidatedRhoProgram};

/// Runtime disposition kind for a rule not lowered by the scalar Rho AST
/// generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RhoRejectedRuleDispositionKind {
    /// Covered by a verified native system process or host-side handler.
    NativeHandler,
    /// Covered by a verified external contract supplied by the host runtime.
    ExternalContract,
    /// Covered by a non-scalar Rho AST contract generated by another lowering.
    RhoAstContract,
}

/// Auditable coverage for one rule that `lower_language_def` recorded as
/// rejected by this scalar lowering family.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoRejectedRuleDisposition {
    pub rule: String,
    pub kind: RhoRejectedRuleDispositionKind,
    /// Stable reference to the proof/oracle/contract artifact that justifies
    /// the disposition. Empty or whitespace-only references are rejected.
    pub evidence_ref: String,
}

impl RhoRejectedRuleDisposition {
    pub fn new(
        rule: impl Into<String>,
        kind: RhoRejectedRuleDispositionKind,
        evidence_ref: impl Into<String>,
    ) -> Self {
        Self {
            rule: rule.into(),
            kind,
            evidence_ref: evidence_ref.into(),
        }
    }
}

/// Invalid rejected-rule coverage diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoRejectedRuleDispositionDiagnostic {
    MissingRuleId,
    MissingEvidenceRef { rule: String },
    DuplicateRuleDisposition { rule: String },
}

/// Coverage evidence for rules not lowered by the scalar Rho AST generator.
///
/// A default Rho backend may not ignore `RhoLowering::rejected`. Either every
/// rule lowered to Rholang AST, or every rejected rule is covered by an
/// explicit external/native/Rho handler contract that passed the separate
/// coverage audit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoCoverageEvidence {
    /// The backend is acceptable only when `RhoLowering::rejected` is empty.
    AllRulesLowered,
    /// Rejected rules are acceptable only when these auditable dispositions
    /// name exactly the rejected rule set and every disposition is well-formed.
    CoveredRejectedRules(Vec<RhoRejectedRuleDisposition>),
}

impl RhoCoverageEvidence {
    fn covered_dispositions(&self) -> &[RhoRejectedRuleDisposition] {
        match self {
            Self::AllRulesLowered => &[],
            Self::CoveredRejectedRules(dispositions) => dispositions,
        }
    }

    fn covered_set(&self) -> BTreeSet<&str> {
        match self {
            Self::AllRulesLowered => BTreeSet::new(),
            Self::CoveredRejectedRules(dispositions) => dispositions
                .iter()
                .map(|disposition| disposition.rule.as_str())
                .collect(),
        }
    }

    fn uncovered_rejections(&self, lowering: &RhoLowering) -> Vec<String> {
        let covered = self.covered_set();
        lowering
            .rejected
            .iter()
            .filter(|rule| !covered.contains(rule.as_str()))
            .cloned()
            .collect()
    }

    fn extraneous_dispositions(&self, lowering: &RhoLowering) -> Vec<String> {
        let rejected: BTreeSet<&str> = lowering.rejected.iter().map(String::as_str).collect();
        self.covered_set()
            .into_iter()
            .filter(|rule| !rejected.contains(rule))
            .map(ToOwned::to_owned)
            .collect()
    }

    fn invalid_dispositions(&self) -> Vec<RhoRejectedRuleDispositionDiagnostic> {
        let mut diagnostics = Vec::new();
        let mut seen = BTreeSet::new();
        let mut duplicate_reported = BTreeSet::new();

        for disposition in self.covered_dispositions() {
            if disposition.rule.trim().is_empty() {
                diagnostics.push(RhoRejectedRuleDispositionDiagnostic::MissingRuleId);
            } else if !seen.insert(disposition.rule.as_str())
                && duplicate_reported.insert(disposition.rule.as_str())
            {
                diagnostics.push(RhoRejectedRuleDispositionDiagnostic::DuplicateRuleDisposition {
                    rule: disposition.rule.clone(),
                });
            }

            if disposition.evidence_ref.trim().is_empty() {
                diagnostics.push(RhoRejectedRuleDispositionDiagnostic::MissingEvidenceRef {
                    rule: disposition.rule.clone(),
                });
            }
        }

        diagnostics
    }

    fn exactly_covers(&self, lowering: &RhoLowering) -> bool {
        self.uncovered_rejections(lowering).is_empty()
            && self.extraneous_dispositions(lowering).is_empty()
            && self.invalid_dispositions().is_empty()
    }

    fn accepted_dispositions(&self) -> Vec<RhoRejectedRuleDisposition> {
        match self {
            Self::AllRulesLowered => Vec::new(),
            Self::CoveredRejectedRules(dispositions) => dispositions.clone(),
        }
    }
}

/// Evidence inputs for selecting Rho as a language's default runtime backend.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoDefaultBackendEvidence {
    pub proofs_passed: bool,
    pub oracle_parity_passed: bool,
    pub coverage_audit_passed: bool,
    pub scheduler_fairness_passed: bool,
    pub coverage: RhoCoverageEvidence,
}

/// Concrete plan for a language that passed the Rho-default flip gate.
#[derive(Debug, Clone, PartialEq)]
pub struct RhoDefaultBackendPlan {
    pub lowering: RhoLowering,
    pub validated_program: ValidatedRhoProgram,
    pub rejected_rule_dispositions: Vec<RhoRejectedRuleDisposition>,
}

impl RhoDefaultBackendPlan {
    /// Executable Rho backend artifact selected and validated by the flip gate.
    pub fn program(&self) -> &ValidatedRhoProgram {
        &self.validated_program
    }

    /// Normalized AST to inject into the host Rho runtime, when available.
    pub fn ast_par(&self) -> Option<&Par> {
        self.program().ast_par()
    }

    /// Reader/debug annotation. This text is not parsed as the execution path.
    pub fn text_annotation(&self) -> &str {
        self.program().text_annotation()
    }
}

/// Rejected Rho-default plan with complete diagnostic state for callers.
#[derive(Debug, Clone, PartialEq)]
pub struct RhoDefaultBackendPlanError {
    pub lowering: Box<RhoLowering>,
    pub decision: RhoFlipDecision,
    pub uncovered_rejections: Vec<String>,
    pub extraneous_dispositions: Vec<String>,
    pub invalid_dispositions: Vec<RhoRejectedRuleDispositionDiagnostic>,
    pub validation_errors: Vec<RhoValidationError>,
}

/// Lower `def` and build the Rho-default backend plan if every flip gate passes.
pub fn plan_rho_default_backend(
    def: &LanguageDef,
    evidence: RhoDefaultBackendEvidence,
) -> Result<RhoDefaultBackendPlan, RhoDefaultBackendPlanError> {
    let lowering = lower_language_def(def);
    let validated_program = ValidatedRhoProgram::try_from(lowering.program.clone());
    let validation_errors = validated_program.clone().err().unwrap_or_default();
    let uncovered_rejections = evidence.coverage.uncovered_rejections(&lowering);
    let extraneous_dispositions = evidence.coverage.extraneous_dispositions(&lowering);
    let invalid_dispositions = evidence.coverage.invalid_dispositions();
    let coverage_passed =
        evidence.coverage_audit_passed && evidence.coverage.exactly_covers(&lowering);
    let decision = decide_rho_flip(
        RhoFlipGates {
            proofs_passed: evidence.proofs_passed,
            oracle_parity_passed: evidence.oracle_parity_passed,
            coverage_passed,
            artifact_validated: validation_errors.is_empty(),
            scheduler_fairness_passed: evidence.scheduler_fairness_passed,
        },
        &lowering.deadlock_report,
    );

    if decision.can_flip_to_rho() {
        Ok(RhoDefaultBackendPlan {
            rejected_rule_dispositions: evidence.coverage.accepted_dispositions(),
            validated_program: validated_program
                .expect("flip decision requires successful artifact validation"),
            lowering,
        })
    } else {
        Err(RhoDefaultBackendPlanError {
            lowering: Box::new(lowering),
            decision,
            uncovered_rejections,
            extraneous_dispositions,
            invalid_dispositions,
            validation_errors,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::flip::RhoFlipBlocker;

    const ALL_LOWERED_FRAGMENT: &str = r#"
        name: CalcAllLowered,
        types { Proc }
        terms {
            AddInt . a:Int, b:Int |- a "+" b : Int ;
            SubInt . a:Int, b:Int |- a "-" b : Int ;
            Neg . a:Int |- "-" a : Int ;
        }
    "#;

    const PARTIAL_FRAGMENT: &str = r#"
        name: CalcPartial,
        types { Proc }
        terms {
            AddInt . a:Int, b:Int |- a "+" b : Int ;
            PowInt . a:Int, b:Int |- a "^" b : Int ;
            AddBigInt . a:BigInt, b:BigInt |- a "+" b : BigInt ;
        }
    "#;

    fn parse(src: &str) -> LanguageDef {
        syn::parse_str::<LanguageDef>(src).expect("test fragment must parse")
    }

    fn passing_evidence(coverage: RhoCoverageEvidence) -> RhoDefaultBackendEvidence {
        RhoDefaultBackendEvidence {
            proofs_passed: true,
            oracle_parity_passed: true,
            coverage_audit_passed: true,
            scheduler_fairness_passed: true,
            coverage,
        }
    }

    fn native_disposition(rule: &str) -> RhoRejectedRuleDisposition {
        RhoRejectedRuleDisposition::new(
            rule,
            RhoRejectedRuleDispositionKind::NativeHandler,
            format!("native-handler:{rule}"),
        )
    }

    #[test]
    fn default_backend_plan_succeeds_when_all_rules_lower() {
        let plan = plan_rho_default_backend(
            &parse(ALL_LOWERED_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::AllRulesLowered),
        )
        .expect("all-lowered fragment should pass the default-backend gate");

        assert_eq!(plan.lowering.lowered, vec!["AddInt", "SubInt", "Neg"]);
        assert_eq!(plan.lowering.rejected, Vec::<String>::new());
        assert_eq!(plan.rejected_rule_dispositions, Vec::new());
        assert_eq!(plan.ast_par().expect("plan must carry AST").receives.len(), 3);
        assert!(plan.text_annotation().contains("contract @\"AddInt\""));
    }

    #[test]
    fn default_backend_plan_blocks_uncovered_rejections() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::AllRulesLowered),
        )
        .expect_err("uncovered rejected rules must block Rho default");

        assert_eq!(err.uncovered_rejections, vec!["PowInt", "AddBigInt"]);
        assert_eq!(err.extraneous_dispositions, Vec::<String>::new());
        assert_eq!(err.invalid_dispositions, Vec::new());
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_accepts_exact_covered_rejections() {
        let plan = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
            ])),
        )
        .expect("explicitly covered rejected rules may pass the default-backend gate");

        assert_eq!(plan.lowering.lowered, vec!["AddInt"]);
        assert_eq!(plan.lowering.rejected, vec!["PowInt", "AddBigInt"]);
        assert_eq!(
            plan.rejected_rule_dispositions,
            vec![native_disposition("PowInt"), native_disposition("AddBigInt")]
        );
    }

    #[test]
    fn default_backend_plan_rejects_stale_disposition_claims() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
                native_disposition("MissingRule"),
            ])),
        )
        .expect_err("coverage evidence must exactly match rejected rules");

        assert_eq!(err.uncovered_rejections, Vec::<String>::new());
        assert_eq!(err.extraneous_dispositions, vec!["MissingRule"]);
        assert_eq!(err.invalid_dispositions, Vec::new());
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_rejects_inauditable_dispositions() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                RhoRejectedRuleDisposition::new(
                    "AddBigInt",
                    RhoRejectedRuleDispositionKind::NativeHandler,
                    "   ",
                ),
            ])),
        )
        .expect_err("blank evidence refs must block the default-backend gate");

        assert_eq!(err.uncovered_rejections, Vec::<String>::new());
        assert_eq!(err.extraneous_dispositions, Vec::<String>::new());
        assert_eq!(
            err.invalid_dispositions,
            vec![RhoRejectedRuleDispositionDiagnostic::MissingEvidenceRef {
                rule: "AddBigInt".to_string()
            }]
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_rejects_duplicate_dispositions() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_evidence(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
                native_disposition("AddBigInt"),
            ])),
        )
        .expect_err("duplicate disposition claims must block the default-backend gate");

        assert_eq!(err.uncovered_rejections, Vec::<String>::new());
        assert_eq!(err.extraneous_dispositions, Vec::<String>::new());
        assert_eq!(
            err.invalid_dispositions,
            vec![RhoRejectedRuleDispositionDiagnostic::DuplicateRuleDisposition {
                rule: "AddBigInt".to_string()
            }]
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_reports_all_non_coverage_gate_failures() {
        let err = plan_rho_default_backend(
            &parse(ALL_LOWERED_FRAGMENT),
            RhoDefaultBackendEvidence {
                proofs_passed: false,
                oracle_parity_passed: false,
                coverage_audit_passed: true,
                scheduler_fairness_passed: false,
                coverage: RhoCoverageEvidence::AllRulesLowered,
            },
        )
        .expect_err("missing proof and oracle gates must block Rho default");

        assert_eq!(err.uncovered_rejections, Vec::<String>::new());
        assert_eq!(err.invalid_dispositions, Vec::new());
        assert_eq!(
            err.decision.blockers,
            vec![
                RhoFlipBlocker::Proofs,
                RhoFlipBlocker::OracleParity,
                RhoFlipBlocker::SchedulerFairness
            ]
        );
    }
}
