//! Rho-default backend planning.
//!
//! `RhoBackendFlipGate.v` proves the Boolean gate. This module is the Rust-side
//! planner that a runtime selector can consume: it lowers a `LanguageDef`,
//! checks exact coverage, artifact validation, and deadlock diagnostics, and
//! either returns a concrete Rho-default backend plan or all blockers.

use std::collections::{BTreeSet, HashMap, HashSet};

use mettail_ast::grammar::{GrammarItem, GrammarRule, SyntaxExpr, TermParam};
use mettail_ast::language::{BehavioralPred, GuardConfig, LanguageDef, Premise, RewriteRule};
use mettail_ast::types::TypeExpr;
use models::rhoapi::Par;

use crate::flip::{decide_rho_flip, RhoFlipBlocker, RhoFlipDecision, RhoFlipGates};
use crate::guard_quality::{derive_guard_qualities, RhoGuardDispositionQuality};
use crate::lower::{lower_language_def, RhoLowering};
use crate::validate::{RhoValidationError, ValidatedRhoProgram};

/// Runtime disposition kind for a rule not lowered by the scalar Rho AST
/// generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RhoRejectedRuleDispositionKind {
    /// Covered by a verified native system process or host-side handler.
    NativeHandler,
    /// Covered by a verified external contract supplied by the host runtime.
    ExternalContract,
    /// Covered by a non-scalar Rho AST contract generated by another lowering.
    RhoAstContract,
}

/// Class of predicated-type / guard obligation induced by a `LanguageDef`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RhoGuardObligationKind {
    /// Runtime predicate over matched values, facts, channels, or named
    /// predicate relations.
    BehavioralPredicate,
    /// Structural pattern predicate such as AC matching, binding shape, or
    /// guarded rewrite pattern structure.
    StructuralPattern,
    /// Registered predicate theory that must supply an effective Boolean
    /// algebra or an equivalent verified theory adapter.
    TheoryRegistration,
    /// Rho-native guarded receive/join/channel scheduling obligation.
    RhoNativeJoin,
}

/// One guard/predicated-type obligation that must be covered before the Rho
/// backend may become the default runtime for a language.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RhoGuardObligation {
    pub id: String,
    pub kind: RhoGuardObligationKind,
}

impl RhoGuardObligation {
    fn new(id: impl Into<String>, kind: RhoGuardObligationKind) -> Self {
        Self { id: id.into(), kind }
    }
}

/// Disposition kind for a guard/predicated-type obligation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RhoGuardDispositionKind {
    /// Covered directly by Dovetail's structural rewrite/pattern semantics.
    DovetailCoreStructural,
    /// Covered by an effective Boolean algebra / symbolic automata theory.
    EffectiveBooleanAlgebra,
    /// Covered by a symbolic finite-state transducer whose output semantics are
    /// part of the associated verification commentary.
    SymbolicFiniteTransducer,
    /// Covered by a Rho-native guarded join / RSpace atomic continuation.
    RhoNativeJoin,
    /// Covered by a verified native host handler.
    NativeHandler,
    /// Covered by an externally supplied verified contract.
    ExternalContract,
}

/// Coverage disposition for one guard/predicated-type obligation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoGuardDisposition {
    pub obligation: String,
    pub kind: RhoGuardDispositionKind,
}

impl RhoGuardDisposition {
    pub fn new(obligation: impl Into<String>, kind: RhoGuardDispositionKind) -> Self {
        Self { obligation: obligation.into(), kind }
    }
}

/// Invalid guard-obligation coverage diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoGuardDispositionDiagnostic {
    MissingObligationId,
    DuplicateObligationDisposition {
        obligation: String,
    },
    IncompatibleDisposition {
        obligation: String,
        obligation_kind: RhoGuardObligationKind,
        disposition_kind: RhoGuardDispositionKind,
    },
}

/// Coverage evidence for all guard/predicated-type obligations induced by a
/// `LanguageDef`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoGuardCoverageEvidence {
    /// Accept only languages whose `LanguageDef` induces no guard obligations.
    NoGuardObligations,
    /// Accept only when these dispositions exactly cover the induced obligation
    /// set and every disposition is compatible with its obligation kind.
    CoveredGuardObligations(Vec<RhoGuardDisposition>),
}

impl RhoGuardCoverageEvidence {
    fn covered_dispositions(&self) -> &[RhoGuardDisposition] {
        match self {
            Self::NoGuardObligations => &[],
            Self::CoveredGuardObligations(dispositions) => dispositions,
        }
    }

    fn covered_set(&self) -> BTreeSet<&str> {
        match self {
            Self::NoGuardObligations => BTreeSet::new(),
            Self::CoveredGuardObligations(dispositions) => dispositions
                .iter()
                .map(|disposition| disposition.obligation.as_str())
                .collect(),
        }
    }

    fn uncovered_obligations(&self, obligations: &[RhoGuardObligation]) -> Vec<String> {
        let covered = self.covered_set();
        obligations
            .iter()
            .filter(|obligation| !covered.contains(obligation.id.as_str()))
            .map(|obligation| obligation.id.clone())
            .collect()
    }

    fn extraneous_dispositions(&self, obligations: &[RhoGuardObligation]) -> Vec<String> {
        let expected: BTreeSet<&str> = obligations
            .iter()
            .map(|obligation| obligation.id.as_str())
            .collect();
        self.covered_set()
            .into_iter()
            .filter(|obligation| !expected.contains(obligation))
            .map(ToOwned::to_owned)
            .collect()
    }

    fn invalid_dispositions(
        &self,
        obligations: &[RhoGuardObligation],
    ) -> Vec<RhoGuardDispositionDiagnostic> {
        let mut diagnostics = Vec::new();
        let mut seen = BTreeSet::new();
        let mut duplicate_reported = BTreeSet::new();
        let obligation_kinds = obligations
            .iter()
            .map(|obligation| (obligation.id.as_str(), obligation.kind))
            .collect::<HashMap<_, _>>();

        for disposition in self.covered_dispositions() {
            if disposition.obligation.trim().is_empty() {
                diagnostics.push(RhoGuardDispositionDiagnostic::MissingObligationId);
            } else if !seen.insert(disposition.obligation.as_str())
                && duplicate_reported.insert(disposition.obligation.as_str())
            {
                diagnostics.push(RhoGuardDispositionDiagnostic::DuplicateObligationDisposition {
                    obligation: disposition.obligation.clone(),
                });
            }

            if let Some(obligation_kind) = obligation_kinds.get(disposition.obligation.as_str()) {
                if !guard_disposition_covers(*obligation_kind, disposition.kind) {
                    diagnostics.push(RhoGuardDispositionDiagnostic::IncompatibleDisposition {
                        obligation: disposition.obligation.clone(),
                        obligation_kind: *obligation_kind,
                        disposition_kind: disposition.kind,
                    });
                }
            }
        }

        diagnostics
    }

    fn exactly_covers(&self, obligations: &[RhoGuardObligation]) -> bool {
        self.uncovered_obligations(obligations).is_empty()
            && self.extraneous_dispositions(obligations).is_empty()
            && self.invalid_dispositions(obligations).is_empty()
    }

    fn accepted_dispositions(&self) -> Vec<RhoGuardDisposition> {
        match self {
            Self::NoGuardObligations => Vec::new(),
            Self::CoveredGuardObligations(dispositions) => dispositions.clone(),
        }
    }
}

/// Whether a disposition mechanism is compatible with an obligation kind — the
/// coverage compatibility matrix consumed by the fail-closed evidence gate.
/// Exposed so the predicate substrate ([`crate::guard_quality`]) can verify the
/// dispositions it emits are gate-compatible before lowering.
pub fn guard_disposition_covers(
    obligation_kind: RhoGuardObligationKind,
    disposition_kind: RhoGuardDispositionKind,
) -> bool {
    use RhoGuardDispositionKind::{
        DovetailCoreStructural, EffectiveBooleanAlgebra, ExternalContract, NativeHandler,
        RhoNativeJoin, SymbolicFiniteTransducer,
    };
    use RhoGuardObligationKind::{
        BehavioralPredicate, RhoNativeJoin as RhoNativeJoinObligation, StructuralPattern,
        TheoryRegistration,
    };

    match obligation_kind {
        BehavioralPredicate => matches!(
            disposition_kind,
            EffectiveBooleanAlgebra
                | SymbolicFiniteTransducer
                | RhoNativeJoin
                | NativeHandler
                | ExternalContract
        ),
        StructuralPattern => matches!(
            disposition_kind,
            DovetailCoreStructural
                | SymbolicFiniteTransducer
                | RhoNativeJoin
                | NativeHandler
                | ExternalContract
        ),
        TheoryRegistration => matches!(
            disposition_kind,
            EffectiveBooleanAlgebra | SymbolicFiniteTransducer | NativeHandler | ExternalContract
        ),
        RhoNativeJoinObligation => {
            matches!(disposition_kind, RhoNativeJoin | NativeHandler | ExternalContract)
        },
    }
}

fn pred_has_structural_component(pred: &BehavioralPred) -> bool {
    match pred {
        BehavioralPred::AcMatch { .. } => true,
        BehavioralPred::Quantified { body, .. } | BehavioralPred::Not(body) => {
            pred_has_structural_component(body)
        },
        BehavioralPred::And(left, right)
        | BehavioralPred::Or(left, right)
        | BehavioralPred::Implies(left, right) => {
            pred_has_structural_component(left) || pred_has_structural_component(right)
        },
        BehavioralPred::RelationQuery { .. } | BehavioralPred::Top => false,
    }
}

fn guard_pred_obligation_kind(pred: &BehavioralPred) -> RhoGuardObligationKind {
    if pred_has_structural_component(pred) {
        RhoGuardObligationKind::StructuralPattern
    } else {
        RhoGuardObligationKind::BehavioralPredicate
    }
}

fn collect_term_guard_obligations(rule: &GrammarRule, out: &mut BTreeSet<RhoGuardObligation>) {
    fn walk_params(label: &str, params: &[TermParam], out: &mut BTreeSet<RhoGuardObligation>) {
        for param in params {
            match param {
                TermParam::GuardBody { name } => {
                    out.insert(RhoGuardObligation::new(
                        format!("term:{label}:guard:{name}"),
                        RhoGuardObligationKind::BehavioralPredicate,
                    ));
                },
                TermParam::Optional { params } => walk_params(label, params, out),
                TermParam::Simple { .. }
                | TermParam::Abstraction { .. }
                | TermParam::MultiAbstraction { .. } => {},
            }
        }
    }

    if let Some(params) = rule.term_context.as_ref() {
        walk_params(&rule.label.to_string(), params, out);
    }
}

fn collect_premise_guard_obligations(
    owner_kind: &str,
    owner_name: &str,
    premises: &[Premise],
    out: &mut BTreeSet<RhoGuardObligation>,
) {
    fn walk(
        owner_kind: &str,
        owner_name: &str,
        premise: &Premise,
        index: usize,
        out: &mut BTreeSet<RhoGuardObligation>,
    ) {
        match premise {
            Premise::BehavioralGuard(pred) => {
                out.insert(RhoGuardObligation::new(
                    format!("{owner_kind}:{owner_name}:guard:{index}"),
                    guard_pred_obligation_kind(pred),
                ));
            },
            Premise::ForAll { body, .. } => walk(owner_kind, owner_name, body, index, out),
            Premise::Freshness(_)
            | Premise::Congruence { .. }
            | Premise::RelationQuery { .. }
            | Premise::SyntheticInjGuard { .. } => {},
        }
    }

    for (index, premise) in premises.iter().enumerate() {
        walk(owner_kind, owner_name, premise, index, out);
    }
}

fn collect_rewrite_guard_obligations(
    rewrite: &RewriteRule,
    out: &mut BTreeSet<RhoGuardObligation>,
) {
    collect_premise_guard_obligations("rewrite", &rewrite.name.to_string(), &rewrite.premises, out);
}

fn collect_guard_config_obligations(
    guard_config: &GuardConfig,
    out: &mut BTreeSet<RhoGuardObligation>,
) {
    match guard_config.builtin_predicates.as_ref() {
        Some(predicates) => {
            for predicate in predicates {
                out.insert(RhoGuardObligation::new(
                    format!("predicate:{}", predicate.name),
                    RhoGuardObligationKind::BehavioralPredicate,
                ));
            }
        },
        None => {
            out.insert(RhoGuardObligation::new(
                "predicate:standard-builtins",
                RhoGuardObligationKind::BehavioralPredicate,
            ));
        },
    }

    for theory in &guard_config.theories {
        out.insert(RhoGuardObligation::new(
            format!("theory:{}", theory.name),
            RhoGuardObligationKind::TheoryRegistration,
        ));
    }

    if let Some(channels) = guard_config.channels.as_ref() {
        for channel in &channels.channel_categories {
            out.insert(RhoGuardObligation::new(
                format!("channel:{}", channel.category),
                RhoGuardObligationKind::RhoNativeJoin,
            ));
        }
        for join in &channels.join_patterns {
            out.insert(RhoGuardObligation::new(
                format!("join:{}", join.label),
                RhoGuardObligationKind::RhoNativeJoin,
            ));
        }
    }
}

/// Collect the exact guard/predicated-type obligation set induced by a
/// `LanguageDef`.
pub fn collect_guard_obligations(def: &LanguageDef) -> Vec<RhoGuardObligation> {
    let mut obligations = BTreeSet::new();

    if let Some(guard_config) = def.guard_config.as_ref() {
        collect_guard_config_obligations(guard_config, &mut obligations);
    }

    for rule in &def.terms {
        collect_term_guard_obligations(rule, &mut obligations);
    }
    for equation in &def.equations {
        collect_premise_guard_obligations(
            "equation",
            &equation.name.to_string(),
            &equation.premises,
            &mut obligations,
        );
    }
    for rewrite in &def.rewrites {
        collect_rewrite_guard_obligations(rewrite, &mut obligations);
    }

    obligations.into_iter().collect()
}

/// The fail-closed guard-quality blockers for a set of substrate-derived
/// quality-tagged dispositions: one [`RhoFlipBlocker::GuardQuality`] per
/// obligation whose [`RhoGuardQuality`](crate::guard_quality::RhoGuardQuality)
/// refuses production-default lowering (i.e. `Unknown`).
///
/// This is the live consumption of the predicate-substrate quality classifier
/// ([`derive_guard_qualities`]): the planner derives qualities for the covered
/// guard obligations and folds these blockers into the flip gate, enforcing the
/// doc-08 rule "`Unknown` quality ⇒ production-default refused". For all current
/// languages `derive_guard_qualities` never yields `Unknown` (proven by
/// `default_classification` + the `default_quality_per_obligation_kind` test),
/// so this returns an empty vector — the wiring is real and fail-closed without
/// changing behavior for the existing obligation kinds.
pub fn guard_quality_blockers_for(qualities: &[RhoGuardDispositionQuality]) -> Vec<RhoFlipBlocker> {
    qualities
        .iter()
        .filter(|disposition| disposition.quality.refuses_production_default())
        .map(|disposition| RhoFlipBlocker::GuardQuality {
            obligation: disposition.obligation.clone(),
            quality: disposition.quality,
        })
        .collect()
}

/// Coverage for one rule that `lower_language_def` recorded as
/// rejected by this scalar lowering family.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoRejectedRuleDisposition {
    pub rule: String,
    pub kind: RhoRejectedRuleDispositionKind,
}

impl RhoRejectedRuleDisposition {
    pub fn new(rule: impl Into<String>, kind: RhoRejectedRuleDispositionKind) -> Self {
        Self { rule: rule.into(), kind }
    }
}

/// Why the planner suggested a disposition for a rejected rule.
///
/// These reasons are derived from the parsed `LanguageDef`; they are not a
/// replacement for verification. A suggestion helps generated tooling avoid
/// brittle hard-coded category lists, while the default-backend gate still
/// requires exact coverage through [`RhoCoverageEvidence`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RhoRejectedRuleClassificationReason {
    /// The rule carries user Rust evaluation code or an explicit HOL fold/step
    /// mode, so it belongs behind a verified native handler boundary.
    NativeEvaluation,
    /// The rejected constructor is mentioned by an equation or rewrite pattern,
    /// so it participates in non-scalar source semantics that need a Rho AST
    /// contract rather than scalar expression lowering.
    ReferencedByEquationOrRewrite,
    /// The rule contains binding, higher-order, collection, optional, guard, or
    /// syntax-operation structure that cannot be represented as one scalar
    /// Rholang expression contract.
    StructuredSyntax,
    /// The rule has scalar-operator shape but no exact scalar Rholang
    /// expression lowering. A host/runtime contract may still cover it.
    UnsupportedScalarOperator,
    /// The rule is a plain constructor outside the scalar-expression lowering
    /// subset. It is a candidate for generated Rho AST structural handling.
    StructuralConstructor,
    /// The rejected label did not correspond to a `LanguageDef::terms` rule.
    /// This should not happen for `lower_language_def`, but keeping it explicit
    /// makes stale lowering data visible to callers.
    MissingLanguageRule,
}

/// Advisory, `LanguageDef`-derived classification for a rule rejected by the
/// scalar lowering family.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoRejectedRuleClassification {
    pub rule: String,
    pub suggested_kind: Option<RhoRejectedRuleDispositionKind>,
    pub reason: RhoRejectedRuleClassificationReason,
}

impl RhoRejectedRuleClassification {
    fn new(
        rule: impl Into<String>,
        suggested_kind: Option<RhoRejectedRuleDispositionKind>,
        reason: RhoRejectedRuleClassificationReason,
    ) -> Self {
        Self {
            rule: rule.into(),
            suggested_kind,
            reason,
        }
    }

    /// This helper deliberately refuses classifications without a suggested
    /// kind; callers must inspect those cases instead of silently fabricating a
    /// coverage claim.
    pub fn to_disposition(&self) -> Option<RhoRejectedRuleDisposition> {
        self.suggested_kind
            .map(|kind| RhoRejectedRuleDisposition::new(self.rule.clone(), kind))
    }
}

/// Invalid rejected-rule coverage diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoRejectedRuleDispositionDiagnostic {
    MissingRuleId,
    DuplicateRuleDisposition { rule: String },
}

/// Coverage evidence for rules not lowered by the scalar Rho AST generator.
///
/// A default Rho backend may not ignore `RhoLowering::rejected`. Either every
/// rule lowered to Rholang AST, or every rejected rule is covered by an
/// explicit external/native/Rho handler contract that passed the separate
/// coverage audit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RhoCoverageEvidence {
    /// The backend is acceptable only when `RhoLowering::rejected` is empty.
    AllRulesLowered,
    /// Rejected rules are acceptable only when these dispositions
    /// name exactly the rejected rule set and every disposition is well-formed.
    CoveredRejectedRules(Vec<RhoRejectedRuleDisposition>),
}

impl RhoCoverageEvidence {
    fn covered_dispositions(&self) -> &[RhoRejectedRuleDisposition] {
        match self {
            Self::AllRulesLowered => &[],
            Self::CoveredRejectedRules(dispositions) => dispositions,
        }
    }

    fn covered_set(&self) -> BTreeSet<&str> {
        match self {
            Self::AllRulesLowered => BTreeSet::new(),
            Self::CoveredRejectedRules(dispositions) => dispositions
                .iter()
                .map(|disposition| disposition.rule.as_str())
                .collect(),
        }
    }

    fn uncovered_rejections(&self, lowering: &RhoLowering) -> Vec<String> {
        let covered = self.covered_set();
        lowering
            .rejected
            .iter()
            .filter(|rule| !covered.contains(rule.as_str()))
            .cloned()
            .collect()
    }

    fn extraneous_dispositions(&self, lowering: &RhoLowering) -> Vec<String> {
        let rejected: BTreeSet<&str> = lowering.rejected.iter().map(String::as_str).collect();
        self.covered_set()
            .into_iter()
            .filter(|rule| !rejected.contains(rule))
            .map(ToOwned::to_owned)
            .collect()
    }

    fn invalid_dispositions(&self) -> Vec<RhoRejectedRuleDispositionDiagnostic> {
        let mut diagnostics = Vec::new();
        let mut seen = BTreeSet::new();
        let mut duplicate_reported = BTreeSet::new();

        for disposition in self.covered_dispositions() {
            if disposition.rule.trim().is_empty() {
                diagnostics.push(RhoRejectedRuleDispositionDiagnostic::MissingRuleId);
            } else if !seen.insert(disposition.rule.as_str())
                && duplicate_reported.insert(disposition.rule.as_str())
            {
                diagnostics.push(RhoRejectedRuleDispositionDiagnostic::DuplicateRuleDisposition {
                    rule: disposition.rule.clone(),
                });
            }
        }

        diagnostics
    }

    fn exactly_covers(&self, lowering: &RhoLowering) -> bool {
        self.uncovered_rejections(lowering).is_empty()
            && self.extraneous_dispositions(lowering).is_empty()
            && self.invalid_dispositions().is_empty()
    }

    fn accepted_dispositions(&self) -> Vec<RhoRejectedRuleDisposition> {
        match self {
            Self::AllRulesLowered => Vec::new(),
            Self::CoveredRejectedRules(dispositions) => dispositions.clone(),
        }
    }
}

fn collect_referenced_constructor_labels(def: &LanguageDef) -> HashSet<String> {
    let mut labels = HashSet::new();
    for equation in &def.equations {
        equation.left.collect_constructor_labels(&mut labels);
        equation.right.collect_constructor_labels(&mut labels);
    }
    for rewrite in &def.rewrites {
        rewrite.left.collect_constructor_labels(&mut labels);
        rewrite.right.collect_constructor_labels(&mut labels);
    }
    labels
}

fn type_expr_is_structured(ty: &TypeExpr) -> bool {
    match ty {
        TypeExpr::Base(_) => false,
        TypeExpr::Arrow { .. }
        | TypeExpr::MultiBinder(_)
        | TypeExpr::Collection { .. }
        | TypeExpr::Refined { .. }
        | TypeExpr::Map { .. } => true,
    }
}

fn term_param_is_structured(param: &TermParam) -> bool {
    match param {
        TermParam::Simple { ty, .. } => type_expr_is_structured(ty),
        TermParam::Abstraction { .. }
        | TermParam::MultiAbstraction { .. }
        | TermParam::GuardBody { .. }
        | TermParam::Optional { .. } => true,
    }
}

fn grammar_item_is_structured(item: &GrammarItem) -> bool {
    matches!(item, GrammarItem::Binder { .. } | GrammarItem::Collection { .. })
}

fn syntax_expr_is_structured(expr: &SyntaxExpr) -> bool {
    matches!(expr, SyntaxExpr::Op(_))
}

fn rule_has_structured_syntax(rule: &GrammarRule) -> bool {
    rule.items.iter().any(grammar_item_is_structured)
        || rule
            .term_context
            .as_ref()
            .is_some_and(|params| params.iter().any(term_param_is_structured))
        || rule
            .syntax_pattern
            .as_ref()
            .is_some_and(|pattern| pattern.iter().any(syntax_expr_is_structured))
}

fn rule_has_scalar_operator_shape(rule: &GrammarRule) -> bool {
    let Some(pattern) = &rule.syntax_pattern else {
        return false;
    };
    matches!(
        pattern.as_slice(),
        [SyntaxExpr::Param(_), SyntaxExpr::Literal(_), SyntaxExpr::Param(_)]
            | [SyntaxExpr::Literal(_), SyntaxExpr::Param(_)]
    )
}

fn classify_rejected_rule(
    rule: &GrammarRule,
    referenced_labels: &HashSet<String>,
) -> RhoRejectedRuleClassification {
    let label = rule.label.to_string();
    if rule.rust_code.is_some() || rule.eval_mode.is_some() {
        return RhoRejectedRuleClassification::new(
            label,
            Some(RhoRejectedRuleDispositionKind::NativeHandler),
            RhoRejectedRuleClassificationReason::NativeEvaluation,
        );
    }

    if referenced_labels.contains(&label) {
        return RhoRejectedRuleClassification::new(
            label,
            Some(RhoRejectedRuleDispositionKind::RhoAstContract),
            RhoRejectedRuleClassificationReason::ReferencedByEquationOrRewrite,
        );
    }

    if rule_has_structured_syntax(rule) {
        return RhoRejectedRuleClassification::new(
            label,
            Some(RhoRejectedRuleDispositionKind::RhoAstContract),
            RhoRejectedRuleClassificationReason::StructuredSyntax,
        );
    }

    if rule_has_scalar_operator_shape(rule) {
        return RhoRejectedRuleClassification::new(
            label,
            Some(RhoRejectedRuleDispositionKind::ExternalContract),
            RhoRejectedRuleClassificationReason::UnsupportedScalarOperator,
        );
    }

    RhoRejectedRuleClassification::new(
        label,
        Some(RhoRejectedRuleDispositionKind::RhoAstContract),
        RhoRejectedRuleClassificationReason::StructuralConstructor,
    )
}

/// Classify every rule label in `lowering.rejected` using `def` as the source
/// of truth.
///
/// The returned classifications are advisory. They are intended for generated
/// coverage tooling and review output, not for bypassing the exact
/// `CoveredRejectedRules` gate. To become accepted coverage, each suggested
/// classification still has to be supplied through
/// [`RhoCoverageEvidence::CoveredRejectedRules`].
pub fn classify_rejected_rules(
    def: &LanguageDef,
    lowering: &RhoLowering,
) -> Vec<RhoRejectedRuleClassification> {
    let rules_by_label = def
        .terms
        .iter()
        .map(|rule| (rule.label.to_string(), rule))
        .collect::<HashMap<_, _>>();
    let referenced_labels = collect_referenced_constructor_labels(def);

    lowering
        .rejected
        .iter()
        .map(|label| {
            rules_by_label.get(label).map_or_else(
                || {
                    RhoRejectedRuleClassification::new(
                        label.clone(),
                        None,
                        RhoRejectedRuleClassificationReason::MissingLanguageRule,
                    )
                },
                |rule| classify_rejected_rule(rule, &referenced_labels),
            )
        })
        .collect()
}

/// Readiness audit for installing a `LanguageDef` as a Rho-default backend.
///
/// This is a diagnostic artifact, not acceptance evidence. It exposes the
/// exact lowering, validation, deadlock, rejected-rule, and guard-obligation
/// state that generated installers need before they decide which separately
/// verified coverage evidence to supply to [`plan_rho_default_backend`].
#[derive(Debug, Clone, PartialEq)]
pub struct RhoDefaultBackendAudit {
    pub lowering: RhoLowering,
    pub rejected_rule_classifications: Vec<RhoRejectedRuleClassification>,
    pub guard_obligations: Vec<RhoGuardObligation>,
    pub validation_errors: Vec<RhoValidationError>,
    pub decision_without_external_coverage: RhoFlipDecision,
}

impl RhoDefaultBackendAudit {
    /// True when this language can pass the Rho-default gate with no external,
    /// native, guard, or structural coverage dispositions.
    pub fn can_plan_without_external_coverage(&self) -> bool {
        self.decision_without_external_coverage.can_flip_to_rho()
    }

    /// Suggested rejected-rule dispositions for review output or generated
    /// coverage scaffolding.
    ///
    /// Missing suggestions are omitted deliberately. Callers must compare the
    /// returned disposition count against `lowering.rejected.len()` before using
    /// the result as coverage input.
    pub fn suggested_rejected_rule_dispositions(&self) -> Vec<RhoRejectedRuleDisposition> {
        self.rejected_rule_classifications
            .iter()
            .filter_map(RhoRejectedRuleClassification::to_disposition)
            .collect()
    }

    /// Whether every rejected rule has an advisory disposition.
    pub fn all_rejected_rules_have_suggestions(&self) -> bool {
        self.suggested_rejected_rule_dispositions().len() == self.lowering.rejected.len()
    }
}

/// Lower `def` and report all Rho-default planning blockers without accepting
/// any rejected-rule or guard coverage by implication.
///
/// The resulting classifications are advisory. They intentionally do not
/// modify the exact flip gate: production planning still has to call
/// [`plan_rho_default_backend`] with coverage evidence that exactly matches the
/// rejected-rule and guard-obligation sets.
pub fn audit_rho_default_backend(def: &LanguageDef) -> RhoDefaultBackendAudit {
    let lowering = lower_language_def(def);
    let validation_errors = ValidatedRhoProgram::try_from(lowering.program.clone())
        .err()
        .unwrap_or_default();
    let rejected_rule_classifications = classify_rejected_rules(def, &lowering);
    let guard_obligations = collect_guard_obligations(def);
    let coverage_passed = lowering.rejected.is_empty() && guard_obligations.is_empty();
    // The audit models the NO-external-coverage scenario: no guard-coverage
    // evidence is supplied, so the covered-obligation set is empty and there are
    // no guard-quality blockers to fold in (any guard obligations already fail
    // the `coverage_passed` gate above). Quality blockers are derived in
    // `plan_rho_default_backend`, where actual coverage evidence selects the
    // covered obligations to quality-check.
    let decision_without_external_coverage = decide_rho_flip(
        RhoFlipGates {
            coverage_passed,
            artifact_validated: validation_errors.is_empty(),
        },
        &lowering.deadlock_report,
        Vec::new(),
    );

    RhoDefaultBackendAudit {
        lowering,
        rejected_rule_classifications,
        guard_obligations,
        validation_errors,
        decision_without_external_coverage,
    }
}

/// Checkable inputs for selecting Rho as a language's default runtime backend.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RhoDefaultBackendRequirements {
    pub coverage: RhoCoverageEvidence,
    pub guard_coverage: RhoGuardCoverageEvidence,
}

/// Concrete plan for a language that passed the Rho-default flip gate.
#[derive(Debug, Clone, PartialEq)]
pub struct RhoDefaultBackendPlan {
    pub lowering: RhoLowering,
    pub validated_program: ValidatedRhoProgram,
    pub rejected_rule_dispositions: Vec<RhoRejectedRuleDisposition>,
    pub guard_obligation_dispositions: Vec<RhoGuardDisposition>,
    /// Substrate quality tags for the language's guard obligations, derived by
    /// the predicate-substrate classifier ([`derive_guard_qualities`]). This is
    /// strictly diagnostic/observability data recording how strong each guard's
    /// evidence is (every tag here is non-`Unknown`, since an `Unknown` quality
    /// would have produced a [`RhoFlipBlocker::GuardQuality`] and blocked the
    /// flip). It is NEVER part of `LanguageDef` identity, the
    /// `definition_fingerprint`, or any runtime gate field — proof/quality
    /// attribution stays external (commit `6d20b82d`).
    pub guard_obligation_qualities: Vec<RhoGuardDispositionQuality>,
}

impl RhoDefaultBackendPlan {
    /// Name of the `LanguageDef` whose lowering passed the default-backend
    /// gate. Runtime wrappers use this to reject cross-language plan
    /// installation.
    pub fn language_name(&self) -> &str {
        self.lowering.language_name()
    }

    /// The substrate quality tags for this language's guard obligations
    /// (diagnostic observability; every entry is non-`Unknown`). See
    /// [`RhoDefaultBackendPlan::guard_obligation_qualities`].
    pub fn guard_obligation_qualities(&self) -> &[RhoGuardDispositionQuality] {
        &self.guard_obligation_qualities
    }

    /// Stable compiler-facing identity of the `LanguageDef` whose lowering
    /// passed the default-backend gate.
    pub fn definition_fingerprint(&self) -> &str {
        self.lowering.definition_fingerprint()
    }

    /// Executable Rho backend artifact selected and validated by the flip gate.
    pub fn program(&self) -> &ValidatedRhoProgram {
        &self.validated_program
    }

    /// Normalized AST to inject into the host Rho runtime, when available.
    pub fn ast_par(&self) -> Option<&Par> {
        self.program().ast_par()
    }

    /// Reader/debug annotation. This text is not parsed as the execution path.
    pub fn text_annotation(&self) -> &str {
        self.program().text_annotation()
    }
}

/// Rejected Rho-default plan with complete diagnostic state for callers.
#[derive(Debug, Clone, PartialEq)]
pub struct RhoDefaultBackendPlanError {
    pub lowering: Box<RhoLowering>,
    pub decision: Box<RhoFlipDecision>,
    pub uncovered_rejections: Box<[String]>,
    pub extraneous_dispositions: Box<[String]>,
    pub invalid_dispositions: Box<[RhoRejectedRuleDispositionDiagnostic]>,
    pub uncovered_guard_obligations: Box<[String]>,
    pub extraneous_guard_dispositions: Box<[String]>,
    pub invalid_guard_dispositions: Box<[RhoGuardDispositionDiagnostic]>,
    pub validation_errors: Box<[RhoValidationError]>,
}

/// Lower `def` and build the Rho-default backend plan if every flip gate passes.
pub fn plan_rho_default_backend(
    def: &LanguageDef,
    requirements: RhoDefaultBackendRequirements,
) -> Result<RhoDefaultBackendPlan, RhoDefaultBackendPlanError> {
    let lowering = lower_language_def(def);
    let validated_program = ValidatedRhoProgram::try_from(lowering.program.clone());
    let validation_errors = validated_program.clone().err().unwrap_or_default();
    let uncovered_rejections = requirements.coverage.uncovered_rejections(&lowering);
    let extraneous_dispositions = requirements.coverage.extraneous_dispositions(&lowering);
    let invalid_dispositions = requirements.coverage.invalid_dispositions();
    let guard_obligations = collect_guard_obligations(def);
    let uncovered_guard_obligations = requirements
        .guard_coverage
        .uncovered_obligations(&guard_obligations);
    let extraneous_guard_dispositions = requirements
        .guard_coverage
        .extraneous_dispositions(&guard_obligations);
    let invalid_guard_dispositions = requirements
        .guard_coverage
        .invalid_dispositions(&guard_obligations);
    let coverage_passed = requirements.coverage.exactly_covers(&lowering)
        && requirements
            .guard_coverage
            .exactly_covers(&guard_obligations);

    // Predicate-substrate quality tags for every induced guard obligation. The
    // substrate ([`derive_guard_qualities`]) classifies HOW STRONG each guard's
    // evidence is (orthogonal to the disposition MECHANISM the coverage gate
    // checks). Restrict to the obligations the requirements actually cover: an
    // uncovered obligation is already a `Coverage` blocker, so it must not also
    // produce a quality blocker. A covered obligation whose quality refuses
    // production-default lowering (`Unknown`) becomes a fail-closed
    // `RhoFlipBlocker::GuardQuality` (doc-08: "`Unknown` quality ⇒
    // production-default refused"). For all current obligation kinds the
    // substrate never yields `Unknown`, so this is real, fail-closed wiring with
    // no behavioral change for existing languages.
    let guard_obligation_qualities = derive_guard_qualities(def);
    let covered_guard_obligations = requirements.guard_coverage.covered_set();
    let guard_quality_blockers = guard_quality_blockers_for(
        &guard_obligation_qualities
            .iter()
            .filter(|disposition| {
                covered_guard_obligations.contains(disposition.obligation.as_str())
            })
            .cloned()
            .collect::<Vec<_>>(),
    );

    // Formal model: `formal/rocq/rho_bridge/theories/RhoBackendFlipGate.v`.
    // The Rust plan carries only the semantic gate result and validated
    // artifacts; proof attribution stays in comments and CI/docs, not runtime
    // data.
    let decision = decide_rho_flip(
        RhoFlipGates {
            coverage_passed,
            artifact_validated: validation_errors.is_empty(),
        },
        &lowering.deadlock_report,
        guard_quality_blockers,
    );

    if decision.can_flip_to_rho() {
        let validated_program =
            validated_program.expect("flip decision requires successful artifact validation");
        let rejected_rule_dispositions = requirements.coverage.accepted_dispositions();
        let guard_obligation_dispositions = requirements.guard_coverage.accepted_dispositions();
        Ok(RhoDefaultBackendPlan {
            rejected_rule_dispositions,
            guard_obligation_dispositions,
            guard_obligation_qualities,
            validated_program,
            lowering,
        })
    } else {
        Err(RhoDefaultBackendPlanError {
            lowering: Box::new(lowering),
            decision: Box::new(decision),
            uncovered_rejections: uncovered_rejections.into_boxed_slice(),
            extraneous_dispositions: extraneous_dispositions.into_boxed_slice(),
            invalid_dispositions: invalid_dispositions.into_boxed_slice(),
            uncovered_guard_obligations: uncovered_guard_obligations.into_boxed_slice(),
            extraneous_guard_dispositions: extraneous_guard_dispositions.into_boxed_slice(),
            invalid_guard_dispositions: invalid_guard_dispositions.into_boxed_slice(),
            validation_errors: validation_errors.into_boxed_slice(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::flip::RhoFlipBlocker;
    use mettail_ast::pattern::{Pattern, PatternTerm};

    fn boxed<T>(values: Vec<T>) -> Box<[T]> {
        values.into_boxed_slice()
    }

    fn boxed_strings(values: &[&str]) -> Box<[String]> {
        values
            .iter()
            .map(|value| (*value).to_string())
            .collect::<Vec<_>>()
            .into_boxed_slice()
    }

    const ALL_LOWERED_FRAGMENT: &str = r#"
        name: CalcAllLowered,
        types {
            Proc
            ![i64] as Int
        }
        terms {
            AddInt . a:Int, b:Int |- a "+" b : Int ;
            SubInt . a:Int, b:Int |- a "-" b : Int ;
            Neg . a:Int |- "-" a : Int ;
        }
    "#;

    const PARTIAL_FRAGMENT: &str = r#"
        name: CalcPartial,
        types {
            Proc
            ![i64] as Int
            ![mettail_runtime::CanonicalBigInt] as BigInt
        }
        terms {
            AddInt . a:Int, b:Int |- a "+" b : Int ;
            PowInt . a:Int, b:Int |- a "^" b : Int ;
            AddBigInt . a:BigInt, b:BigInt |- a "+" b : BigInt ;
        }
    "#;

    const NATIVE_REJECTED_FRAGMENT: &str = r#"
        name: CalcNativeRejected,
        types {
            Proc
            ![i64] as Int
        }
        terms {
            PowInt . a:Int, b:Int |- a "^" b : Int ![a.pow(b as u32)] fold;
            FactInt . a:Int |- a "!" : Int ![factorial(a)] step;
        }
    "#;

    const GUARDED_SCALAR_FRAGMENT: &str = r#"
        name: GuardedScalar,
        types {
            Proc
            Name
            ![i64] as Int
            ![bool] as Bool
        },
        guards {
            gt . x: Int, y: Int |- x ">" y ;
            theories {
                arithmetic = PresburgerAlgebra for [Int];
            }
            channels {
                channel Name;
                join PGuardedInput(ch: Name);
            }
        },
        terms {
            AddInt . a:Int, b:Int |- a "+" b : Int ;
            PGuardedInput . n:Name, ?guard:Guard, ^x.p:[Name -> Proc]
                |- "for" "(" x "<-" n "where" guard ")" "{" p "}" : Proc ;
        }
    "#;

    const MINIRHO_FOR_FRAGMENT: &str = r#"
        name: MiniRhoFor,
        options {
            emit_simulator: false,
            emit_blockly: false,
        },
        types {
            Proc
            Name
        },
        terms {
            PZero . |- "0" : Proc ;

            PPar . ps:HashBag(Proc)
                |- "{" ps.*sep("|") "}" : Proc ;

            POutput . n:Name, q:Name
                |- n "!" "(" q ")" : Proc ;

            PFor . n:Name, ^x.p:[Name -> Proc]
                |- "for" "(" x "<-" n ")" "{" p "}" : Proc ;
        },
        equations {},
        rewrites {
            Comm . |- (PPar {(PFor N cont), (POutput N Q), ...rest})
                ~> (PPar {(eval cont Q), ...rest});

            ParCong . | S ~> T
                |- (PPar {S, ...rest}) ~> (PPar {T, ...rest});
        }
    "#;

    fn parse(src: &str) -> LanguageDef {
        syn::parse_str::<LanguageDef>(src).expect("test fragment must parse")
    }

    fn ident(name: &str) -> syn::Ident {
        syn::parse_str(name).expect("test identifier must parse")
    }

    fn guarded_scalar_with_structural_guard() -> LanguageDef {
        let mut def = parse(GUARDED_SCALAR_FRAGMENT);
        let placeholder = Pattern::Term(PatternTerm::Var(ident("P")));
        def.rewrites.push(RewriteRule {
            name: ident("GuardedStep"),
            type_context: Vec::new(),
            premises: vec![Premise::BehavioralGuard(BehavioralPred::AcMatch {
                bag: ident("xs"),
                elements: vec![ident("x")],
                rest: Some(ident("rest")),
            })],
            left: placeholder.clone(),
            right: placeholder,
            is_auto_injected: false,
        });
        def
    }

    fn passing_requirements(coverage: RhoCoverageEvidence) -> RhoDefaultBackendRequirements {
        RhoDefaultBackendRequirements {
            coverage,
            guard_coverage: RhoGuardCoverageEvidence::NoGuardObligations,
        }
    }

    fn native_disposition(rule: &str) -> RhoRejectedRuleDisposition {
        RhoRejectedRuleDisposition::new(rule, RhoRejectedRuleDispositionKind::NativeHandler)
    }

    fn rho_ast_disposition(rule: &str) -> RhoRejectedRuleDisposition {
        RhoRejectedRuleDisposition::new(rule, RhoRejectedRuleDispositionKind::RhoAstContract)
    }

    fn guard_disposition(obligation: &str, kind: RhoGuardDispositionKind) -> RhoGuardDisposition {
        RhoGuardDisposition::new(obligation, kind)
    }

    fn classification<'a>(
        classifications: &'a [RhoRejectedRuleClassification],
        rule: &str,
    ) -> &'a RhoRejectedRuleClassification {
        classifications
            .iter()
            .find(|classification| classification.rule == rule)
            .expect("classification must exist for rejected rule")
    }

    #[test]
    fn default_backend_plan_succeeds_when_all_rules_lower() {
        let plan = plan_rho_default_backend(
            &parse(ALL_LOWERED_FRAGMENT),
            passing_requirements(RhoCoverageEvidence::AllRulesLowered),
        )
        .expect("all-lowered fragment should pass the default-backend gate");

        assert_eq!(plan.language_name(), "CalcAllLowered");
        assert_eq!(plan.lowering.language_name(), "CalcAllLowered");
        assert_eq!(plan.lowering.lowered, vec!["AddInt", "SubInt", "Neg"]);
        assert_eq!(plan.lowering.rejected, Vec::<String>::new());
        assert_eq!(plan.rejected_rule_dispositions, Vec::new());
        assert_eq!(plan.ast_par().expect("plan must carry AST").receives.len(), 3);
        assert!(plan.text_annotation().contains("contract @\"AddInt\""));
    }

    #[test]
    fn rejected_rule_classification_is_derived_from_language_def() {
        let def = parse(PARTIAL_FRAGMENT);
        let lowering = lower_language_def(&def);
        let classifications = classify_rejected_rules(&def, &lowering);

        assert_eq!(lowering.rejected, vec!["PowInt", "AddBigInt"]);
        assert_eq!(
            classifications,
            vec![
                RhoRejectedRuleClassification {
                    rule: "PowInt".to_string(),
                    suggested_kind: Some(RhoRejectedRuleDispositionKind::ExternalContract),
                    reason: RhoRejectedRuleClassificationReason::UnsupportedScalarOperator,
                },
                RhoRejectedRuleClassification {
                    rule: "AddBigInt".to_string(),
                    suggested_kind: Some(RhoRejectedRuleDispositionKind::ExternalContract),
                    reason: RhoRejectedRuleClassificationReason::UnsupportedScalarOperator,
                },
            ]
        );

        let disposition = classifications[0]
            .to_disposition()
            .expect("classification with suggested kind should become disposition");
        assert_eq!(
            disposition,
            RhoRejectedRuleDisposition::new(
                "PowInt",
                RhoRejectedRuleDispositionKind::ExternalContract
            )
        );
    }

    #[test]
    fn default_backend_audit_reports_all_lowered_readiness_without_external_coverage() {
        let audit = audit_rho_default_backend(&parse(ALL_LOWERED_FRAGMENT));

        assert_eq!(audit.lowering.language_name(), "CalcAllLowered");
        assert_eq!(audit.lowering.lowered, vec!["AddInt", "SubInt", "Neg"]);
        assert!(audit.lowering.rejected.is_empty());
        assert!(audit.rejected_rule_classifications.is_empty());
        assert!(audit.guard_obligations.is_empty());
        assert!(audit.validation_errors.is_empty());
        assert!(audit.can_plan_without_external_coverage());
        assert!(audit.decision_without_external_coverage.can_flip_to_rho());
    }

    #[test]
    fn default_backend_audit_keeps_rejected_classifications_advisory() {
        let audit = audit_rho_default_backend(&parse(PARTIAL_FRAGMENT));

        assert_eq!(audit.lowering.lowered, vec!["AddInt"]);
        assert_eq!(audit.lowering.rejected, vec!["PowInt", "AddBigInt"]);
        assert_eq!(audit.rejected_rule_classifications.len(), 2);
        assert!(audit.all_rejected_rules_have_suggestions());
        assert_eq!(
            audit
                .suggested_rejected_rule_dispositions()
                .iter()
                .map(|disposition| (disposition.rule.as_str(), disposition.kind))
                .collect::<Vec<_>>(),
            vec![
                ("PowInt", RhoRejectedRuleDispositionKind::ExternalContract),
                ("AddBigInt", RhoRejectedRuleDispositionKind::ExternalContract),
            ]
        );
        assert!(
            !audit.can_plan_without_external_coverage(),
            "advisory classifications must not make rejected rules accepted coverage"
        );
        assert!(audit
            .decision_without_external_coverage
            .blockers
            .contains(&RhoFlipBlocker::Coverage));
    }

    #[test]
    fn default_backend_audit_reports_guard_obligations_as_blockers() {
        let audit = audit_rho_default_backend(&guarded_scalar_with_structural_guard());

        assert_eq!(audit.lowering.lowered, vec!["AddInt"]);
        assert!(!audit.guard_obligations.is_empty());
        assert!(audit
            .guard_obligations
            .iter()
            .any(|obligation| { obligation.kind == RhoGuardObligationKind::BehavioralPredicate }));
        assert!(audit
            .guard_obligations
            .iter()
            .any(|obligation| { obligation.kind == RhoGuardObligationKind::StructuralPattern }));
        assert!(
            !audit.can_plan_without_external_coverage(),
            "guard obligations require explicit coverage evidence"
        );
        assert!(audit
            .decision_without_external_coverage
            .blockers
            .contains(&RhoFlipBlocker::Coverage));
    }

    #[test]
    fn native_rejected_rule_classification_uses_eval_metadata() {
        let def = parse(NATIVE_REJECTED_FRAGMENT);
        let lowering = lower_language_def(&def);
        let classifications = classify_rejected_rules(&def, &lowering);

        assert_eq!(lowering.rejected, vec!["PowInt", "FactInt"]);
        for rule in ["PowInt", "FactInt"] {
            let classification = classification(&classifications, rule);
            assert_eq!(
                classification.suggested_kind,
                Some(RhoRejectedRuleDispositionKind::NativeHandler)
            );
            assert_eq!(
                classification.reason,
                RhoRejectedRuleClassificationReason::NativeEvaluation
            );
        }
    }

    #[test]
    fn rho_structural_rule_classification_comes_from_rewrites_and_syntax() {
        let def = parse(MINIRHO_FOR_FRAGMENT);
        let lowering = lower_language_def(&def);
        let classifications = classify_rejected_rules(&def, &lowering);

        assert_eq!(lowering.lowered, Vec::<String>::new());
        assert_eq!(lowering.rejected, vec!["PZero", "PPar", "POutput", "PFor"]);

        assert_eq!(
            classification(&classifications, "PZero").suggested_kind,
            Some(RhoRejectedRuleDispositionKind::RhoAstContract)
        );
        assert_eq!(
            classification(&classifications, "PZero").reason,
            RhoRejectedRuleClassificationReason::StructuralConstructor
        );

        for rule in ["PPar", "POutput", "PFor"] {
            let classification = classification(&classifications, rule);
            assert_eq!(
                classification.suggested_kind,
                Some(RhoRejectedRuleDispositionKind::RhoAstContract)
            );
            assert_eq!(
                classification.reason,
                RhoRejectedRuleClassificationReason::ReferencedByEquationOrRewrite
            );
        }
    }

    #[test]
    fn guard_obligations_cover_behavioral_structural_eba_and_rho_native_surfaces() {
        let def = guarded_scalar_with_structural_guard();
        let obligations = collect_guard_obligations(&def);
        assert_eq!(
            obligations,
            vec![
                RhoGuardObligation::new("channel:Name", RhoGuardObligationKind::RhoNativeJoin),
                RhoGuardObligation::new(
                    "join:PGuardedInput",
                    RhoGuardObligationKind::RhoNativeJoin
                ),
                RhoGuardObligation::new(
                    "predicate:gt",
                    RhoGuardObligationKind::BehavioralPredicate
                ),
                RhoGuardObligation::new(
                    "rewrite:GuardedStep:guard:0",
                    RhoGuardObligationKind::StructuralPattern
                ),
                RhoGuardObligation::new(
                    "term:PGuardedInput:guard:guard",
                    RhoGuardObligationKind::BehavioralPredicate
                ),
                RhoGuardObligation::new(
                    "theory:arithmetic",
                    RhoGuardObligationKind::TheoryRegistration
                ),
            ]
        );
    }

    #[test]
    fn default_backend_plan_blocks_uncovered_guard_obligations() {
        let err = plan_rho_default_backend(
            &guarded_scalar_with_structural_guard(),
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                rho_ast_disposition("PGuardedInput"),
            ])),
        )
        .expect_err("uncovered guard obligations must block Rho default");

        assert_eq!(
            err.uncovered_guard_obligations,
            boxed_strings(&[
                "channel:Name",
                "join:PGuardedInput",
                "predicate:gt",
                "rewrite:GuardedStep:guard:0",
                "term:PGuardedInput:guard:guard",
                "theory:arithmetic",
            ])
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_accepts_exact_guard_coverage() {
        let mut requirements =
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                rho_ast_disposition("PGuardedInput"),
            ]));
        requirements.guard_coverage = RhoGuardCoverageEvidence::CoveredGuardObligations(vec![
            guard_disposition("channel:Name", RhoGuardDispositionKind::RhoNativeJoin),
            guard_disposition("join:PGuardedInput", RhoGuardDispositionKind::RhoNativeJoin),
            guard_disposition("predicate:gt", RhoGuardDispositionKind::EffectiveBooleanAlgebra),
            guard_disposition(
                "rewrite:GuardedStep:guard:0",
                RhoGuardDispositionKind::SymbolicFiniteTransducer,
            ),
            guard_disposition(
                "term:PGuardedInput:guard:guard",
                RhoGuardDispositionKind::RhoNativeJoin,
            ),
            guard_disposition(
                "theory:arithmetic",
                RhoGuardDispositionKind::EffectiveBooleanAlgebra,
            ),
        ]);

        let plan = plan_rho_default_backend(&guarded_scalar_with_structural_guard(), requirements)
            .expect("exact guard coverage must pass the default-backend gate");

        assert_eq!(plan.lowering.lowered, vec!["AddInt"]);
        assert_eq!(plan.lowering.rejected, vec!["PGuardedInput"]);
        assert_eq!(plan.guard_obligation_dispositions.len(), 6);

        // The substrate quality tags are carried on the plan (observability).
        // The behavioral-predicate legs (`predicate:gt`,
        // `term:PGuardedInput:guard:guard`) are RECORDED as reject-safe — not
        // Unknown — so the language flips with bounded/reject-safe evidence,
        // exactly the M7 mixed-guard soundness case.
        use crate::guard_quality::RhoGuardQuality;
        let quality_for = |obligation: &str| -> RhoGuardQuality {
            plan.guard_obligation_qualities()
                .iter()
                .find(|disposition| disposition.obligation == obligation)
                .unwrap_or_else(|| panic!("plan must carry a quality tag for {obligation}"))
                .quality
        };
        assert_eq!(quality_for("predicate:gt"), RhoGuardQuality::RejectSafeApprox);
        assert_eq!(
            quality_for("term:PGuardedInput:guard:guard"),
            RhoGuardQuality::RejectSafeApprox
        );
        assert_eq!(quality_for("rewrite:GuardedStep:guard:0"), RhoGuardQuality::ExactDecidable);
        assert_eq!(quality_for("theory:arithmetic"), RhoGuardQuality::ExactDecidable);
        assert_eq!(quality_for("channel:Name"), RhoGuardQuality::RuntimeObservation);
        assert_eq!(quality_for("join:PGuardedInput"), RhoGuardQuality::RuntimeObservation);
        // No obligation is Unknown ⇒ no quality blocker fired (the flip succeeded).
        assert!(
            plan.guard_obligation_qualities()
                .iter()
                .all(|disposition| !disposition.quality.refuses_production_default()),
            "a flipped plan must carry no production-default-refusing (Unknown) quality"
        );
        assert_eq!(plan.guard_obligation_qualities().len(), 6);
    }

    #[test]
    fn unknown_guard_quality_yields_fail_closed_blocker() {
        // The live consumption of the substrate classifier: an `Unknown`-quality
        // covered obligation produces a `RhoFlipBlocker::GuardQuality` that the
        // flip gate treats as fail-closed (doc-08: "`Unknown` ⇒ refused"). The
        // substrate's `default_classification` never yields `Unknown` for the
        // real obligation kinds, so this exercises the gate's wiring with a
        // hand-built Unknown disposition-quality.
        use crate::guard_quality::{RhoGuardDispositionQuality, RhoGuardQuality};

        let usable = RhoGuardDispositionQuality {
            obligation: "predicate:gt".to_string(),
            kind: RhoGuardDispositionKind::EffectiveBooleanAlgebra,
            quality: RhoGuardQuality::RejectSafeApprox,
        };
        let unknown = RhoGuardDispositionQuality {
            obligation: "predicate:mystery".to_string(),
            kind: RhoGuardDispositionKind::EffectiveBooleanAlgebra,
            quality: RhoGuardQuality::Unknown,
        };

        // A usable quality produces no blocker.
        assert!(guard_quality_blockers_for(&[usable.clone()]).is_empty());

        // The Unknown quality produces exactly one GuardQuality blocker, and it
        // blocks the flip even with all Boolean gates passing + a clean report.
        let blockers = guard_quality_blockers_for(&[usable, unknown]);
        assert_eq!(
            blockers,
            vec![RhoFlipBlocker::GuardQuality {
                obligation: "predicate:mystery".to_string(),
                quality: RhoGuardQuality::Unknown,
            }]
        );

        let clean = crate::deadlock::analyze_channel_deadlocks(
            &crate::deadlock::ChannelNetwork::new()
                .with_external("entry")
                .with_contract(crate::deadlock::ContractFlow::exported_service(
                    "entry",
                    std::iter::empty::<&str>(),
                )),
        );
        let decision = crate::flip::decide_rho_flip(
            RhoFlipGates {
                coverage_passed: true,
                artifact_validated: true,
            },
            &clean,
            blockers.clone(),
        );
        assert!(!decision.can_flip_to_rho(), "an Unknown-quality guard must refuse the flip");
        assert_eq!(decision.blockers, blockers);
    }

    #[test]
    fn default_backend_plan_rejects_incompatible_guard_disposition() {
        let mut requirements =
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                rho_ast_disposition("PGuardedInput"),
            ]));
        requirements.guard_coverage = RhoGuardCoverageEvidence::CoveredGuardObligations(vec![
            guard_disposition("channel:Name", RhoGuardDispositionKind::RhoNativeJoin),
            guard_disposition("join:PGuardedInput", RhoGuardDispositionKind::RhoNativeJoin),
            guard_disposition("predicate:gt", RhoGuardDispositionKind::DovetailCoreStructural),
            guard_disposition(
                "rewrite:GuardedStep:guard:0",
                RhoGuardDispositionKind::SymbolicFiniteTransducer,
            ),
            guard_disposition(
                "term:PGuardedInput:guard:guard",
                RhoGuardDispositionKind::RhoNativeJoin,
            ),
            guard_disposition(
                "theory:arithmetic",
                RhoGuardDispositionKind::EffectiveBooleanAlgebra,
            ),
        ]);

        let err = plan_rho_default_backend(&guarded_scalar_with_structural_guard(), requirements)
            .expect_err("behavioral predicates cannot be covered by structural-only coverage");

        assert_eq!(err.uncovered_guard_obligations, boxed_strings(&[]));
        assert_eq!(err.extraneous_guard_dispositions, boxed_strings(&[]));
        assert_eq!(
            err.invalid_guard_dispositions,
            boxed(vec![RhoGuardDispositionDiagnostic::IncompatibleDisposition {
                obligation: "predicate:gt".to_string(),
                obligation_kind: RhoGuardObligationKind::BehavioralPredicate,
                disposition_kind: RhoGuardDispositionKind::DovetailCoreStructural,
            }])
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_blocks_uncovered_rejections() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_requirements(RhoCoverageEvidence::AllRulesLowered),
        )
        .expect_err("uncovered rejected rules must block Rho default");

        assert_eq!(err.uncovered_rejections, boxed_strings(&["PowInt", "AddBigInt"]));
        assert_eq!(err.extraneous_dispositions, boxed_strings(&[]));
        assert_eq!(
            err.invalid_dispositions,
            boxed(Vec::<RhoRejectedRuleDispositionDiagnostic>::new())
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_accepts_exact_covered_rejections() {
        let plan = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
            ])),
        )
        .expect("explicitly covered rejected rules may pass the default-backend gate");

        assert_eq!(plan.lowering.lowered, vec!["AddInt"]);
        assert_eq!(plan.lowering.rejected, vec!["PowInt", "AddBigInt"]);
        assert_eq!(
            plan.rejected_rule_dispositions,
            vec![native_disposition("PowInt"), native_disposition("AddBigInt")]
        );
    }

    #[test]
    fn default_backend_plan_rejects_stale_disposition_claims() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
                native_disposition("MissingRule"),
            ])),
        )
        .expect_err("coverage must exactly match rejected rules");

        assert_eq!(err.uncovered_rejections, boxed_strings(&[]));
        assert_eq!(err.extraneous_dispositions, boxed_strings(&["MissingRule"]));
        assert_eq!(
            err.invalid_dispositions,
            boxed(Vec::<RhoRejectedRuleDispositionDiagnostic>::new())
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }

    #[test]
    fn default_backend_plan_rejects_duplicate_dispositions() {
        let err = plan_rho_default_backend(
            &parse(PARTIAL_FRAGMENT),
            passing_requirements(RhoCoverageEvidence::CoveredRejectedRules(vec![
                native_disposition("PowInt"),
                native_disposition("AddBigInt"),
                native_disposition("AddBigInt"),
            ])),
        )
        .expect_err("duplicate disposition claims must block the default-backend gate");

        assert_eq!(err.uncovered_rejections, boxed_strings(&[]));
        assert_eq!(err.extraneous_dispositions, boxed_strings(&[]));
        assert_eq!(
            err.invalid_dispositions,
            boxed(vec![RhoRejectedRuleDispositionDiagnostic::DuplicateRuleDisposition {
                rule: "AddBigInt".to_string()
            }])
        );
        assert_eq!(err.decision.blockers, vec![RhoFlipBlocker::Coverage]);
    }
}
