-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language rholang14.

module AbsRholang where

import Prelude (String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Int, Maybe(..)
  )
import qualified Data.String

data Program = ProgramProc Proc | ProgramDecls [TopDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TopDecl = TopDeclLang LangDecl | TopDeclProc Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Proc
    = PGround Ground
    | PCollect Collection
    | PVar ProcVar
    | PNil
    | PSimpleType SimpleType
    | PZero
    | PVarRef VarRefKind Var
    | PNegation Proc
    | PConjunction Proc Proc
    | PDisjunction Proc Proc
    | PEval Name
    | PMethod Proc Var [Proc]
    | PExprs Proc
    | PLam Var Proc
    | PMLam [Var] Proc
    | PApply DollarIdent [Proc]
    | PFuncCall Var [Proc]
    | PNot Proc
    | PNeg Proc
    | PMult Proc Proc
    | PDiv Proc Proc
    | PMod Proc Proc
    | PPercentPercent Proc Proc
    | PAdd Proc Proc
    | PMinus Proc Proc
    | PPlusPlus Proc Proc
    | PMinusMinus Proc Proc
    | PLt Proc Proc
    | PLte Proc Proc
    | PGt Proc Proc
    | PGte Proc Proc
    | PMatches Proc Proc
    | PEq Proc Proc
    | PNeq Proc Proc
    | PAnd Proc Proc
    | POr Proc Proc
    | PSend Name Send [Proc]
    | PContr Name [Name] NameRemainder Proc
    | PInput [Receipt] Proc
    | PChoice [Branch]
    | PMatch Proc [Case]
    | PBundle Bundle Proc
    | PLet Decl Decls Proc
    | PInputTc [ChanBind] Proc
    | PIf Proc Proc
    | PIfElse Proc Proc Proc
    | PNew [NameDecl] Proc
    | PNewParen [Var] Proc
    | PSendSynch Name [Proc] SynchSendCont
    | PPar Proc Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Name = NameWildcard | NameVar Var | NameQuote Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Receipt
    = ReceiptLinear ReceiptLinearImpl
    | ReceiptRepeated ReceiptRepeatedImpl
    | ReceiptPeek ReceiptPeekImpl
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReceiptLinearImpl
    = LinearSimple [LinearBind] | LinearWhere [LinearBind] Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LinearBind = LinearBindImpl [Name] NameRemainder NameSource
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data NameSource
    = SimpleSource Name
    | ReceiveSendSource Name
    | SendReceiveSource Name [Proc]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReceiptRepeatedImpl
    = RepeatedSimple [RepeatedBind] | RepeatedWhere [RepeatedBind] Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RepeatedBind = RepeatedBindImpl [Name] NameRemainder Name
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReceiptPeekImpl
    = PeekSimple [PeekBind] | PeekWhere [PeekBind] Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PeekBind = PeekBindImpl [Name] NameRemainder Name
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ChanBind = ChanBindImpl Name Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Pred
    = PredOr Pred Pred
    | PredAnd Pred Pred
    | PredNot Pred
    | PredAtom Var [PredArg]
    | PredComp PredArg CompOp PredArg
    | PredIfLet Pattern PredArg
    | PredTrue
    | PredFalse
    | PredParen Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PredArg
    = PredArgVar Var
    | PredArgWild
    | PredArgStr StringLiteral
    | PredArgInt LongLiteral
    | PredArgFloat FloatLiteral
    | PredArgQuote Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CompOp
    = CompEq | CompNeq | CompGt | CompLt | CompGte | CompLte
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Send = SendSingle | SendMultiple
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SynchSendCont = EmptyCont | NonEmptyCont Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ProcVar = ProcVarWildcard | ProcVarVar Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Bundle
    = BundleWrite | BundleRead | BundleEquiv | BundleReadWrite
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Branch = BranchImpl ReceiptLinearImpl Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Case = CaseImpl Proc Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl = DeclImpl [Name] NameRemainder [Proc]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LinearDecl = LinearDeclImpl Decl
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConcDecl = ConcDeclImpl Decl
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decls
    = EmptyDeclImpl
    | LinearDeclsImpl [LinearDecl]
    | ConcDeclsImpl [ConcDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data NameDecl = NameDeclSimpl Var | NameDeclUrn Var UriLiteral
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarRefKind = VarRefKindProc | VarRefKindName
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BoolLiteral = BoolTrue | BoolFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Ground
    = GroundBool BoolLiteral
    | GroundInt LongLiteral
    | GroundFloat FloatLiteral
    | GroundString StringLiteral
    | GroundUri UriLiteral
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Collection
    = CollectList [Proc] ProcRemainder
    | CollectTuple Tuple
    | CollectSet [Proc] ProcRemainder
    | CollectMap [KeyValuePair] ProcRemainder
    | CollectBag [BagElem]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data KeyValuePair = KeyValuePairImpl Proc Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BagElem = BagElemImpl Proc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Tuple = TupleSingle Proc | TupleMultiple Proc [Proc]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ProcRemainder = ProcRemainderVar ProcVar | ProcRemainderEmpty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data NameRemainder = NameRemainderVar ProcVar | NameRemainderEmpty
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SimpleType
    = SimpleTypeBool
    | SimpleTypeInt
    | SimpleTypeFloat
    | SimpleTypeString
    | SimpleTypeUri
    | SimpleTypeByteArray
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Pattern
    = PatternWild
    | PatternVar Var
    | PatternGround Ground
    | PatternQuote Pattern
    | PatternConstr UpperIdent [Pattern]
    | PatternList [Pattern]
    | PatternTuple Pattern [Pattern]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LangDecl = LangDeclImpl UpperIdent [LangSection]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LangSection
    = LangSectTypes [TypeDecl]
    | LangSectTerms [TermDecl]
    | LangSectEqs [EqDecl]
    | LangSectRws [RwDecl]
    | LangSectLogic [LogicClause]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TypeDecl
    = TypeDeclSimple UpperIdent
    | TypeDeclNative TypeExpr UpperIdent
    | TypeDeclColl TypeExpr UpperIdent StringLiteral StringLiteral StringLiteral
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TypeExpr
    = TypeExprIdent Var
    | TypeExprUpper UpperIdent
    | TypeExprApp UpperIdent TypeExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermDecl
    = TermDeclPlain UpperIdent TermParams [TermItem] UpperIdent
    | TermDeclFold UpperIdent TermParams [TermItem] UpperIdent RustBlock
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermParams
    = TermParamsEmpty | TermParamsList TermParam TermParamsRest
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermParamsRest
    = TermParamsRestNil | TermParamsRestCons TermParam TermParamsRest
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermParam
    = TermParamSimple Var TermType
    | TermParamBinder VarList Var TermBinderType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarList = VarListOne Var | VarListCons Var VarList
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermType
    = TermTypeIdent UpperIdent | TermTypeColl UpperIdent UpperIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermBinderType
    = TermBinderSimple UpperIdent UpperIdent
    | TermBinderMulti UpperIdent UpperIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermItem
    = TermItemLit StringLiteral
    | TermItemVar Var
    | TermItemSep Var StringLiteral
    | TermItemZip Var Var TermLambda StringLiteral
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermLambda = TermLambdaImpl VarList [TermItem]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data EqDecl = EqDeclImpl UpperIdent EqBinder TermPat TermPat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data EqBinder
    = EqBinderEmpty | EqBinderVars EqBinderItem EqBinderRest
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data EqBinderRest
    = EqBinderRestNil | EqBinderRestCons EqBinderItem EqBinderRest
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data EqBinderItem = EqBinderMap Var TermLambda | EqBinderVar Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RwDecl
    = RwDeclSimple UpperIdent TermPat TermPat
    | RwDeclCond UpperIdent RwCond TermPat TermPat
    | RwDeclWeight UpperIdent TermPat TermPat Proc [Refinement]
    | RwDeclCondWeight UpperIdent RwCond TermPat TermPat Proc FoldFunc
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RwCond = RwCondStep Var Var | RwCondMulti Var Var RwCond
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Refinement = RefinementImpl Var Proc Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FoldFunc = FoldFuncImpl Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermPat
    = TermPatVar TermPat
    | TermPatConstr UpperIdent [TermPat]
    | TermPatBag TermPat Var
    | TermPatEval Var [TermPat]
    | TermPatMap TermPat TermPatLambda
    | TermPatBinder VarList TermPat
    | TermPatAtomVar Var
    | TermPatAtomUpper UpperIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TermPatLambda = TermPatLambdaImpl VarList TermPat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicClause
    = LogicClauseRule LogicHead [LogicBody]
    | LogicClauseRel Var [LogicType]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicHead = LogicHeadImpl Var [LogicArg]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicBody
    = LogicBodyAtom Var [LogicArg]
    | LogicBodyNeg Var [LogicArg]
    | LogicBodyIfLet Pattern LogicArg
    | LogicBodyIf LogicExpr
    | LogicBodyLet Var LogicExpr
    | LogicBodyFor Var LogicExpr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicExpr
    = LogicExprVar Var
    | LogicExprApp Var [LogicArg]
    | LogicExprComp LogicArg CompOp LogicArg
    | LogicExprDot Var Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicArg
    = LogicArgVar Var
    | LogicArgWild
    | LogicArgConst Ground
    | LogicArgClone Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LogicType = LogicTypeIdent UpperIdent | LogicTypeVec LogicType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype LongLiteral = LongLiteral ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype FloatLiteral = FloatLiteral ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype StringLiteral = StringLiteral String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype UriLiteral = UriLiteral String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Var = Var String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype UpperIdent = UpperIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype DollarIdent = DollarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype RustBlock = RustBlock String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition LongLiteral where
  hasPosition (LongLiteral (p, _)) = C.Just p

instance HasPosition FloatLiteral where
  hasPosition (FloatLiteral (p, _)) = C.Just p

